### ISSUE TITLE
Problem with 0.1.3 on mac

### ISSUE THREAD

**Issue by davidillsley** [Yubico/yubico-piv-tool#10]
Having downloaded the binary from https://developers.yubico.com/yubico-piv-tool/Releases/ I'm getting:

$ ~/bin/yubico-piv-tool-0.1.3-mac/bin/yubico-piv-tool 
dyld: Library not loaded: /Users/klas/yubico-piv-tool/tmp/root/lib/libykpiv.1.dylib
  Referenced from: /Users/davidillsley/bin/yubico-piv-tool-0.1.3-mac/bin/yubico-piv-tool
  Reason: image not found
Trace/BPT trap: 5

0.1.2 is fine.

**Comment by klali** [comment]
correct mac binaries are now pushed.
