### ISSUE TITLE
YKCS11 numbers the keys wrongly

### ISSUE THREAD

**Issue by mouse07410** [Yubico/yubico-piv-tool#100]
When listing the keys, their IDs should start from 1, not from 0. PIV Authentication key should be identified by `id=%01`, and CARD Authentication key - by `id=%04`.

Here's what I get using YKCS11:

```
$ p11tool --provider /usr/local/lib/libykcs11.dylib --list-privkeys --login
Token 'YubiKey PIV' with URL 'pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV' requires user PIN
Enter PIN: 
Object 0:
    URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%00;object=Private%20key%20for%20PIV%20Authentication%00;type=private
    Type: Private key
    Label: Private key for PIV Authentication
    Flags: CKA_PRIVATE; 
    ID: 00

Object 1:
    URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%01;object=Private%20key%20for%20Card%20Authentication%00;type=private
    Type: Private key
    Label: Private key for Card Authentication
    ID: 01

Object 2:
    URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%02;object=Private%20key%20for%20Digital%20Signature%00;type=private
    Type: Private key
    Label: Private key for Digital Signature
    Flags: CKA_PRIVATE; 
    ID: 02

Object 3:
    URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%03;object=Private%20key%20for%20Key%20Management%00;type=private
    Type: Private key
    Label: Private key for Key Management
    Flags: CKA_PRIVATE; CKA_ALWAYS_AUTH; 
    ID: 03
```

Here's the correct numbering done by OpenSC:

```
$ p11tool --provider /Library/OpenSC/lib/opensc-pkcs11.dylib --list-privkeys --login
Token 'PIV Card Holder pin (PIV_II)' with URL 'pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=4ffxxxxx;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29' requires user PIN
Enter PIN: 
Object 0:
    URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=4ffxxxxx;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%01;object=PIV%20AUTH%20key;type=private
    Type: Private key
    Label: PIV AUTH key
    Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
    ID: 01

Object 1:
    URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=4ffxxxxx;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%02;object=SIGN%20key;type=private
    Type: Private key
    Label: SIGN key
    Flags: CKA_PRIVATE; CKA_ALWAYS_AUTH; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
    ID: 02

Object 2:
    URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=4ffxxxxx;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%03;object=KEY%20MAN%20key;type=private
    Type: Private key
    Label: KEY MAN key
    Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
    ID: 03

Object 3:
    URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=4ffxxxxx;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%04;object=CARD%20AUTH%20key;type=private
    Type: Private key
    Label: CARD AUTH key
    Flags: CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
    ID: 04
```

Also note the difference in the object naming between the two. I would much prefer if YKCS11 would embrace already established OpenSC way, naming key `id=%02` as `object=SIGN%20key` instead of that monstrously long `object=Private%20key%20for%20Digital%20Signature%00`. This would make writing interoperable scripts far easier.

_Especially important are keys with_ `id=%00` _and_ `id=%01`, _because_ `PIV%20AUTH%20key` _is used for smartcard login. In your case_ `id=%01` _would've picked up the wrong key with the wrong KU and EKU on its corresponding certificate._

**Comment by dwmw2** [comment]
Strictly speaking, PKCS#11 says the ID should match the X509v3 Subject Key Identifier, doesn't it?

Is the OpenSC ID usage actually "correct" here, or just well-established and worth conforming to?

**Comment by mouse07410** [comment]
I don't know. OpenSC ID usage is certainly well-established (and mostly debugged by now), and probably worth conforming to.

On the other hand, if there's a case for adopting the naming that YKCS11 chose (because it conforms to the PKCS#11 standard better?), it' OK with me - especially if the OpenSC maintainers can be brought to agreement.

So, I don't really care which choice is picked as the "normative" - all I care for is having *one* common way.

**Comment by a-dma** [comment]
It is supposed to match, but it's not strictly enforced. From the specs:

>The CKA_ID attribute is intended as a means of distinguishing multiple public-key/private-key pairs held by the same subject (whether stored in the same token or not). (Since the keys are distinguished by subject name as well as identifier, it is possible that keys for different subjects may have the same CKA_ID value without introducing any ambiguity.)
It is intended in the interests of interoperability that the subject name and key identifier for a certificate will be the same as those for the corresponding public and private keys (though it is not required that all be stored in the same token). However, Cryptoki does not enforce this association, or even the uniqueness of the key identifier for a given subject; in particular, an application may leave the key identifier empty.
The CKA_ISSUER and CKA_SERIAL_NUMBER attributes are for compatibility with PKCS#7 and Privacy Enhanced Mail (RFC1421). Note that with the version 3 extensions to X.509 certificates, the key identifier may be carried in the certificate. It is intended that the CKA_ID value be identical to the key identifier in such a certificate extension, although this will not be enforced by Cryptoki.

I think that changing object numbering at this stage will break current implementations, something that I would like to avoid.

**Comment by mouse07410** [comment]
> I think that changing object numbering at this stage will break current implementations, something that I would like to avoid.

Alessio, let me be blunt - and no offense meant.

When YKCS11 came about, OpenSC has already been established, under heavy development, and mostly debugged. At this time YKCS11 barely works, and when it does it takes 3.5 times longer to complete an operation than OpenSC. This means that it would be silly for me (for example) to write scripts that utilize YKCS11 naming instead of OpenSC naming. And I need a way to at least name the keys in an interoperable way. Currently it works for slots 9c and 9d (great, thanks!), but is broken for 9a (which I really care for) and 9e (which is mostly for physical access, so I can't tell what impact this incompatibility may have).

If you do want YKCS11 to actually be *used*, I suggest you change the naming, **especially the indexing** of the keys  (that `id=` thing) **now**. Because if these two stay diverged - there's no reason for users to even *try* YKCS11. OpenSC library does everything YKCS11 library does, and works with all the tokens, *including* YubiKeys. YKCS11 sort of works with YubiKeys only, but as long as it is not OpenSC-compatible - there's no reason to even touch it.

**Comment by a-dma** [comment]
> Alessio, let me be blunt - and no offense meant.

None taken.

> When YKCS11 came about, OpenSC has already been established, under heavy development, and mostly debugged. At this time YKCS11 barely works, and when it does it takes 3.5 times longer to complete an operation than OpenSC. This means that it would be silly for me (for example) to write scripts that utilize YKCS11 naming instead of OpenSC naming. And I need a way to at least name the keys in an interoperable way. Currently it sort of works for slots 9c and 9d (great, thanks!) because I can address those keys as id=%02 and id=%03, but is broken for 9a (which I really care for) and 9e (which is mostly for physical access, so I can't tell yet what impact this incompatibility may have).

I think that saying it _barely_ works is an overstatement. I know of many applications where it does work for the intended purpose and it is actually in production systems. I do however agree with you that it needs extensive work.
If OpenSC's PKCS#11 module does what you want and checks all the boxes you're interested in, then by all means, I believe you should use it. With this I'm not saying that I don't care about ykcs11, I very much appreciate the effort that you and others have put in by reporting issues and providing solutions.

> If you do want YKCS11 to actually be used, I suggest you change the naming, especially the indexing of the keys (that id= thing) now.

Even if, as you put it, it is only a minority of people that use ykcs11, doing a backward-incompatible change like this is something that I can't just do willy-nilly. There is a series of repercussions that we should think about. It might be a sensible thing to do, but I don't think that **now** is the answer.

> Because if these two stay diverged - there's no reason for users to even try YKCS11. OpenSC library does everything YKCS11 library does, and works with all the tokens, including YubiKeys (how do I know? I use OpenSC with CAC and YubiKeys). YKCS11 sort of works, and with YubiKeys only. As long as it is not OpenSC-compatible - there's no reason to even touch it.

We never meant for ykcs11 to be a complete replacement of OpenSC's module. Furthermore, last I checked that module is not capable of generating keys and setting touch-to-sign on YubiKeys. Moreover, it is an additional dependency. This module comes "for free" with `yubico-piv-tool` which you still need to personalize the device anyway. It might be enough to get you off the ground.

If we can get the two to inter-operate I think it would be a plus, but it will also make other users unhappy.

**Comment by mouse07410** [comment]
> If OpenSC's PKCS#11 module does what you want and checks all the boxes you're interested in, then by all means, I believe you should use it.

Which is exactly what I'm doing. I hoped to give a try to YKCS11, and keep it as a steady second option once its kinks are straightened out.

But if it remains incompatible - the cost of maintaining two different sets of scripts and such just makes it not worth the trouble.

> Even if, as you put it, it is only a minority of people that use ykcs11, doing a backward-incompatible change like this is something that I can't just do willy-nilly. There is a series of repercussions that we should think about.

Would they mind a one-time change, especially if it allows them to re-use their scripts and apps on another platform (OpenSC)?

> It might be a sensible thing to do, but I don't think that now is the answer.

The longer you wait - the more mature YKCS11 becomes, the (potentially) more users it would have, the more scripts those users would accumulate - overall, the longer you wait - the more difficult the move would become.

> We never meant for ykcs11 to be a complete replacement of OpenSC's module.

What is its purpose then?

> Furthermore, last I checked that module is not capable of generating keys and setting touch-to-sign on YubiKeys. 

Don't know about generating keys - I generate signing keys with Yubico tools (not using anybody's libraries with 3rd party tools), and load encryption keys generated in software (escrow and backup purposes). I concur regarding setting touch-to-sign on YubiKey 4.

> Moreover, it is an additional dependency. 

I'm not sure I understand. Could you clarify please?

> This module comes "for free" with yubico-piv-tool which you still need to personalize the device anyway.

That is correct. So basically it's just to make the design cleaner - separating the "tool" (yubico-piv-tool) from the "library" (libykcs11). OK then.

> If we can get the two to inter-operate I think it would be a plus, but it will also make other users unhappy.

I strongly doubt that it would make anybody unhappy if your key indexing changed to become compatible with OpenSC. Especially since you said, "We never meant for ykcs11 to be a complete replacement of OpenSC's module" - so you expect that people would use OpenSC to access these tokens after they are provisioned. Why would these people be upset if you allow them to use the same key numbering (at least), or maybe even the same key naming for both ykcs11 and OpenSC? You think they prefer to maintain two distinct versions of command scripts instead of one?

**Comment by dwmw2** [comment]
@mouse07410 I think you're overstating the problem. It is not the end of the world if, in order to use a different PKCS#11 provider, you use a different identifier for the keys therein. As things stand, you can have them both installed together and select which one to use at runtime — using either `pkcs11:manufacturer=piv_II;id=...` for OpenSC or `pkcs11:model=YubiKey%20NEO;id=...` for YKCS11.

Note that the URI is *already* different... having the ID and the object names be different is slightly suboptimal but really isn't that much of a barrier to adoption.

Perhaps it would be nice if YKCS11 could have a configure-time option to make it use the same labels and IDs as OpenSC does for the keys Then existing deployments of YKCS11 would continue to build without that option, but when we package it for Linux distributions we'd use it.

Then again, for Linux distributions I suspect the best path forward is to add the missing Yubikey-specific features to OpenSC and still not ship YKCS11.

**Comment by a-dma** [comment]
> Would they mind a one-time change, especially if it allows them to re-use their scripts and apps on another platform (OpenSC)?

I'd say yes. If they're not interested in using OpenSC stuff they would have to change their system just to retain the same functionality.

> The longer you wait - the more mature YKCS11 becomes, the (potentially) more users it would have, the more scripts those users would accumulate - overall, the longer you wait - the more difficult the move would become.

This is also true.

> What is its purpose then?

To provide a way of using PKCS#11 with YubiKeys and PIV. Solving key generation, import, and vendor-specific configuration. At least to begin with. If in the future we can expand this to cover more use-cases, then even better. As always bugs are clearly unacceptable, no matter what.

> I'm not sure I understand. Could you clarify please?

I meant that in this case you would have to install more software, namely the whole OpenSC "stack". Probably not a big deal for the average user, but on a production system where you want to have the minimum amount of components it is another thing to think/worry about.

> That is correct. So basically it's just to make the design cleaner - separating the "tool" (yubico-piv-tool) from the "library" (libykcs11). OK then.

Not really. When it comes down to this ykcs11 is really completely separated from yubico-piv-tool. The only thing the have in common is libykpiv, which both of them use.

> I strongly doubt that it would make anybody unhappy if your key indexing changed to become compatible with OpenSC. Especially since you said, "We never meant for ykcs11 to be a complete replacement of OpenSC's module" - so you expect that people would use OpenSC to access these tokens after they are provisioned. Why would these people be upset if you allow them to use the same key numbering (at least), or maybe even the same key naming for both ykcs11 and OpenSC? You think they prefer to maintain two distinct versions of command scripts instead of one?

As @dwmw2 said I don't think this is really the end of the world. If you're willing to maintain two different systems, then you should be prepared to deal with what that entails, e.g., having a different set of scripts. I agree that reducing the friction between different tools is a good thing, I'm not saying that I oppose to this change, in principle.

**Comment by mouse07410** [comment]
> ...If you're willing to maintain two different systems, then you should be prepared to deal with what that entails...

But this is the point - I did not plan to maintain two different systems. I just noticed that `yubico-piv-tool` (which I need to provision the tokens anyway) comes with YKCS11, and tried to figure what it might be good for.

**Comment by qpernil** [comment]
Hi,

yubico-piv-tool 2.0.0 is a major new release of ykcs11, now ith a fairly complete pkcs11 implementation that is compatible with the opensc pkcs11 regarding CKA_ID values. We haven't changed the slot labels, but why not let your scripts select key by CKA_ID instead ? 

I'm closing this issue now, please open a new issue if you find bugs in the new release
