### ISSUE TITLE
YKCS11 does not display the correct serial number of the token

### ISSUE THREAD

**Issue by mouse07410** [Yubico/yubico-piv-tool#101]
YKCS11 always returns `1234` as the token's serial number. Here's one example:

```
$ examples/.libs/auth /usr/local/lib/libykcs11.dylib 
Slot manufacturer......: Yubico
Slot description.......: Yubico Yubikey NEO OTP+U2F+CCID
Slot token label.......: YubiKey PIV
Slot token manufacturer: Yubico
Slot token model.......: YubiKey NEO
Slot token serialnr....: 1234
Password for token YubiKey PIV: authentication successfull.
$ 
```

I'm not sure if it's a deliberate attempt to hide/mask the real serial number of the token, but probably it's a bug. So unless you really did not mean to display the token serial number upon request - please consider fixing it.

**Comment by a-dma** [comment]
It's deliberate, there is no way of extracting the serial number from PIV.

**Comment by mouse07410** [comment]
OK. Would it make sense to present the *token* serial number here instead?

I'm a little confused by this obviously useless piece of data being presented for reason I don't understand.

**Comment by a-dma** [comment]
It would, but there is no easy way of getting the serial number out.
The first 16 bytes of the `CCC` or `CHUID` could be used, but that is not guaranteed to be set.

**Comment by mouse07410** [comment]
Is there any reason then to output that field at all? Considering that its value is completely meaningless? Wouldn't it be better to just remove that line altogether?

**Comment by a-dma** [comment]
Yes, it is not optional.

**Comment by mouse07410** [comment]
Let me understand. The field is not optional, but filling it with the correct value is not required?

**Comment by a-dma** [comment]
Well, there has to be a value in there. Technically it could be the empty string, which might make more sense, but there has to be something. Nothing is mentioned on the specs about the correctness.

**Comment by mouse07410** [comment]
> Nothing is mentioned on the specs about the correctness

In that case I have nothing else to add here.

**Comment by rmhrisk** [comment]
If you are not going to use the correct value I would like to suggest you return "CORRECT_VALUE_GOES_HERE".

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 contains a major upgrade to ykcs11. Please try with that version.
I believe the issue has been adressed, closing the issue. Please re-open if the problem persists.
