### ISSUE TITLE
ykcs11: 'agent refused operation' after doing any operations on yubikey

### ISSUE THREAD

**Issue by Gh0u1L5** [Yubico/yubico-piv-tool#102]
The error messages are exactly the same as in #88 .
The version of Mac OSX is 10.12.1
The version of OpenSSL library is 1.0.2j

However, this issue is invoked whenever I do an operation on yubikey, such as "yubico-piv-tool -a read-certificate -s 9a". So it's not just something about sleep/wake in OSX system. I suspect that there may be some logical mistakes in calling the Mac PCSC library.

**Comment by Gh0u1L5** [comment]
Sorry, I thought I fixed this issue, but after few tests I noticed that it still fails.

**Comment by a-dma** [comment]
could you please be a bit more specific on how to repro this?

**Comment by aoeldemann** [comment]
I am facing an issue, which I think is related to this one. I am using macOS 10.12.2.

After re-inserting the YubiKey and trying to authenticate myself via SHH, I'm getting the following error:

> sign_and_send_pubkey: signing failed: agent refused operation

I am currently using the current workaround:

> echo "dummy" | gpg --encrypt | gpg --decrypt > /dev/null 2>&1

On decryption, I am asked for the PIN and the YubiKey is _unlocked_. Afterwards SSH authentication works until I remove and re-insert the YubiKey.

I am using GPG version 2.0.30 (homebrew) and set SSH_AUTH_SOCK to the gpg-agent ssh socket.

Any ideas on how to solve this problem? Thanks!

**Comment by a-dma** [comment]
I'm a bit confused, you're saying this is related to this issue, which is about `ykcs11`, which in turn uses the PIV application on the YubiKey, but then you mention gpg.
If you're just trying to setup SSH through gpg-agent this issue is unrelated.

**Comment by aoeldemann** [comment]
Okay, maybe it was simply the fact that I am receiving the same error "agent refused operation" and I am using macOS Sierra as well (works without problems on Ubuntu) that led me to believe it's related. Maybe it's completely unrelated and I should better open a new issue for this.

**Comment by a-dma** [comment]
Aha, now I got you now.
Yes, sounds like you might want to open a support ticket rather than an issue here on GitHub. Also try to add some more debug info if you can.

**Comment by suvash** [comment]
@aoeldemann had the same problem and found a solution for it. Reading above, I believe you are using gpg-agent's support for ssh. As mentioned in the manual for gpg-agent, one has to update the tty info for the agent by running
`gpg-connect-agent updatestartuptty /bye` (instead of simply `gpg-connect-agent /bye` in your `.bashrc` etc)

**Comment by Gh0u1L5** [comment]
@a-dma Here're the steps to reproduce the problem.
1. Generate new key and self-signed certificates as mentioned in this link:
https://developers.yubico.com/PIV/Guides/SSH_user_certificates.html
2. Add the public key to a server and try ssh to it, all works.
3. Execute "yubico-piv-tool -a read-certificate -s 9a"
4. Try "ssh -v server" again, failed, with error message "sign_and_send_pubkey: signing failed: agent refused operation"

**Comment by Gh0u1L5** [comment]
Currently my macOS version is Sierra 10.12.5 (16F73), with OpenSSH 7.4p1, OpenSSL 0.9.8zh.
The firmware of yubikey is 4.3.3, the version of yubico-piv-tool is 1.4.3.
Besides the situation I mentioned above, the ykcs11 library also failed to sign data after sleep/awake.

**Comment by Gh0u1L5** [comment]
Following two comments are the logs from ykcs11 library compiled with --enable-ykcs11-debug

**Comment by Gh0u1L5** [comment]
This is the log when I log in successfully
debug: ykcs11.c:1313 (C_FindObjectsInit): In
debug: ykcs11.c:1346 (C_FindObjectsInit): Keeping private objects
debug: ykcs11.c:1357 (C_FindObjectsInit): Initialized search with 3 parameters
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 0, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 0 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 1, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 1 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 2, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 2 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 3, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 3 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 4, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 4 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 5, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 5 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 6, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 6 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 7, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 7 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 8, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 8 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 9, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 9 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 10, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 10 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 11, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 11 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 12, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 12 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 13, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 13 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 14, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 14 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 15, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 15 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 16, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 16 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 17, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 17 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 18, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 18 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 19, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 19 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 20, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 20 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 21, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 21 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 22, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 22 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 23, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 23 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 24, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 24 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 25, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 25 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 26, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 26 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 27, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 27 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:398 (get_doa): For data object 28, get 
debug: objects.c:402 (get_doa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 28 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:482 (get_coa): For certificate object 37, get 
debug: objects.c:486 (get_coa): CLASS
debug: objects.c:482 (get_coa): For certificate object 37, get 
debug: objects.c:486 (get_coa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 37 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:482 (get_coa): For certificate object 38, get 
debug: objects.c:486 (get_coa): CLASS
debug: objects.c:482 (get_coa): For certificate object 38, get 
debug: objects.c:486 (get_coa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 38 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:591 (get_proa): For private key object 62, get 
debug: objects.c:595 (get_proa): CLASS
debug: objects.c:591 (get_proa): For private key object 62, get 
debug: objects.c:595 (get_proa): CLASS
debug: ykcs11.c:1385 (C_FindObjectsInit): Keeping object 62 in the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 1
Type: 258 Value: 16140901064495857664 Len: 1
debug: objects.c:591 (get_proa): For private key object 62, get 
debug: objects.c:636 (get_proa): ID
debug: objects.c:591 (get_proa): For private key object 62, get 
debug: objects.c:636 (get_proa): ID
debug: ykcs11.c:1385 (C_FindObjectsInit): Keeping object 62 in the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 2
Type: 264 Value: 769 Len: 1
debug: objects.c:591 (get_proa): For private key object 62, get 
debug: objects.c:661 (get_proa): SIGN
debug: objects.c:591 (get_proa): For private key object 62, get 
debug: objects.c:661 (get_proa): SIGN
debug: ykcs11.c:1385 (C_FindObjectsInit): Keeping object 62 in the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:591 (get_proa): For private key object 63, get 
debug: objects.c:595 (get_proa): CLASS
debug: objects.c:591 (get_proa): For private key object 63, get 
debug: objects.c:595 (get_proa): CLASS
debug: ykcs11.c:1385 (C_FindObjectsInit): Keeping object 63 in the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 1
Type: 258 Value: 16140901064495857664 Len: 1
debug: objects.c:591 (get_proa): For private key object 63, get 
debug: objects.c:636 (get_proa): ID
debug: objects.c:591 (get_proa): For private key object 63, get 
debug: objects.c:636 (get_proa): ID
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 63 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:832 (get_puoa): For public key object 87, get 
debug: objects.c:836 (get_puoa): CLASS
debug: objects.c:832 (get_puoa): For public key object 87, get 
debug: objects.c:836 (get_puoa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 87 from the list
debug: ykcs11.c:1376 (C_FindObjectsInit): Parameter 0
Type: 0 Value: 3 Len: 8
debug: objects.c:832 (get_puoa): For public key object 88, get 
debug: objects.c:836 (get_puoa): CLASS
debug: objects.c:832 (get_puoa): For public key object 88, get 
debug: objects.c:836 (get_puoa): CLASS
debug: ykcs11.c:1379 (C_FindObjectsInit): Removing object 88 from the list
debug: ykcs11.c:1389 (C_FindObjectsInit): 1 object(s) left after attribute matching
debug: ykcs11.c:1393 (C_FindObjectsInit): Out
debug: ykcs11.c:1404 (C_FindObjects): In
debug: ykcs11.c:1429 (C_FindObjects): Can return 1 object(s)
debug: ykcs11.c:1445 (C_FindObjects): Returning object 62
debug: ykcs11.c:1454 (C_FindObjectsFinal): In
debug: ykcs11.c:1479 (C_FindObjectsFinal): Out
debug: ykcs11.c:1701 (C_SignInit): In
debug: ykcs11.c:1726 (C_SignInit): Trying to sign some data with mechanism 1 and key 62
debug: objects.c:591 (get_proa): For private key object 62, get 
debug: objects.c:623 (get_proa): KEY TYPE
debug: ykcs11.c:1741 (C_SignInit): Key type is 0

debug: objects.c:591 (get_proa): For private key object 62, get 
debug: objects.c:737 (get_proa): MODULUS BITS
debug: ykcs11.c:1800 (C_SignInit): Key length is 2048 bit
debug: ykcs11.c:1808 (C_SignInit): Algorithm is 7
debug: ykcs11.c:1825 (C_SignInit): Out
debug: ykcs11.c:1840 (C_Sign): In
debug: ykcs11.c:1890 (C_Sign): Sending 35 bytes to sign
30 21 30 09 06 05 2b 0e 03 02 1a 05 00 04 14 3a a3 e1 a9 89 c8 6d 96 2d 48 5a be c8 20 b0 ae 68 1b d7 3a 
debug: openssl_utils.c:538 (do_pkcs_1_t1): Apply padding to 35 bytes and get 256

debug: ykcs11.c:1931 (C_Sign): Using key 9a
debug: ykcs11.c:1932 (C_Sign): After padding and transformation there are 256 bytes
00 01 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 30 21 30 09 06 05 2b 0e 03 02 1a 05 00 04 14 3a a3 e1 a9 89 c8 6d 96 2d 48 5a be c8 20 b0 ae 68 1b d7 3a 
debug: ykcs11.c:1953 (C_Sign): Got 256 bytes back
76 a0 fd 2b 24 27 2c d2 e9 8b 4d 62 c2 59 51 fb 21 d5 64 2e 34 3f d6 4b 1d 36 88 60 26 29 8f 8a ef 9c ec d3 f9 6f 00 61 02 0e 88 2e a8 14 13 4a e9 bb 24 47 4d 5a 68 02 c9 97 b1 09 bb 9d 3d b4 a5 2b 3d b0 bf 27 63 7b 3e 74 fd 07 cd a8 6b e7 88 8d bd f2 f7 0f 30 cc 05 ce ec 7e 61 41 de f2 08 b2 2f b8 36 06 d4 ed 41 01 fe d0 2f 11 83 a0 07 ff 6b d1 0a d7 9b 1f 31 d4 fa 11 ee ce b8 08 c4 6e 9d 0a 6a 6c 1c a9 f3 67 bb 49 98 7e b0 6f b0 45 08 69 23 38 1d dc a0 06 83 17 24 cc 9f 4c 2f f1 75 ea fa 4a 4a 4e a3 6f aa ba 99 9a db 67 f9 d0 50 79 b7 32 2f 83 be 20 28 09 07 aa 50 d8 2f 49 06 5f a7 e4 1d e0 18 5c 1e 76 3f cc 26 32 7e 50 0a 5e 55 d6 1d e9 1e 7c 4a 81 43 76 4d bf 95 ec 75 c0 b2 3f 9d c3 15 69 a8 55 a4 59 81 f9 83 a0 8d 57 60 0d 31 75 70 8c 8d 84 4b f1 90 21 
debug: ykcs11.c:1977 (C_Sign): Out

**Comment by Gh0u1L5** [comment]
And here's the log when things go **wrong**

debug: objects.c:591 (get_proa): For private key object 62, get 
debug: objects.c:737 (get_proa): MODULUS BITS
debug: ykcs11.c:1800 (C_SignInit): Key length is 2048 bit
debug: ykcs11.c:1808 (C_SignInit): Algorithm is 7
debug: ykcs11.c:1825 (C_SignInit): Out
debug: ykcs11.c:1840 (C_Sign): In
debug: ykcs11.c:1890 (C_Sign): Sending 35 bytes to sign
30 21 30 09 06 05 2b 0e 03 02 1a 05 00 04 14 c7 b2 83 d4 32 ce 2c 9b b7 e6 44 d0 aa 44 45 f0 72 7f c3 76 
debug: openssl_utils.c:538 (do_pkcs_1_t1): Apply padding to 35 bytes and get 256

debug: ykcs11.c:1931 (C_Sign): Using key 9a
debug: ykcs11.c:1932 (C_Sign): After padding and transformation there are 256 bytes
00 01 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 30 21 30 09 06 05 2b 0e 03 02 1a 05 00 04 14 c7 b2 83 d4 32 ce 2c 9b b7 e6 44 d0 aa 44 45 f0 72 7f c3 76 
error: Failed to begin pcsc transaction, rc=ffffffff80100068
Sign command failed to communicate.
debug: ykcs11.c:1947 (C_Sign): Sign error, Error in PCSC call
debug: ykcs11.c:1977 (C_Sign): Out
process_sign_request2: sshkey_sign: error in libcrypto

**Comment by Gh0u1L5** [comment]
Solved in recent commits.
