### ISSUE TITLE
Doesn't build with openssl 1.1

### ISSUE THREAD

**Issue by mmuehlenhoff** [Yubico/yubico-piv-tool#104]
yubico-piv-tool fails to build with the latest openssl release 1.1 (which has made some API changes), please see this Debian bug for a build log and pointers to documentation for the API changes:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828616

**Comment by Jakuje** [comment]
Any update on this? There was a new release, but this didn't change.
Most of the changes needed are already in place in my PR, but since I do not see any feedback, I do not see any motivation to continue with further investigation.

**Comment by klali** [comment]
Not really an update.. It would be great to have 1.1 compatibility in place but I haven't had time to work on the remaining pieces of it. Do you think #107 is mergeable as is or should we try to have full compat in place before we merge anything?

**Comment by Jakuje** [comment]
It is quite much done, but merging only this part will not make it build and therefore it is still quite useless. I will review the changes once more and I will try to think about the missing bits.
