### ISSUE TITLE
Ability to set touch policy for Yubikey 4

### ISSUE THREAD

**Issue by mouse07410** [Yubico/yubico-piv-tool#105]
First, I'd like that capability to be available in your GUI as well, not only in the CLI `yubico-piv-tool`.

Second - I'd like to be able to modify that setting *after* the key and its corresponding certificate is loaded, not only *when* the key is loaded.

**Comment by klali** [comment]
An issue about touch functionality in the GUI was opened recently, this request fits better in that repo: https://github.com/Yubico/yubikey-piv-manager/issues/18

As for locking the touch setting at key load this was decided when implementing it, not something that can be controlled by a tool like yubico-piv-tool.

**Comment by mouse07410** [comment]
> As for locking the touch setting at key load this was decided when implementing it, not something that can be controlled by a tool like yubico-piv-tool.

@klali can this decision be revisited? I see neither advantages nor security benefits of this restriction (except maybe that if I *generate* the key on the card with "touch-policy" enabled, there would be impossible to undo that later on - only by loading or generating a new key)...

**Comment by klali** [comment]
Please contact Yubico support for feedback about the behaviour/features of the device.
