### ISSUE TITLE
YKCS11 methods to return more adequate values

### ISSUE THREAD

**Issue by alexyack** [Yubico/yubico-piv-tool#106]
According to PKCS#11 Chapter 11 (in version 2.20 on page 90):

> A Cryptoki library need not support every function in the Cryptoki API. However, even
> an unsupported function must have a “stub” in the library which simply returns the value
> CKR_FUNCTION_NOT_SUPPORTED. The function’s entry in the library’s
> CK_FUNCTION_LIST structure (as obtained by C_GetFunctionList) should point to
> this stub function (see Section 9.6).

Also please force C_WaitForSlotEvent to return CKR_NO_EVENT instead of CKR_FUNCTION_FAILED - it will be more  correct.

Issue #84 resolved by not the best way.

**Comment by tgeoghegan** [comment]
The same problem applies to the implementation of C_InitToken, which:

```
CK_DEFINE_FUNCTION(CK_RV, C_InitToken)(
  CK_SLOT_ID slotID,
  CK_UTF8CHAR_PTR pPin,
  CK_ULONG ulPinLen,
  CK_UTF8CHAR_PTR pLabel
)
{
  DIN;
  DBG("Token initialization unsupported");
  DOUT;
  return CKR_FUNCTION_FAILED;
}
```
CKR_FUNCTION_NOT_SUPPORTED would be more appropriate, and would have saved me some debugging time.

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 contains a major upgrade to ykcs11. Please try with that version.
I believe the issue has been adressed, closing the issue. Please re-open if the problem persists.
