### ISSUE TITLE
YKCS C_GenerateKeyPair return CKR_DEVICE_ERROR for 9c

### ISSUE THREAD

**Issue by gzhong-dm** [Yubico/yubico-piv-tool#108]
YKCS C_GenerateKeyPair return CKR_DEVICE_ERROR for 9c, while works for other slots

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 is out and contains a major update to ykcs11. Please try with that version.
I believe the issue you mention has been adressed in that release, so I'm closing this issue due to age.
Please re-open if the problem persists.
