### ISSUE TITLE
Wrong string names for info structures

### ISSUE THREAD

**Issue by microshine** [Yubico/yubico-piv-tool#109]
Spec from PKCS#11
https://www.cryptsoft.com/pkcs11doc/v230/structCK__SLOT__INFO.html
```
Must be padded with the blank character (' ‘). Should ''not'' be null-terminated
```

As I can see Yubico returns null terminations.

__Yubico SLOT_INFO__
<img width="500" alt="i61 pimgpsh_fullsize_distr" src="https://cloud.githubusercontent.com/assets/7333669/24022991/8278e35a-0aba-11e7-9a14-d163dd317c0a.png">

__SoftHSM SLOT_INFO__
<img width="399" alt="i60 pimgpsh_fullsize_distr" src="https://cloud.githubusercontent.com/assets/7333669/24022995/84f8b84e-0aba-11e7-925d-7405497517f7.png">

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 is out and contains a major update to ykcs11. Please try with that version.
The issue you mention has ben adressed in that release, so I'm closing this release due to age.
Please re-open if the problem persists.
