### ISSUE TITLE
Failed to import Windows Certificate 

### ISSUE THREAD

**Issue by busbauen** [Yubico/yubico-piv-tool#11]
Hey,
I'm trying to get a Windows Certificate on my YoubKey. I followed the steps according to https://developers.yubico.com/yubico-piv-tool/Windows_certificate.html

While importing (yubico-piv-tool -s 9a -a import-certificate -i cert.crt) the certificate I get an error:
Failed loading certificate for import.

I have no Windows CA so I used the CA of my raspberry pi. Is there any difference between the signing?

I used these commands:
openssl x509 -req -days 3650 -in request.csr -signkey ca.key -out newcert.pem
openssl x509 -outform der -in newcert.pem -out newcert.crt

Thx

**Comment by busbauen** [comment]
Solved the issue by using
openssl x509 -outform pem -in newcert.pem -out newcert2.crt

:+1:

**Comment by klali** [comment]
Hello,

Yes, as you realise you need the certificate in pem format, so the conversion line is not needed at all.

/klas
