### ISSUE TITLE
RSA-PSS support on yubikeys

### ISSUE THREAD

**Issue by hannesm** [Yubico/yubico-piv-tool#111]
(I'm not sure whether this is the right repository for this issue, please direct me to a more appropriate place if this is the wrong one)

I have a YubiKey NEO and a YubiKey nano, and would like to do some RSA-PSS signatures with this (via PKCS11 API).

I managed to generate a RSA key using `yubico-piv-tool`.  Now, using `pkcs11-tool` from the `opensc` project, I tried to do some signatures, first some information:

```
# pkcs11-tool -L
Available slots:
Slot 0 (0x0): Alcor Micro AU9560 00 00
  (empty)
Slot 1 (0x4): Yubico Yubikey 4 OTP+U2F+CCID 01 00
  token label        : PIV_II (PIV Card Holder pin)
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : rng, login required, PIN initialized, token initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 00000000

Slot 1 (0x4): Yubico Yubikey NEO OTP+U2F+CCID 01 00
  token label        : PIV_II (PIV Card Holder pin)
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : rng, login required, PIN initialized, token initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 00000000
```

Now, listing the available mechanisms:

```
# pkcs11-tool -M
Using slot 1 with a present token (0x4)
Supported mechanisms:
  SHA-1, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  GOSTR3411, digest
  ECDSA, keySize={256,384}, hw, sign, other flags=0x1800000
  ECDH1-COFACTOR-DERIVE, keySize={256,384}, hw, derive, other flags=0x1800000
  ECDH1-DERIVE, keySize={256,384}, hw, derive, other flags=0x1800000
  RSA-X-509, keySize={1024,3072}, hw, decrypt, sign, verify
  RSA-PKCS, keySize={1024,3072}, hw, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={1024,3072}, sign, verify
  SHA256-RSA-PKCS, keySize={1024,3072}, sign, verify
  SHA384-RSA-PKCS, keySize={1024,3072}, sign, verify
  SHA512-RSA-PKCS, keySize={1024,3072}, sign, verify
  MD5-RSA-PKCS, keySize={1024,3072}, sign, verify
  RIPEMD160-RSA-PKCS, keySize={1024,3072}, sign, verify
```

I'm somehow missing any mention of PSS here, also trying to sign using RSA-PSS, I get CKR_MECHANISM_INVALID instead of a signature.  Any help how to achieve a PSS signature (according to the [docs](https://developers.yubico.com/yubico-piv-tool/YKCS11_release_notes.html), it should be supported.)

**Comment by klali** [comment]
The opensc tools don't support PSS at all, so with those tools it will not be possible for you to do PSS.

The pkcs11 module included in this project (ykcs11) should support PSS, but it will not work with pkcs11-tool which doesn't.

**Comment by hannesm** [comment]
@klali thanks for your reply.  according to `strings`, the opensc tool at least knows about both PKCS and PSS mechanisms.  I'll try the ykcs11 and my own tooling soon -- here the label (in opensc terms `SIGN key`) seems to be different.

**Comment by hannesm** [comment]
(I found it - `0: 64 {"CKA_LABEL":"Private key for Digital Signature\u0000"} {"CKA_CLASS":"CKO_PRIVATE_KEY"}`)

I can use this private key (and ykcs11) to generate a PKCS1 v1.5 signature, but when I attempt to do a PSS signature (using the same code path calling out to `sign_init` and `sign`), with params: CKM_SHA256, mgf = CKG_MGF1_SHA256, len = 32, and CKM_SHA256_RSA_PKCS_PSS, I get CKR_FUNCTION_FAILED.

is there anything specific to look at for PSS support? according to the above mentioned release notes, the PSS signing in ykcs11 is untested -- has it been tested in the meantime?

**Comment by klali** [comment]
Yeah, unfortunately that is still true. The code is there, but as you've discovered it seems to be buggy.

**Comment by hannesm** [comment]
@klali thx again... is this likely in YKCS11, or rather in the (non-open source (AFAICT) yubikey neo/nano firmware) -- i.e. do I have a chance to debug and fix it myself or should I get a HSM which is tested with PSS?

**Comment by klali** [comment]
it should be entirely in ykcs11

**Comment by hannesm** [comment]
(I opened PR #113 for PSS, which at least locally works with my Yubikey NEO)

**Comment by hannesm** [comment]
closing since #113 was merged.  thanks!
