### ISSUE TITLE
Missing cmdline.h on build

### ISSUE THREAD

**Issue by norbusan** [Yubico/yubico-piv-tool#122]
It seems that the files generated by gengetopt were not completely included in the release tar ball, or that the makefile is missing some parts, because I get the following errors:
```
In file included from ../../ykcs11/ykcs11.c:45:0:
../../ykcs11/../tool/util.h:38:10: fatal error: cmdline.h: No such file or directory
 #include "cmdline.h"
          ^~~~~~~~~~~
```
Any suggestions?

Thanks

Norbert

**Comment by klali** [comment]
This looks like you maybe used the github generated tarball? Please use one from https://developers.yubico.com/yubico-piv-tool/Releases/ it should contain all generated files.

**Comment by norbusan** [comment]
Indeed, thanks and sorry for the noise.
