### ISSUE TITLE
open flag for binary files.

### ISSUE THREAD

**Issue by chanchanzhang** [Yubico/yubico-piv-tool#123]
in open_file, file are opened as text files not binary file.
On Windows, when write file as text, hex value 0xA will be replaced with 0x0D 0x0A.
This causes error if the output is a binary file, as you can see below, the RSA2048 signature file size is 259 not 256 becaue 3 extra bytes "0x0D" is introduced.
`-rw-r--r-- 1 chanchaz 1049089     259 Sep  8 11:21 token_signed`

I suggest put a thrid parameter in 
`tool/util.c:FILE *open_file(const char *file_name, int mode)`
to mark if open as binary file.

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 contains a major upgrade to ykcs11. Please try with that version.
I believe the issue has been adressed, closing the issue. Please re-open if the problem persists.
