### ISSUE TITLE
Current ykcs11.dylib screws up key usage and therefore fails to decrypt or sign

### ISSUE THREAD

**Issue by mouse07410** [Yubico/yubico-piv-tool#124]
```
$ p11tool --login --list-keys "pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV"
Token 'YubiKey PIV' with URL 'pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV' requires user PIN
Enter PIN: 
Object 0:
	URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%00;object=Private%20key%20for%20PIV%20Authentication%00;type=private
	Type: Private key
	Label: Private key for PIV Authentication
	Flags: CKA_PRIVATE; 
	ID: 00

Object 1:
	URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%01;object=Private%20key%20for%20Card%20Authentication%00;type=private
	Type: Private key
	Label: Private key for Card Authentication
	ID: 01

Object 2:
	URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%02;object=Private%20key%20for%20Digital%20Signature%00;type=private
	Type: Private key
	Label: Private key for Digital Signature
	Flags: CKA_PRIVATE; 
	ID: 02

Object 3:
	URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%03;object=Private%20key%20for%20Key%20Management%00;type=private
	Type: Private key
	Label: Private key for Key Management
	Flags: CKA_PRIVATE; CKA_ALWAYS_AUTH; 
	ID: 03
```

`CKA_ALWAYS_AUTHENTICATE` flag mysteriously jumped from the Digital Signature key (the one that requires it by default) to the Key Management key (which AFAIK never has that flag set). And it fails to decrypt the file.

Trying RSA-OAEP decryption using `ykcs11.dylib` (note: padding in this case is done by OpenSSL software):
```
$ openssl pkeyutl -engine pkcs11 -keyform engine -decrypt -inkey "pkcs11:token=YubiKey%20PIV;id=%03;type=private" -in t256.dat.enc.oaep -out t256.dat.dec -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_mgf1_md:sha512 -pkeyopt rsa_oaep_md:sha512 
engine "pkcs11" set.
Enter PKCS#11 token PIN for YubiKey PIV:
Enter PKCS#11 key PIN for Private key for Key Management:
Public Key operation error
140736842581000:error:82079103:PKCS#11 module:pkcs11_private_decrypt:User type invalid:p11_rsa.c:154:
$
```

Same file to decrypt, same token, same OpenSSL, but using `opensc-pkcs11.dylib`:
```
$ openssl pkeyutl -engine pkcs11 -keyform engine -decrypt -inkey "pkcs11:token=Uri%20the%20Great;object=KEY%20MAN%20key;type=private" -in t256.dat.enc.oaep -out t256.dat.dec -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_mgf1_md:sha512 -pkeyopt rsa_oaep_md:sha512 
engine "pkcs11" set.
Enter PKCS#11 token PIN for Uri the Great:
$
```
Successfully decrypted.

And since ykcs11 screwed up the ALWAYS_AUTHENTICATE, naturally it cannot do signatures either:
```
$ pkcs11-tool --module /usr/local/lib/libykcs11.dylib -s -m SHA512-RSA-PKCS-PSS --id 02 -i t2570.dat -o t2570.dat.sig3.pss
Using slot 0 with a present token (0x0)
Logging in to "YubiKey PIV".
Please enter User PIN: 
Using signature algorithm SHA512-RSA-PKCS-PSS
PSS parameters: hashAlg=SHA512, mgf=MGF1-SHA512, salt=64 B
error: PKCS11 function C_SignUpdate failed: rv = CKR_FUNCTION_FAILED (0x6)
Aborting.
$ 
```
I didn't bother to collect SPY output, but it's fairly obvious that it fails because the key requires authentication that was never provided.

**Comment by chanchanzhang** [comment]
I happen to get same error using pkcs11-tool, after enable debugging I found C_SignUpdate is actually not defined in ykcs11.c:
CK_DEFINE_FUNCTION(CK_RV, C_SignUpdate)(
  CK_SESSION_HANDLE hSession,
  CK_BYTE_PTR pPart,
  CK_ULONG ulPartLen
)
{
  DIN;
  DBG("TODO!!!");
  DOUT;
  return CKR_FUNCTION_FAILED;
}

Thoughts?

**Comment by mouse07410** [comment]
@klali is anybody planning to address this bug? Or don't you think that misplacing CKA_ALWAYS_AUTH on a key is a problem?

**Comment by klali** [comment]
It is on our radar that there are problems with ykcs11 (this issue among others). It's not in the immediate pipe to take care of though.

@chanchanzhang that does not seem relevant for this bug, however only the complete signature with C_Sign() is implemented

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 is out and contains a major update to ykcs11. Please try with that version.
The issue you mention has ben adressed in that release, so I'm closing this release due to age.
Please re-open if the problem persists.
