### ISSUE TITLE
error: SCardEstablishContext failed, rc=8010001d

### ISSUE THREAD

**Issue by nullterminated** [Yubico/yubico-piv-tool#125]
yubico-piv-tool seems to be built and working, but I'm unable to connect to cards.

$yubico-piv-tool -a status -v2
error: SCardEstablishContext failed, rc=8010001d
Failed to connect to reader.

Installed on arch linux arm using the following commands,

$git clone https://aur.archlinux.org/yubico-piv-tool.git
$cd yubico-piv-tool/
$makepkg -Acs
$sudo pacman -U yubico-piv-tool-1.4.3-1-aarch64.pkg.tar.xz

**Comment by klali** [comment]
This is probably due to pcscd not running.

**Comment by nullterminated** [comment]
That appears to be part of the problem

[alarm@alarm ~]$ systemctl status pcscd.socket 
* pcscd.socket - PC/SC Smart Card Daemon Activation Socket
   Loaded: loaded (/usr/lib/systemd/system/pcscd.socket; disabled; vendor preset
   Active: inactive (dead)
   Listen: /run/pcscd/pcscd.comm (Stream)
[alarm@alarm ~]$ systemctl status pcscd.service 
* pcscd.service - PC/SC Smart Card Daemon
   Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; vendor prese
   Active: inactive (dead)

If I start pcscd.socket and then pcscd.service though,

[alarm@alarm ~]$ systemctl status pcscd.socket 
* pcscd.socket - PC/SC Smart Card Daemon Activation Socket
   Loaded: loaded (/usr/lib/systemd/system/pcscd.socket; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-10-03 04:02:19 UTC; 1min 29s ago
   Listen: /run/pcscd/pcscd.comm (Stream)

Oct 03 04:02:19 alarm systemd[1]: Listening on PC/SC Smart Card Daemon Activation Socket.
[alarm@alarm ~]$ systemctl status pcscd.service 
* pcscd.service - PC/SC Smart Card Daemon
   Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; vendor preset: disabled)
   Active: active (running) since Tue 2017-10-03 04:02:41 UTC; 1min 13s ago
 Main PID: 1479 (pcscd)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/pcscd.service
           `-1479 /usr/bin/pcscd --foreground --auto-exit

I get a slightly different error,

[alarm@alarm ~]$ yubico-piv-tool -a status -v2
error: SCardListReaders failed, rc=8010002e
Failed to connect to reader.

I did add udev rules to make gpg --card-status work,

https://archlinuxarm.org/forum/viewtopic.php?f=57&t=11931

but after removing the udev rules file, gpg --card-status still works. Would this have anything to do with the issue?

**Comment by klali** [comment]
8010002e is SCARD_E_NO_READERS_AVAILABLE (look in pcsclite.h, we should probably do a better job to translate these), did you replug your yubikey after starting pcscd?

There are issues with gpg locking the yubikey, it might look like this. To rule that out, kill the process scdaemon. Udev rules shouldn't matter, pcscd/libccid comes (should come) with it's own set.

**Comment by nullterminated** [comment]
Yeah, replugged. Even rebooted. scdaemon doesn't appear to be running. I killed gpg-agent and tried it but got the same error. Running gpg --card-status afterward brought gpg-agent back to life.

If the LED on the key is any indication, it's off. No blinking, nothing, just off. If I do gpg --card-status, it lights up for about 5 seconds before turning off again.

**Comment by klali** [comment]
This might be a permission problem with the pcscd socket. You can get debug information from pcscd by starting it manually with -dfa 
That might give indications both if the YubiKey is discovered correctly by pcscd and also if communication between yubico-piv-tool and pcscd works.

**Comment by nullterminated** [comment]
I think you've pinpointed the problem,

sudo pcscd -dfa
00000000 pcscdaemon.c:345:main() pcscd set to foreground with debug send to stdout
00000074 debuglog.c:310:DebugLogSetCategory() Debug options: APDU
00000073 utils.c:82:GetDaemonPid() Can't open /run/pcscd/pcscd.pid: No such file or directory
00000284 configfile.l:361:DBGetReaderList() Parsing conf file: /etc/reader.conf.d
00000035 pcscdaemon.c:658:main() pcsc-lite 1.8.22 daemon ready.
00002043 hotplug_libudev.c:729:HPRegisterForHotplugEvents() No bundle files in pcsc drivers directory: /usr/lib/pcsc/drivers
00000036 hotplug_libudev.c:730:HPRegisterForHotplugEvents() Disabling USB support for pcscd

I also notice that while pcscd.socket is running after a reboot, pcscd.service is dead,

$ systemctl list-units --all | grep pcsc
  pcscd.service                                                                                 loaded    inactive dead      PC/SC Smart Card Daemon                                                                
  pcscd.socket                                                                                  loaded    active   listening PC/SC Smart Card Daemon Activation Socket                                              

I feel like I've taken enough of your time. Thanks for your help.

**Comment by nullterminated** [comment]
I always end up back here when googling how to fix this. The princess is in another castle. The solution is at

https://github.com/Yubico/yubico-piv-tool/issues/146#issuecomment-393022983
