### ISSUE TITLE
Generated keys are considered "weak" by github.com

### ISSUE THREAD

**Issue by doherty** [Yubico/yubico-piv-tool#127]
I generated an RSA 2048 key following the instructions at [Using PIV for SSH through PKCS11](https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html), e.g.

```
yubico-piv-tool -s 9a -a generate -k$key --pin-policy=once --touch-policy=always --algorithm=RSA2048 -o public.pem
yubico-piv-tool -a verify-pin -a selfsign-certificate -s 9a -S "/CN=mike@mikedoherty.ca/" -i public.pem -o cert.pem
yubico-piv-tool -a import-certificate -s 9a -i cert.pem  -k$key
ssh-keygen -D /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -e
```

When adding this key to github, it is rejected:

> Key is weak. GitHub recommends using ssh-keygen to generate a RSA key of at least 2048 bits.

The same is true if using the GUI wrapper [YubiKey PIV Manager](https://developers.yubico.com/PIV/Tools/YubiKey_PIV_Manager.html).

However, generating and importing my own, the key is accepted:

```
ssh-keygen -t rsa -b 2048 -C "mike@mikedoherty.ca"
yubico-piv-tool -s 9a -a import-key -k$key --pin-policy=once --touch-policy=always -i id_rsa_2.pem
openssl rsa -in id_rsa_2 -out id_rsa_2.pem -outform pem
yubico-piv-tool -s 9a -a import-key -k$key --pin-policy=once --touch-policy=always -i id_rsa_2.pem
yubico-piv-tool -a verify-pin -a selfsign-certificate -s 9a -S '/CN=mike@mikedoherty.ca/' -i id_rsa_2.pub.pkcs8 -o cert.pem
yubico-piv-tool -a import-certificate -s 9a -i cert.pem -k$key
ssh-keygen -D /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -e
```

**Comment by doherty** [comment]
Is github detecting keys affected by [ysa-2017-01](https://www.yubico.com/support/security-advisories/ysa-2017-01/)? (as a side note, how does one subscribe to yubico's security advisory notifications, like `debian-security-announce@lists.debian.org`?)

**Comment by klali** [comment]
Yes, blocking generation of weak keys is happening, see cd1119653558c782eeffb0db7616ebb8d49af437 thanks for reminding us about pkcs11 though.

For notifications there is https://www.yubico.com/support/security-advisories/ but we plan to do better shortly.

**Comment by klali** [comment]
version 1.4.4 blocking key generation for these keys has been released.
