### ISSUE TITLE
No implementation for C_Encrypt or the associated functions.

### ISSUE THREAD

**Issue by bwitt2** [Yubico/yubico-piv-tool#129]
I noticed that C_Encrypt is not yet implemented:

```
CK_DEFINE_FUNCTION(CK_RV, C_Encrypt)(
  CK_SESSION_HANDLE hSession,
  CK_BYTE_PTR pData,
  CK_ULONG ulDataLen,
  CK_BYTE_PTR pEncryptedData,
  CK_ULONG_PTR pulEncryptedDataLen
)
{
  DIN;
  DBG("TODO!!!");
  DOUT;
  return CKR_FUNCTION_FAILED;
}
```
Is there a specification specific to the Yubikey 4 that I can use to implement this function?

**Comment by a-dma** [comment]
You probably want to implement decryption, since that's the operation that uses the private key on the YubiKey.

For details you want to check the PIV specifications from NIST.
