### ISSUE TITLE
Vagrant box failing on missing dependencies

### ISSUE THREAD

**Issue by jonnisell** [Yubico/yubico-piv-tool#142]
When building the Vagrantfile provided with yubico-piv-tool, it fails on missing dependencies whern running make.

![image](https://user-images.githubusercontent.com/26717852/37508859-32243a4e-28f5-11e8-87bf-ffe67d28f4eb.png)

**Comment by Jakuje** [comment]
Just update the https://github.com/Yubico/yubico-piv-tool/blob/master/vagrant/development/provision.sh file and add the missing `check` dependency. Though, this should be fixed here.
