### ISSUE TITLE
import-key does not import ED25519 in SSH format

### ISSUE THREAD

**Issue by volth** [Yubico/yubico-piv-tool#143]
generate key
```ssh-keygen -t ed25519 -f key```

 try to import
```yubico-piv-tool -s 9a -a import-key  -i key```

 try to import
```yubico-piv-tool -s 9a -a import-key -K SSH -i key```

yubico-piv-tool answers with
```
Failed loading private key for import. 
Unable to import private key
```

No problem if key is RSA
No problem with ED25519 generated by ```openssl ecparam -genkey ...``` (they start with "-----BEGIN EC PRIVATE KEY-----" while the keys made by ```ssh-keygen ...``` start with "-----BEGIN OPENSSH PRIVATE KEY-----" and the files are bigger: ~400 bytes against ~230 bytes for openssl's)

**Comment by Jakuje** [comment]
Are you sure you are able to load ED25519 key to your Yubikey? Isn't it the ECDSA one?

The Ed25519 keys do not have any standard representation in PEM format nor in PKCS#11 and to my understanding neither in yubikeys so I don't think there is a way to make this working.

For more information about the new OpenSSH format used for ed25519 keys, see

https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/PROTOCOL.key?annotate=HEAD
