### ISSUE TITLE
yubico-piv-tool fails to connect to reader on Arch

### ISSUE THREAD

**Issue by scolby33** [Yubico/yubico-piv-tool#146]
```
$ yubico-piv-tool -a status -v2
trying to connect to reader 'Yubico Yubikey 4 OTP+U2F+CCID 00 00'.
SCardConnect failed, rc=80100009
error: no usable reader found.
Failed to connect to reader.
```

According to the codes in pcsclite.h, `80100009` is `SCARD_E_UNKNOWN_READER`.

Following the advice from #125, I ran

```
$ sudo pcscd -dfa
...
hotplug_llibudev.c:651:HPEstablishUSBNotifications() USB Device add
hotplog_libudev.c:297get_driver() Looking for a driver for VID: 0x1050, PID: 0x0407, path: /dev/bus/usb/005/004
hotplug_libudev.c:436:HPAddDevice() Adding USB device: Yubico Yubikey 4 OTP+U2F+CCID
readerfactory.c:1075:RFInitializeReader() Attempting startup of Yubico Yubikey 4 OTP+U2F+CCID 00 00 using /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
dyn_unix.c:58:DYN_LoadLibrary() /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so: /usr/lib/libfl.so.2: undefined symbol: yylex
readerfactory.c:1082:RFInitializeReader() RFLoadReader failed: 0x80100014  # (this is  "SCARD_F_UNKNOWN_ERROR" -ed.)
readerfactory.c:376:RFAddReader() Yubico Yubikey 4 OTP+U2F+CCID init failed.
hotplug_libudev.c:523:HPAddDevice() Failed adding USB device: Yubico Yubikey 4 OTP+U2F+CCID
...
```
That failure sequence repeats twice more until `pcscd` gives up.

This `yylex` error seems to come from a library called `flex`. I have version 2.6.4-1 of that installed on my system, but other instances the error on Google come from a few years ago and version 2.5.something.

Any thoughts on this?

**Comment by klali** [comment]
The failure here is when pcscd tries to load libccid, it's apparently linked with libfl and when linking that symbol was probably there. Might you have done partial re-builds where that symbol has been lost in between?

**Comment by scolby33** [comment]
I don't think I did any sort of partial build, but I had been futzing with installed packages a good bit before attempting this. I tried a clean re-install of the relevant packages with no success. I've submitted a support request to the CCID mailing list (https://ccid.apdu.fr/#support) and will update here with whatever information I receive from there.

**Comment by nullterminated** [comment]
Aaand it works! :) 147 was right, I needed to install yubikey-manager, and then rebuild the yubico-piv-tool.

**Comment by scolby33** [comment]
I'll give the suggestions in #147 a try! The maintainer went and installed Arch and tried a build himself and it worked with no problems; the wrinkle in my case is I'm using [Arch Linux 32](https://archlinux32.org/) which might have some weirdness going on.

**Comment by scolby33** [comment]
Unfortunately, no luck here. `yubikey-manager` was already installed, and a reinstall and rebuild didn't help.

**Comment by nullterminated** [comment]
I have done a clean install of arch linux arm, and tried this again. The missing dependency is ccid. Also, sudo systemctl start pcscd.socket, sudo systemctl enable pcscd.socket is needed. It doesn't seem to be activated by installing pcsclite. Is @travisghansen the same travisghansen who maintains https://aur.archlinux.org/packages/yubico-piv-tool/?

**Comment by scolby33** [comment]
With `ccid` installed and `pcscd.socket` enabled and running, I still experience an issue with `yylex` on Archlinux 32.

See this thread on the yylex mailing list http://lists.infradead.org/pipermail/pcsclite-muscle/2018-May/001083.html

**Comment by michaellass** [comment]
@scolby33 : I also had this issue on archlinux32. You can fix it by modifying the ccid PKGBUILD and adding `LEXLIB=` to the ./configure parameters (similar to https://bugzilla.redhat.com/show_bug.cgi?id=1386390#c1).

I don't have the issue on 64bit Arch Linux and right now don't know where the issue originates.

**Comment by scolby33** [comment]
That did it for me! It looks like the official PKGBUILD has been updated with this workaround as well as of 1.4.30-2. [The change](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/ccid&id=73a4eb71be04c7e73c46e8c55a840b169235ab94), [the PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/ccid)
