### ISSUE TITLE
yubico-piv-tool failed to connect error: SCardListReaders failed, rc=8010002e Arch

### ISSUE THREAD

**Issue by reefland** [Yubico/yubico-piv-tool#147]
yubico-piv-tool Build:

  Version:          1.5.0
  Host type:        x86_64-pc-linux-gnu
  Install prefix:   /usr/local
  Compiler:         gcc
  CFLAGS:           -g -O2
  CPPFLAGS:         
  Warnings:         
  Backend:          pcsc
  OpenSSL version:  1.1.0h
  PCSC
          CFLAGS:   -pthread -I/usr/include/PCSC
            LIBS:   -lpcsclite
  Winscard
            LIBS:   
  Mac PCSC
            LIBS:   

  YKCS11 debug:    DISABLED
  Hardware tests:  DISABLED

Clean reboot, without YubiKey NEO inserted

Arch: x86_64 Linux 4.16.5-1-ARCH

systemctl status pcscd.socket
● pcscd.socket - PC/SC Smart Card Daemon Activation Socket
   Loaded: loaded (/usr/lib/systemd/system/pcscd.socket; disabled; vendor preset: disabled)
   Active: inactive (dead)
   Listen: /run/pcscd/pcscd.comm (Stream)

systemctl status pcscd.service
● pcscd.service - PC/SC Smart Card Daemon
   Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; vendor preset: disabled)
   Active: inactive (dead)

sudo systemctl start pcscd.socket
sudo systemctl start pcscd.service

systemctl status pcscd.socket
Failed to dump process list, ignoring: No such file or directory
● pcscd.socket - PC/SC Smart Card Daemon Activation Socket
   Loaded: loaded (/usr/lib/systemd/system/pcscd.socket; disabled; vendor preset: disabled)
   Active: active (listening) since Wed 2018-05-02 10:45:00 EDT; 1min 23s ago
   Listen: /run/pcscd/pcscd.comm (Stream)
   CGroup: /system.slice/pcscd.socket

May 02 10:45:00 dldsk01 systemd[1]: Listening on PC/SC Smart Card Daemon Activation Socket.

systemctl status pcscd.service
● pcscd.service - PC/SC Smart Card Daemon
   Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; vendor preset: disabled)
   Active: inactive (dead)

sudo pcscd -dfa
00000000 pcscdaemon.c:347:main() pcscd set to foreground with debug send to stdout
00000019 debuglog.c:310:DebugLogSetCategory() Debug options: APDU
00000072 utils.c:82:GetDaemonPid() Can't open /run/pcscd/pcscd.pid: No such file or directory
00000094 configfile.l:361:DBGetReaderList() Parsing conf file: /etc/reader.conf.d
00000014 pcscdaemon.c:662:main() pcsc-lite 1.8.23 daemon ready.
00000608 hotplug_libudev.c:729:HPRegisterForHotplugEvents() No bundle files in pcsc drivers directory: /usr/lib/pcsc/drivers
00000018 hotplug_libudev.c:730:HPRegisterForHotplugEvents() Disabling USB support for pcscd

** Insert YubiKey NEO here - no change in pcscd screen

dmesg output:
[  572.107714] usb 2-1.6: new full-speed USB device number 3 using ehci-pci
[  572.206754] usb 2-1.6: New USB device found, idVendor=1050, idProduct=0116
[  572.206758] usb 2-1.6: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  572.206760] usb 2-1.6: Product: Yubikey NEO OTP+U2F+CCID
[  572.206762] usb 2-1.6: Manufacturer: Yubico
[  572.208136] input: Yubico Yubikey NEO OTP+U2F+CCID as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/0003:1050:0116.0006/input/input16
[  572.264614] hid-generic 0003:1050:0116.0006: input,hidraw5: USB HID v1.10 Keyboard [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:1d.0-1.6/input0
[  572.265511] hid-generic 0003:1050:0116.0007: hiddev3,hidraw6: USB HID v1.10 Device [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:1d.0-1.6/input1

systemctl status pcscd.service
● pcscd.service - PC/SC Smart Card Daemon
   Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; vendor preset: disabled)
   Active: inactive (dead)

(Still dead?  restart again)

sudo systemctl start pcscd.service

systemctl status pcscd.service
● pcscd.service - PC/SC Smart Card Daemon
   Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; vendor preset: disabled)
   Active: active (running) since Wed 2018-05-02 10:50:43 EDT; 2s ago
 Main PID: 2770 (pcscd)
    Tasks: 2 (limit: 4915)
   Memory: 452.0K
   CGroup: /system.slice/pcscd.service
           └─2770 /usr/bin/pcscd --foreground --auto-exit

yubico-piv-tool -V
yubico-piv-tool 1.5.0

yubico-piv-tool -a status -v2
error: SCardListReaders failed, rc=8010002e
Failed to connect to reader.

The output from pcscd upon running the above:
99999999 winscard_msg_srv.c:255:ProcessEventsServer() Common channel packet arrival
00000038 winscard_msg_srv.c:267:ProcessEventsServer() ProcessCommonChannelRequest detects: 7
00000014 pcscdaemon.c:133:SVCServiceRunLoop() A new context thread creation is requested: 7
00000188 winscard_svc.c:340:ContextThread() Authorized PC/SC client
00000019 winscard_svc.c:344:ContextThread() Thread is started: dwClientID=7, threadContext @0x55efeead25f0
00000023 winscard_svc.c:362:ContextThread() Received command: CMD_VERSION from client 7
00000017 winscard_svc.c:374:ContextThread() Client is protocol version 4:3
00000010 winscard_svc.c:394:ContextThread() CMD_VERSION rv=0x0 for client 7
00000133 winscard_svc.c:362:ContextThread() Received command: ESTABLISH_CONTEXT from client 7
00000027 winscard.c:215:SCardEstablishContext() Establishing Context: 0x2272FAF4
00000014 winscard_svc.c:458:ContextThread() ESTABLISH_CONTEXT rv=0x0 for client 7
00000095 winscard_svc.c:362:ContextThread() Received command: CMD_GET_READERS_STATE from client 7
00000150 winscard_svc.c:362:ContextThread() Received command: RELEASE_CONTEXT from client 7
00000028 winscard.c:229:SCardReleaseContext() Releasing Context: 0x2272FAF4
00000014 winscard_svc.c:473:ContextThread() RELEASE_CONTEXT rv=0x0 for client 7
00000120 winscard_svc.c:354:ContextThread() Client die: 7
00000078 winscard_svc.c:1029:MSGCleanupClient() Thread is stopping: dwClientID=7, threadContext @0x55efeead25f0
00000015 winscard_svc.c:1035:MSGCleanupClient() Freeing SCONTEXT @0x55efeead25f0

**Comment by reefland** [comment]
I wasn't aware I needed the required Arch package "yubikey-manager".   Worked fine once installed.

**Comment by shibumi** [comment]
Thank you! Stumbled over the same issue. Installing `yubikey-manager` fixed `gpg --card-status` for me. I have the feeling it has to do with the `ccid` dependency.
