### ISSUE TITLE
Segfault Error 6 in libc-2.27.so on Import Certificate

### ISSUE THREAD

**Issue by reefland** [Yubico/yubico-piv-tool#148]
$ yubico-piv-tool -s 9a -a generate -o public.pem
Successfully generated a new private key.

$ yubico-piv-tool -a verify-pin -P xxxxxxx -a selfsign-certificate -s 9a -S "/CN=SSH key/" -i public.pem -o cert.pem
Successfully verified PIN.
Successfully generated a new self signed certificate.

$ ls -l *.pem
-rw-r--r--  1 rich users        451 May  4 12:13 public.pem
-rw-r--r--  1 rich users      30308 May  4 12:22 cert.pem

$ yubico-piv-tool -a import-certificate -s 9a -i cert.pem
Segmentation fault (core dumped)

$ yubico-piv-tool -a import-certificate -s 9a -i cert.pem
Segmentation fault (core dumped)

DMESG Output:
```
[ 3332.951936] usb 2-1.6: new full-speed USB device number 3 using ehci-pci
[ 3333.051298] usb 2-1.6: New USB device found, idVendor=1050, idProduct=0116
[ 3333.051302] usb 2-1.6: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 3333.051304] usb 2-1.6: Product: Yubikey NEO OTP+U2F+CCID
[ 3333.051306] usb 2-1.6: Manufacturer: Yubico
[ 3333.052516] input: Yubico Yubikey NEO OTP+U2F+CCID as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6/2-1.6:1.0/0003:1050:0116.0006/input/input16
[ 3333.109026] hid-generic 0003:1050:0116.0006: input,hidraw5: USB HID v1.10 Keyboard [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:1d.0-1.6/input0
[ 3333.109852] hid-generic 0003:1050:0116.0007: hiddev3,hidraw6: USB HID v1.10 Device [Yubico Yubikey NEO OTP+U2F+CCID] on usb-0000:00:1d.0-1.6/input1
[ 4398.976390] yubico-piv-tool[4639]: segfault at 7fffe0178000 ip 00007f5e61cd42c4 sp 00007fffe0174618 error 6 in libc-2.27.so[7f5e61c34000+1b1000]
[ 4460.895444] yubico-piv-tool[4675]: segfault at 7ffcfeb3f000 ip 00007f32e54192c4 sp 00007ffcfeb3b698 error 6 in libc-2.27.so[7f32e5379000+1b1000]

```
**Package Versions:**

$ opensc-tool -i
OpenSC 0.17.0 [gcc  7.3.1 20180312]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)

$ uname -r
4.16.6-1-ARCH

$ yubico-piv-tool -V
yubico-piv-tool 1.5.0

$ ykinfo -V
1.19.0

$ pcsc_scan -V
```
PC/SC device scanner
V 1.5.2 (c) 2001-2017, Ludovic Rousseau <ludovic.rousseau@free.fr>
```

**Maybe useful stuff:**

$ yubico-piv-tool -v -a status
trying to connect to reader 'Yubico Yubikey NEO OTP+U2F+CCID 00 00'.
Action 'status' does not need authentication.
Now processing for action 'status'.
CHUID:	No data available
CCC:	No data available
PIN tries left:	3

$ opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Yubico Yubikey NEO OTP+U2F+CCID 00 00

$ pcsc_scan 
```
PC/SC device scanner
V 1.5.2 (c) 2001-2017, Ludovic Rousseau <ludovic.rousseau@free.fr>
Using reader plug'n play mechanism
Scanning present readers...
0: Yubico Yubikey NEO OTP+U2F+CCID 00 00
 
Fri May  4 12:37:09 2018
 Reader 0: Yubico Yubikey NEO OTP+U2F+CCID 00 00
  Card state: Card inserted, 
  ATR: 3B FC 13 00 00 81 31 FE 15 59 75 62 69 6B 65 79 4E 45 4F 72 33 E1

ATR: 3B FC 13 00 00 81 31 FE 15 59 75 62 69 6B 65 79 4E 45 4F 72 33 E1
+ TS = 3B --> Direct Convention
+ T0 = FC, Y(1): 1111, K: 12 (historical bytes)
  TA(1) = 13 --> Fi=372, Di=4, 93 cycles/ETU
    43010 bits/s at 4 MHz, fMax for Fi = 5 MHz => 53763 bits/s
  TB(1) = 00 --> VPP is not electrically connected
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 81 --> Y(i+1) = 1000, Protocol T = 1 
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1 
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 15 --> Block Waiting Integer: 1 - Character Waiting Integer: 5
+ Historical bytes: 59 75 62 69 6B 65 79 4E 45 4F 72 33
  Category indicator byte: 59 (proprietary format)
+ TCK = E1 (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B FC 13 00 00 81 31 FE 15 59 75 62 69 6B 65 79 4E 45 4F 72 33 E1
	YubiKey NEO (PKI)
	http://www.yubico.com/
```

**Comment by reefland** [comment]
Not sure if any of this helps:

```
$ yubico-piv-tool -a import-certificate -s 9a -i cert.pem -v2
trying to connect to reader 'Yubico Yubikey NEO OTP+U2F+CCID 00 00'.
> 00 a4 04 00 05 a0 00 00 03 08 
< 61 11 4f 06 00 00 10 00 01 00 79 07 4f 05 a0 00 00 03 08 90 00 
Authenticating since action 'import-certificate' needs that.
> 00 87 03 9b 04 7c 02 80 00 
< 7c 0a 80 08 9c c0 59 15 da db 69 cf 90 00 
> 00 87 03 9b 16 7c 14 80 08 a8 5d 77 21 da 90 ed f6 81 08 7c 9e 1b a1 c5 1e 81 14 
< 7c 0a 82 08 31 ec c9 22 c6 3a e4 da 90 00 
Successful application authentication.
Now processing for action 'import-certificate'.
Segmentation fault (core dumped)

```

**Comment by reefland** [comment]
hmm...  I self-signed again using the new version from git and it seemed to work...

```
$ yubico-piv-tool -a verify-pin -P xxxxxx -a selfsign-certificate -s 9a -S "/CN=SSH key/" -i public.pem -o cert.pem
Successfully verified PIN.
Successfully generated a new self signed certificate.

$ yubico-piv-tool -a import-certificate -s 9a -i cert.pem
Successfully imported a new certificate.

```

**Comment by klali** [comment]
the selfsign command received a fix in https://github.com/Yubico/yubico-piv-tool/pull/136 this shouldn't cause crashes in import though (and yes, we need to release this).

**Comment by klali** [comment]
I'm failing to produce one of the broken certs, could you possibly attach one of the broken certs that crash yubico-piv-tool or send it to me at klas@yubico.com ?

**Comment by ekromhout** [comment]
I have a broken cert if one is still needed.

**Comment by klali** [comment]
Please. Either email or attach here.

**Comment by ekromhout** [comment]
[bad-cert-nano.pem.gz](https://github.com/Yubico/yubico-piv-tool/files/2155232/bad-cert-nano.pem.gz)

This should be the broken cert produced by the yubico-piv-tool 1.5.0 in a Fedora 28 package install. Building from current git produced a working certificate and config.

**Comment by klali** [comment]
Thank you, the crash here was due to a missing length check.

Thank's for persisting!
