### ISSUE TITLE
Hangs on macOS

### ISSUE THREAD

**Issue by natevw** [Yubico/yubico-piv-tool#151]
When my Yubikey is configured under macOS High Sierra 10.13.5 (using tokend if that makes a difference), this command line tool frequently hangs:

```
$ ./yubico-piv-tool -v11 -a status
trying to connect to reader 'Yubico Yubikey 4 U2F+CCID'.
```

…that is the only output for dozens of minutes.

Oddly, if I lock my screen and then enter my PIN in the system unlock dialog, the hung-for-eons command has ended up finally succeeding by the time I can see it. But running the command again soon after, it fails. (Experimenting with `while sleep 1; do ./yubico-piv-tool -a status; date; done` behind the lock screen seems to reveal that the command starts working every second after a bad PIN entry at the lock screen, and stops working within a few seconds after a successful PIN entry.)

If I unplug the device, the hung command detects with `SCardConnect failed, rc=ffffffff8010000c`. Upon plugging in again (usually takes two tries before the device is read…) the command works repeatedly *until* I enter the **correct** PIN in a system dialog. At that point this piv-tool hangs again.

**Comment by richarddb** [comment]
I have a similar issue that might be related. On macOS 10.13.6, YubiKey NEO, I was "randomly" getting reader errors against the YubiKey when working with the `yubico-piv-tool`. For example:

```
$  yubikey_neo git:(master) ✗ yubico-piv-tool --verbose=2 -aversion
trying to connect to reader 'Yubico Yubikey NEO OTP+U2F+CCID'.
SCardConnect failed, rc=ffffffff8010000b
error: no usable reader found.
Failed to connect to reader.
```

Installing the yubikey manager made no difference at all to my problem, as has been suggested elsewhere for Arch Linux.

I suspect this is my problem: A little before running this command, I'm running a GPG command to retrieve the device serial number (for automation purposes)... Such as `gpg --card-status | grep 'Serial number'`. And I think the OpenPGP mode "confuses" the PIV mode.

I've found a fairly reliable workaround for me is to use `ykman piv info`. That seems to have relieved my issues so far.

Maybe that helps you and the developers.

**Comment by richarddb** [comment]
https://xkcd.com/979/ applies 😄

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 is out and contains major upgrade to ykcs11. Please try that version, I do not have any hanging issues on my dev machine which runs Catalina. Regarding error opening the card reader they can occur if someone else is hogging the USB device (through pcsc-lite or otherwise).

I'm closing this issue, please re-open if the problem persists.
