### ISSUE TITLE
yubico-piv-tool output is sent to StdError even on success in some cases

### ISSUE THREAD

**Issue by achiniqu** [Yubico/yubico-piv-tool#152]
As an example, when running yubico-pv-tool -a change-pin -P <OLD PIN> -N <NEW PIN>, when the PIN is successfully changed, yubico-piv-tools exits with an exit code of 0 as expected but the messaged "Successfully changed the pin code." is output to StdError and not StdOut. This is annoying when running in scripts and matching on output text.  Please note that this appears to be occurring in the 1.5.0 win64 build. I have not tested others.

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 is out and contains a major update to ykcs11. Please try with that version.
I'm closing this issue due to age.
Please re-open if the problem persists.
