### ISSUE TITLE
PKCS11 - Unable to import private key

### ISSUE THREAD

**Issue by pramodrj07** [Yubico/yubico-piv-tool#155]
Input -
 pkcs11-tool --module /usr/local//lib/softhsm/libsofthsm2.so -l --pin 123456789 --write-object ./privatekey.der --type privkey --id 2222 --label ABC
 
Output -

Using slot 0 with a present token (0x357ce9ef)
error: PKCS11 function C_CreateObject failed: rv = CKR_TEMPLATE_INCOMPLETE (0xd0)

Any pointers  on how to resolve it:?

**Comment by a-dma** [comment]
Are you sure you meant to use SoftHSM there? If so this is the wrong to ask since you're using something from DNSSec and OpenSC :)

Anyway, generally speaking that error means that the module requires more parameters than the one that have been set by pkcs11-tool.

**Comment by pramodrj07** [comment]
Oh i did not know about it! Thanks @a-dma
