### ISSUE TITLE
Issue during keypair generation using PKCS#11 module (libykcs11-1.dll)

### ISSUE THREAD

**Issue by lexxxandreev** [Yubico/yubico-piv-tool#156]
I've been trying to generate keypair using PKCS#11 (libykcs11-1.dll), but every time I'm getting the error CKR_FUNCTION_FAILED. The generation using yubico-piv-tool is always successful though. I check its source code, but it looks like yubico-piv-tool  doesn't call C_GenerateKeyPair for keypair generation.
Note, I'm trying to login as CKU_SO with the default 010203040506070801020304050607080102030405060708 key.
I use the YubiKey NEO token. Any ideas what is wrong?

 CK_MECHANISM mechanism = {
            CKM_RSA_PKCS_KEY_PAIR_GEN, NULL_PTR, 0
        };
        CK_ULONG modulusBits = AppConfig::getModulusBits();
        CK_BYTE publicExponent[] = { 1, 0, 1 };
		CK_BYTE id[] = { 2 };
        //generateRandomId(id, 8);
        CK_BBOOL _true = TRUE;
        CK_ATTRIBUTE publicKeyTemplate[] = {
            { CKA_ID, id, sizeof(id) },
            { CKA_TOKEN, &_true, sizeof(true) },
            { CKA_ENCRYPT, &_true, sizeof(true) },
            { CKA_VERIFY, &_true, sizeof(true) },
            { CKA_MODULUS_BITS, &modulusBits, sizeof(modulusBits) },
            { CKA_PUBLIC_EXPONENT, publicExponent, 3 }
        };
        CK_ATTRIBUTE privateKeyTemplate[] = {
            { CKA_ID, id, sizeof(id) },
            { CKA_TOKEN, &_true, sizeof(true) },
            { CKA_PRIVATE, &_true, sizeof(true) },
            { CKA_SENSITIVE, &_true, sizeof(true) },
            { CKA_DECRYPT, &_true, sizeof(true) },
            { CKA_SIGN, &_true, sizeof(true) },
        };

        CK_RV status = _functionList->C_GenerateKeyPair(_session,
            &mechanism,
            publicKeyTemplate, sizeof(publicKeyTemplate) / sizeof(CK_ATTRIBUTE),
            privateKeyTemplate, sizeof(privateKeyTemplate) / sizeof(CK_ATTRIBUTE),
            &publicKey,
            &privateKey);
        if (status != CKR_OK)
        {
            LOG_ERROR("C_GenerateKeyPair failed 0x%08?x", status);
            throw Pkcs11Exception(status);
        }

**Comment by a-dma** [comment]
yubico-piv-tool doesn't use ykcs11, they both call into libykpiv.

Maybe storing the certificate to hold the public key is failing? Are you using OpenSSL 1.1? What version of ykcs11?

Does
`pkcs11-tool --module PATH/TO/ykcs11.so --key-type RSA:1024 --usage-sign --usage-decrypt --id 1 --keypairgen --login --login-type so --so-pin 010203040506070801020304050607080102030405060708` work for you?

I suggest you try building ykcs11 in debug mode and see where that trips up.

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 contains a major new release of ykcs11, please try that version.

I'm closing this issue now due to it's age, please re-open if the problem persists with the new version.
