### ISSUE TITLE
Generating certificate

### ISSUE THREAD

**Issue by MrRobbi** [Yubico/yubico-piv-tool#159]
yubico-piv-tool -s9d -A ECCP384 -agenerate --touch-policy=cached -k -o yubikey.pem

yubico-piv-tool -s9d -S/CN=Test -averify -arequest -i yubikey.pem -o yubikey.csr

Enter PIN:
Successfully verified PIN.
**error: Failed to begin pcsc transaction, rc=80100003**
Successfully generated a certificate request

I had the same problem on version 1.5.0, but with RSA2048. Now in v. 1.6.0 RSA works, but ECCP384 ( or 256 ) doesnt - same error.

**Comment by hessophanes** [comment]
This is related to #136: the fix there was incomplete, as it did not handle the "on stack structure" problem for the ECC case. The function wrap_public_key() should probably be fixed to look like this (see attached patch).
[yubico-piv-tool.patch.txt](https://github.com/Yubico/yubico-piv-tool/files/2366413/yubico-piv-tool.patch.txt)

**Comment by hessophanes** [comment]
Note: this is already fixed in master - you're probably using a downstream software package like myself.

**Comment by klali** [comment]
As noted this should be fixed by the fixes for #164
