### ISSUE TITLE
Side-effects of enforcing parity on 3DES keys

### ISSUE THREAD

**Issue by devonobrien** [Yubico/yubico-piv-tool#16]
I'm writing an issue here, which is an excerpt from a conversation I had on the forums concerning a separate but related issue.

In addition to several fixes with respect to yubico-piv-tool's handling of PIV management keys (hex_decode failing, etc.) yubico-piv-tool version 0.1.4 enforces DES parity for entry as a parameter.

I do want to point out that enforcing DES parity bits actually makes things significantly more complicated for users and doesn't inherently add any security value. It breaks compatibility with all current tools wrapping yubico-piv-tool in addition to contrasting existing documentation for provisioning NEO tokens and NEO CAs. The additional level of effort to provide this as input using scripts can be seen here: http://forum.yubico.com/viewtopic.php?f=26&t=1729

The state of cryptographic tools is hindered, not helped, by DES implementations that require parity bits to be properly set. They tend to exist in legacy implementations with new versions of software treating keys with and without proper parity identically since they are identical, cryptographically speaking.

Is there a reason this change is inextricably tied to the hex_decode (or some other) change in this version? Based on my understanding, these are independent. Based on the day 1 threads on the forum struggling with the change and my own efforts to repair tooling around the new version, I would like to request for a revert on this feature.

**Comment by devonobrien** [comment]
Looks like 0.1.5 took care of this. Thanks!

**Comment by klali** [comment]
As you say enforcing parity wasn't a very well considered change, so we reverted that change in fa1d3ca9f984bc12b42e59bc91f63ed77912948c

Thank you for taking the time to report an issue here!

/klas
