### ISSUE TITLE
Yubikey Malloc Error

### ISSUE THREAD

**Issue by maevyn11** [Yubico/yubico-piv-tool#160]
Hey guys, after using the yubico-piv-tool to configure a yubikey 4, I have been running into an issue trying to use it for code signing with notary. Sometimes the key works fine but around 50% of the time I see what looks like low level memory errors. I have seen similar issues with the Yubikey 4 and the Yubikey4C. Full output of the issue with the Yubikey 4 is below. The linked notary issue describes the output that occurs with the Yubikey4C.

Would appreciate any guidance on what might be causing this or what I could do to workaround. Would like to use the yubikey to store our root keys for notary, but these issues do not inspire confidence that the key will be usable should we need it years down the line. 

https://github.com/theupdateframework/notary/issues/1372

DEBU[0000] Using the following trust directory: /Users/dveenstra/.notary/trust_test1001
DEBU[0001] Initialized PKCS11 library /usr/local/lib/libykcs11.dylib and started HSM session
DEBU[0001] Found 1 objects matching list filters
DEBU[0001] Making dir path: /Users/dveenstra/.notary/trust_test1001/tuf/test1001/changelist
Root key found, using: a12c4afac8e4950be29ce96581221f76d9f1ec8029318db316205ef6b844cd00
DEBU[0001] Initialized PKCS11 library /usr/local/lib/libykcs11.dylib and started HSM session
DEBU[0001] Initialized PKCS11 library /usr/local/lib/libykcs11.dylib and started HSM session
Enter the User Pin for the attached Yubikey:
Please touch the attached Yubikey to perform signing.
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff788d56da]

runtime stack:
runtime.throw(0x45610f8, 0x2a)
	/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall]:
runtime.cgocall(0x4438660, 0xc420176870, 0x29)
	/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420176830 sp=0xc4201767f8 pc=0x4003dd4
github.com/theupdateframework/notary/vendor/github.com/miekg/pkcs11._Cfunc_CloseSession(0x4e84cd0, 0x51b660, 0x0)
	_cgo_gotypes.go:446 +0x4e fp=0xc420176870 sp=0xc420176830 pc=0x43b429e
github.com/theupdateframework/notary/vendor/github.com/miekg/pkcs11.(*Ctx).CloseSession.func1(0x4e84cd0, 0x51b660, 0xc42029e748)
	/go/src/github.com/theupdateframework/notary/vendor/github.com/miekg/pkcs11/pkcs11.go:1017 +0x60 fp=0xc4201768a8 sp=0xc420176870 pc=0x43c1dd0
github.com/theupdateframework/notary/vendor/github.com/miekg/pkcs11.(*Ctx).CloseSession(0xc42038e0b8, 0x51b660, 0xc420176940, 0x18)
	/go/src/github.com/theupdateframework/notary/vendor/github.com/miekg/pkcs11/pkcs11.go:1017 +0x41 fp=0xc4201768e8 sp=0xc4201768a8 pc=0x43baa61
github.com/theupdateframework/notary/trustmanager/yubikey.cleanup(0x45bd620, 0xc42038e0b8, 0x51b660)
	/go/src/github.com/theupdateframework/notary/trustmanager/yubikey/yubikeystore.go:809 +0x3f fp=0xc420176940 sp=0xc4201768e8 pc=0x43ce44f
github.com/theupdateframework/notary/trustmanager/yubikey.(*YubiPrivateKey).Sign(0xc420368200, 0x45b4280, 0xc4200a4de0, 0xc42049cd00, 0x20, 0x20, 0x45b50a0, 0xc4204a2d10, 0xc42052ad40, 0x40, ...)
	/go/src/github.com/theupdateframework/notary/trustmanager/yubikey/yubikeystore.go:208 +0x2c8 fp=0xc420176a20 sp=0xc420176940 pc=0x43c7d88
crypto/x509.CreateCertificate(0x45b4280, 0xc4200a4de0, 0xc42046a680, 0xc42046a680, 0x44eeb00, 0xc4204a1480, 0x4505860, 0xc420368200, 0xc42046a680, 0x0, ...)
	/usr/local/go/src/crypto/x509/x509.go:2133 +0x8f7 fp=0xc420177478 sp=0xc420176a20 pc=0x429c627
github.com/theupdateframework/notary/cryptoservice.generateCertificate(0x45b6cc0, 0xc420368200, 0x7ffeefbff966, 0x8, 0xbed4eb0e22171282, 0x5932b5c5, 0x4839560, 0xc387ebce22171282, 0x46062402190b5c5, 0x4839560, ...)
	/go/src/github.com/theupdateframework/notary/cryptoservice/certificate.go:30 +0x245 fp=0xc420177598 sp=0xc420177478 pc=0x4399f95
github.com/theupdateframework/notary/cryptoservice.GenerateCertificate(0x45bb840, 0xc420368180, 0x7ffeefbff966, 0x8, 0xbed4eb0e22171282, 0x5932b5c5, 0x4839560, 0xc387ebce22171282, 0x46062402190b5c5, 0x4839560, ...)
	/go/src/github.com/theupdateframework/notary/cryptoservice/certificate.go:21 +0xd2 fp=0xc420177630 sp=0xc420177598 pc=0x4399c32
github.com/theupdateframework/notary/client.rootCertKey(0x7ffeefbff966, 0x8, 0x45bb840, 0xc420368180, 0xc4204a0da0, 0xc4204aa8b0, 0x1, 0x1)
	/go/src/github.com/theupdateframework/notary/client/client.go:169 +0xd9 fp=0xc420177700 sp=0xc420177630 pc=0x43d0819
github.com/theupdateframework/notary/client.(*repository).createNewPublicKeyFromKeyIDs(0xc4201084d0, 0xc4204aa890, 0x1, 0x1, 0x0, 0x3f, 0xc420177818, 0x4034a1b, 0x30)
	/go/src/github.com/theupdateframework/notary/client/client.go:276 +0x140 fp=0xc4201777a8 sp=0xc420177700 pc=0x43d1710
github.com/theupdateframework/notary/client.(*repository).initialize(0xc4201084d0, 0xc4204aa890, 0x1, 0x1, 0xc4204aa8a0, 0x0, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/theupdateframework/notary/client/client.go:222 +0x425 fp=0xc420177a70 sp=0xc4201777a8 pc=0x43d0e45
github.com/theupdateframework/notary/client.(*repository).InitializeWithCertificate(0xc4201084d0, 0xc4204aa890, 0x1, 0x1, 0xc4204aa8a0, 0x0, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/theupdateframework/notary/client/client.go:366 +0x400 fp=0xc420177c10 sp=0xc420177a70 pc=0x43d2380
main.(*tufCommander).tufInit(0xc4200a7790, 0xc420317200, 0xc420270f60, 0x1, 0x6, 0x0, 0x0)
	/go/src/github.com/theupdateframework/notary/cmd/notary/tuf.go:505 +0x232 fp=0xc420177cd8 sp=0xc420177c10 pc=0x442f602
main.(*tufCommander).(main.tufInit)-fm(0xc420317200, 0xc420270f60, 0x1, 0x6, 0x0, 0x0)
	/go/src/github.com/theupdateframework/notary/cmd/notary/tuf.go:139 +0x52 fp=0xc420177d20 sp=0xc420177cd8 pc=0x4435462
github.com/theupdateframework/notary/vendor/github.com/spf13/cobra.(*Command).execute(0xc420317200, 0xc420270ea0, 0x6, 0x6, 0xc420317200, 0xc420270ea0)
	/go/src/github.com/theupdateframework/notary/vendor/github.com/spf13/cobra/command.go:698 +0x46d fp=0xc420177dc8 sp=0xc420177d20 pc=0x4171a0d
github.com/theupdateframework/notary/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200b8fc0, 0x0, 0x0, 0x0)
	/go/src/github.com/theupdateframework/notary/vendor/github.com/spf13/cobra/command.go:783 +0x2e4 fp=0xc420177ef8 sp=0xc420177dc8 pc=0x4172184
github.com/theupdateframework/notary/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200b8fc0, 0xc4200b8fc0, 0x0)
	/go/src/github.com/theupdateframework/notary/vendor/github.com/spf13/cobra/command.go:736 +0x2b fp=0xc420177f28 sp=0xc420177ef8 pc=0x4171e7b
main.main()
	/go/src/github.com/theupdateframework/notary/cmd/notary/main.go:196 +0x6a fp=0xc420177f88 sp=0xc420177f28 pc=0x442866a
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc420177fe0 sp=0xc420177f88 pc=0x402d512
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420177fe8 sp=0xc420177fe0 pc=0x4057771

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa7
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
Notary init exit code is 2

**Comment by a-dma** [comment]
Possibly a problem with the FFI and how Go calls into the C libraries.

As I said in the other issue, there's too many abstraction layers to understand what's happening. I'd try to attach a debugger to that process and step through it, or even better, build a debug version of ykcs11 and libykpiv and run against those.

**Comment by mouse07410** [comment]
Is there any reason why you use libykcs11 Target than opensc-pkcs11 from the current OpenSC?

In my experience, ykcs11 should be avoided, unless you need what it can do (generating a key on the token with policy like Physical Touch Enforced).

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 is out and contains major upgrade to ykcs11. Please try that version.

I'm closing this issue, please re-open if the problem persists.
