### ISSUE TITLE
Who was signing the 1.6.1 release tarball?

### ISSUE THREAD

**Issue by Jakuje** [Yubico/yubico-piv-tool#162]
I tried to verify the signature of the last 1.6.1 release as I did many times before, but this time, the gpgp says, there is a signature made by unknown key. I can not find this key under the list of people who sign the releases:

https://developers.yubico.com/Software_Projects/Software_Signing.html

Who signed this release and using which key?
```
+ gpgv2 --quiet --keyring gpgkey-9921835E.gpg yubico-piv-tool-1.6.1.tar.gz.sig yubico-piv-tool-1.6.1.tar.gz
gpgv: Signature made Fri Aug 17 09:23:51 2018 CEST
gpgv:                using RSA key BCA00FD4B2168C0A
gpgv: Can't check signature: No public key
error: Bad exit status from /var/tmp/rpm-tmp.GMgL4J (%prep)
```

**Comment by klali** [comment]
It's signed by me.

The full fingerprint is "0A3B 0262 BCA1 7053 07D5  FF06 BCA0 0FD4 B216 8C0A" and is listed on the Software Signing page.

**Comment by Jakuje** [comment]
Sorry for the noise. I probably had a bad look into the signing page and direct download from the keyserver using the short fingerprint did not work for me. Now, it works fine. Thank you.

**Comment by klali** [comment]
Np, vigilance is good and someone checking signatures is awesome =)
