### ISSUE TITLE
ykcs11: hardcoded token flags

### ISSUE THREAD

**Issue by b-fett** [Yubico/yubico-piv-tool#167]
https://github.com/Yubico/yubico-piv-tool/blob/master/ykcs11/yubico_token.c#L45

**Comment by a-dma** [comment]
Is this causing issues? Simply linking to a line of code is not very helpful.

**Comment by b-fett** [comment]
Of course it is.
I'm trying to access token flags with [pkcs11js](https://github.com/PeculiarVentures/pkcs11js) library to test, if pin is blocked. But even after PIN being entered 3 times incorrectly (`YubiKey PIV Manager` recognizes that PIN is blocked, `yubico-piv-tool  -astatus` saying that `PIN tries left:	0`) i get same `flags` value of token equals 1037.

**Comment by a-dma** [comment]
As noted in https://developers.yubico.com/yubico-piv-tool/YKCS11_release_notes.html, all the PIN-related operations are not supported by the module.

Realizing whether or not there are attempts left is possible, but currently not implemented.

**Comment by qpernil** [comment]
Yubico PIV tool 2.0.0 was recently released and is a major update to the included ykcs11 PKCS#11 implementation. However, it still doesn't manage the PIN blocked / low retry count etc flags in token info. We plan to implement this in the next minor release.

**Comment by qpernil** [comment]
This issue has now been mitigated on the master branch, and will be in the 2.0.1 release
