### ISSUE TITLE
Token label change

### ISSUE THREAD

**Issue by karen-arutyunov** [Yubico/yubico-piv-tool#169]
Is it possible to explicitly change the token label for Yubikey 4 using yubico-piv-tool?

When using relatively fresh version of yubico-piv-tool (>= 1.5.0) the label is implicitly set to the Common Name (CN) of the imported (via the -a import-certificate option) x509 certificate. That seems to not be the case for earlier versions of the tool. Is this implicit label change a bug or deliberate behavior?

I have failed to find a code that triggers this functionality. The _write_certificate() function that, I'm pretty sure, changes the label doesn't contain any code that explicitly make this change. Unless it sets some flags before calling _ykpiv_save_object(), that I'm unable to interpret.

Any information on this would be greatly appreciated.

Thanks.

**Comment by erikvanzijst** [comment]
Did you ever find an answer to this?

**Comment by karen-arutyunov** [comment]
Have been a while since then, but don't think so.

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 cintains a major update to libykcs11.so/dylib/dll, please upgrade.

CKA_LABEL returns a hard-coded value reflecting the purpose of the underlying PIV slot, and cannot be changed. 

CKA_SUBJECT returns the DER-coded Subject from the certificate stored in the slot. It will thus change if a new certificate is stored, but cannot be changed through the CKA_SUBJECT attribute.

A certificates stored in a slot is exposed as a data object plus a certificate object plus a public and a private key object. If your YubiKey supports attestation there will also be an attestation certificate object.

I'm closing this issue as it should work with the latest release. Please reopen if you find an issue with that version.
