### ISSUE TITLE
Missing info in documentation, please explain.

### ISSUE THREAD

**Issue by smrt28** [Yubico/yubico-piv-tool#171]
Hi,

I'm missing some information in the doc. Could you please explain...

1. MGM key is suppose to be a 3DES key. Why? How it works? I've studied the libykpiv source-code and it seems to me MGM key works like an access token (or a password) only which allows you to do a certain operation, so why 3DES? How it works? Why is't MGM key just a random string? Please explain.

2. At: https://developers.yubico.com/yubikey-piv-manager/PIN_and_Management_Key.html
"....An attacker could use the knowledge of this to effectively brute-force the PIN....". According to libykpiv source code It seems you can't read the salt without knowing the PIN. I'm not sure what does brute-force mean there? I would have to query Yubikey for every key try. Since the salt has 64bits the brute-force attack seems to me nonsense.

3. calling ykpiv_decipher_data(... YKPIV_ALGO_RSA2048, ...), I get 256 bytes output. I can use RSA_padding_check_PKCS1_type_2() to extract the open data. I would expect for the same input the decipher function gives me the same output. But the 256 bytes seems somehow randomized. Is it possible to call ykpiv_decipher_data() to be deterministic and give me the seme outpu for the same input?

4. yubico-piv-tool write-objetc/read-object. I can store 3kB of arbitrary data in 20 slots. It's nice, but is there any particular reason for this feature?

5.  What are ykpiv_util_XXX_mscmap ykpiv_util_XXX_msroots functions for?

Thansk

**Comment by qpernil** [comment]
1. The mechanism to authenticate with the management key involves a challenge-response mechanism that mutually authenticates the client and the YubiKey, based on 3DES. 3DES uses a 24 byte binary key, which becomes 48 character when hex-encoded.
2. The derivation of management key using a salt is deprecated. The current implementation of this instead stores a fully random management key (the 24 bytes mentioned above) in a PIN-protected slot on the YubiKey. Using this mechanism a brute force attack is not possible.
3. There are different types of padding used together with RSA encryption. A common property of all of them is that they insert some random data in the padding phase. The purpose of this is to ensure the same cleartext yields different ciphertext each time, for security purposes.
4. See the PIV specification, the YubiKey is a PIV-like device and the slots are part of the specification.
5. They are used by the minidriver.
Hope this helps.
