### ISSUE TITLE
Wrong ATR with ACS ACR122U NFC reader

### ISSUE THREAD

**Issue by FlGreff** [Yubico/yubico-piv-tool#172]
Hello,

I don't manage to make my Yubikey 5 NFC working with an ACS ACR122U NFC reader. More precisely, I aim to read the PIV certificates in it. I have tested the setup with yubico-piv-tool, OpenSC piv-tool, pkcs11-tool, pkcs15-tool, opensc-tool and pcsc_scan. OS wise, I have tested it on Raspbian, Ubuntu and Windows 7.
Everything is working fine in USB.

Basically, it seems to be an ATR problem, because the Yubikey is considered as a generic OpenPGP card in NFC. The ATR returned via NFC and USB are different (tested with pcsc_scan). The Yubikey is thus considered as an invalid card when running yubico-piv-tool, for instance.

I have tested various options but cannot make it work. I am wondering if this could be a reader issue, although the ACS ACR122U should be fully compliant with PC/SC and CCID. Furthermore, the reader is "working", meaning it is able to correctly read basic NFC tags.

Thank you in advance for your help,
Best regards

**Comment by klali** [comment]
I'm not sure which software you're having problems with here, yubico-piv-tool only uses ATR to see if a device is a YubiKey NEO, it's never used for YubiKey5.

However, the YubiKey 5 ships with PIV disabled over NFC (it doesn't always play nice wiht microsoft platforms over NFC), you can enable it with the yubikey-manager tool.
