### ISSUE TITLE
keyUsage=digitalSignature

### ISSUE THREAD

**Issue by HavardLine** [Yubico/yubico-piv-tool#173]
Hi There

I would like to add a self-signed cert to slot 9c. It would be used to sign PDFs.

We use PDF-XChange Editor. Seems like the software need a flag like keyUsage=digitalSignature before accepting the cert.

Can we set the "keyUsage=digitalSignature" bit using yubico-piv-tool?

The code bellow is my current code. yubico-piv-tool 1.4.3 is installed.
```
# Defining secret management key
set MGM-KEY=010203040506070801020304050607080102030405060708

# Generating key in slot 9c and exports public key
yubico-piv-tool -s 9c -A RSA2048 -a generate -k  $MGM-KEY -o c:/test/public.key

# Self-signing cert in slot 9c
yubico-piv-tool -H SHA256 -a verify-pin --valid-days 3650 -a selfsign-certificate -s 9c -v -S "/CN=Signing key for NAME at COMPANY/O=COMPANY/L=CITY/C=NO/" -i c:/test/key.pub -o c:/test/cert.cer
```

**Comment by klali** [comment]
Hey,

We've not wanted to add to much certificate management features to yubico-piv-tool, rather poiting at openssl for this sort of thing. Using the openssl commandline with a pkcs11 module it's possible to configure your certificates as you please.

A quick example of how to do this with the opensc pkcs11 module:

generate key using yubico-piv-tool:
$ yubico-piv-tool -a generate -s 9a

selfsign and load a cert with yubico-piv-tool (so the pkcs11 module can find it):
$ yubico-piv-tool -a verify -a selfsign -s9a -S '/CN=test/' --in pubkey.pem --out cert.pem
$ yubico-piv-tool -a import-cert -s9a --in cert.pem

create a openssl config:
$ cat > engine.conf <<EOF
openssl_conf = openssl_init

[openssl_init]
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
MODULE_PATH = /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so

[ req ]
distinguished_name = req_dn
string_mask = utf8only
utf8 = yes

[ req_dn ]
commonName = Common Name (eg, your name)
EOF

use openssl to sign a certificate request:
$ OPENSSL_CONF=engine.conf openssl req -subj "/CN=test/" -sha256 -engine pkcs11 -keyform engine -x509 -key 0:01
