### ISSUE TITLE
FASC-N generation utility

### ISSUE THREAD

**Issue by plloydhpe** [Yubico/yubico-piv-tool#177]
A few things caught my eye while looking at the FASC-N generation utility, fasc.pl.

Here is the interesting bit of code:

my %encoding = (
  0 => "00001",
  1 => "10000",
  2 => "00100",
  3 => "00111",
  4 => "01000",
  5 => "01011",
  6 => "01101",
  7 => "01110",
  8 => "10000",
  9 => "10011",
  S => "11010", # the examples and definitions of S and F differ
  F => "10110", # but we'll go with the examples here..
  E => "11111",
);

Note that 1 and 8 both map to '10000'. That seems almost certainly to be a bug.

Empirically, the rightmost bit is the parity bit, which is consistent with 2.3 TIG SCEPACS. That leaves the leftmost 4 bits to encode each digit or SS, FS and ES. The mapping seems inconsistent however regarding endianness, and the mapping does not fully match table 7 of 2.3 TIG SCEPACS. 

It's interesting to note that the FASC-N in the default CHUID uses mostly 9s and 0s, and both of those happen to have the same 4 bit encoding in the leftmost 4 bits regardless of endianness. But other digits are used as well, and that makes me wonder.

**Comment by klali** [comment]
Yes, it seems like 1 should be 00010 to fit in with the rest of this assuming the endianness of the rest is correct. In this case it seems like S/F is flipped as well.

I'm not aware of anything that can read this format, for interop purposes, are you?

**Comment by klali** [comment]
This was fixed in #178
