### ISSUE TITLE
Adjust return codes for verify-pin

### ISSUE THREAD

**Issue by mike-csis** [Yubico/yubico-piv-tool#19]
Verify-pin gives the same return code on a failed try as it does on the "pin code blocked" message. The blocked message should return f.ex. 2 so that we in scripts can loop over the verify-pin until it is blocked, rather than hope that 3-4 attempts are enough. 

See the attached picture.
![tmp](https://cloud.githubusercontent.com/assets/5907292/7409244/04488f24-ef25-11e4-8d9e-fe582ef66af5.png)

**Comment by klali** [comment]
Hello

Currently the code is just using EXIT_FAILURE for all failures. If we go the route to change this I'd like to define different exit codes for different errors and use those consistently, which would be quite a bit of work.
So with that said I'm positive of this, but it's not in the works.

/klas

**Comment by mike-csis** [comment]
But don't you already, in other cases, use different error codes for other subcommands?

**Comment by klali** [comment]
No, it's using EXIT_SUCCESS (0) for ok and EXIT_FAILURE(1) for all errors. (as you can see from https://github.com/Yubico/yubico-piv-tool/blob/master/tool/yubico-piv-tool.c#L1487 and onward)

**Comment by mike-csis** [comment]
Maybe I'm thinking of some of the other tools in the Yubico toolkit.
Anyways. Add a +1 to the error codes task then.

**Comment by qpernil** [comment]
The PIV library now returns better error codes. This will be part of the next minor release (After 2.0.0). Fixing the status codes of the tool is a candidate for that release.

**Comment by qpernil** [comment]
Since it's kind of a niche requirement to be able to loop until blocked, and it can be done by parsing the text output of the program this was not accepted as a change for the upcoming 2.1.0 release.
