### ISSUE TITLE
pins and code not changing on yubikey5 after being set

### ISSUE THREAD

**Issue by benoit-canet** [Yubico/yubico-piv-tool#192]
Hi,

On ubuntu 19.04 with a yubikey 5 and yubico ppas with self generated 4096 RSA key and the touch fix parameter set the pin changes are ignored: I succeed to do a card edit and change pin codes and the same seems to work with ykpersonalise but the key forget the new codes.

**Comment by benoit-canet** [comment]
It was transient

**Comment by klali** [comment]
Is there an issue here?

if you're using 4096 RSA you're probably not using this tool and the PIV support (since that's RSA 2048 max).

**Comment by mouse07410** [comment]
"card edit" suggests that `gpg` and OpenPGP applet are in use. 

PIN and other codes for PIV and OpenPGP are independent: changing one doesn't affect the other.
