### ISSUE TITLE
YKCS11 support to change PUK pin

### ISSUE THREAD

**Issue by tharsanrp** [Yubico/yubico-piv-tool#199]
I was wondering if there are any way to change the puk pin through ykcs11 ? 
If not, is there any plans to add the ability to change the puk pin through ykcs11?

 If not, I was wondering if I can work on it, since I need to change the puk pin. 
To change the management key, the user is a Security Officer.
To change the user pin, the user is a User.
I was wondering what the user type to change the puk pin?

**Comment by a-dma** [comment]
The abstraction layer between PIV and PKCS#11 is fairly leaky and kind of forced in a few places.
I don't think there is a clean way to change the PUK. Is using `yubico-piv-tool` for that not an option?

**Comment by mxork** [comment]
Agreed the abstraction layer is leaky. However, we have code calling through pkcs11 in a couple places and the shortest path between us and *feature* is adding change_puk to ykcs11.

The proposal is to abuse the semantics of `CKU_CONTEXT_SPECIFIC` in `YUBICO_token_change_pin`. Given that the pkcs11 spec is already stretched, this seems like a small cheat.

@tharsanrp should have a patch inbound. Feedback, or workarounds that go through ykcs11 are obviously welcome.

**Comment by a-dma** [comment]
Yeah, I was thinking about something along the line of using `CKU_CONTEXT_SPECIFIC` to mean change_puk as well, given that it's the only other user type available. An alternative would be to prepend the the PIN with a known string like "puk:" and calling `C_SetPIN` with that. So `C_SetPIN(hSession, "puk:12345678", 12, "87654321", 8)` would change the PUK from `12345678` to `87654321`.

I'm not sure which one is better, prepending the PIN probably has higher chances of working across different implementations.

**Comment by mxork** [comment]
String prefix looks good. Less rude than taking over CKU_CONTEXT_SPECIFIC.

**Comment by tharsanrp** [comment]
Does this make sense?
https://github.com/Yubico/yubico-piv-tool/pull/201

**Comment by mouse07410** [comment]
> Is using `yubico-piv-tool` for that not an option?

i think this is a valid question, and would like to see a reply with reasoning why.

**Comment by mouse07410** [comment]
> Does this make sense?
> #201

Yes it does, IMHO.

**Comment by a-dma** [comment]
@tharsanrp it does, thanks. Merged.
