### ISSUE TITLE
Delimiter for Please paste the input..

### ISSUE THREAD

**Issue by supreetd21** [Yubico/yubico-piv-tool#200]
I have a Yubikey 4. 
I'm trying to sign my CSR using the private key & certificate I have stored in slot 9c using the YubiKey Manager GUI tool on Macos.
I couldn't find any documentation on the --sign apart from an option in --full-help.
https://www.yubico.com/wp-content/uploads/2016/05/Yubico_PIV_Tool_Command_Line_Guide_en.pdf

I used the following command on macOS:
./yubico-piv-tool --sign -a verify-pin --slot 9c
Enter PIN:
Successfully verified PIN.
Please paste the input...
-----BEGIN CERTIFICATE REQUEST-----
MIICijCCAXICAQAwRTEVMBMGA1UEAxMMQzQ0RjMzMjA2MjZEMQswCQYDVQQGEwJJ
TjELMAkGA1UECBMCTUgxEjAQBgNVBAoTCUVzcHJlc3NpZjCCASIwDQYJKoZIhvcN
...
...
-----END CERTIFICATE REQUEST-----

The input stream does not stop, what should be the delimiter to indicate the tool to stop accepting the input to sign.

**Comment by a-dma** [comment]
You can either give an input file to the tool by using the `-i FILENAME` option, or you can send an `EOF` after pasting your input. The latter is normally done with `Ctrl+D`.

**Comment by supreetd21** [comment]
It worked. Thanks for the information.
Could you let me where could I get more information on the --sign option.

I want to sign my CSR with the key/cert stored in the digital signature(9c) slot.
From the output, I suppose that a digest has been created from the input & has been signed.

Is it possible to perform CSR signing with a YubiKey?

**Comment by a-dma** [comment]
There is no direct support for signing CSRs, yubico-piv-tool has support for generic signatures of message digests with the `--sign` option. If you have something that can produce such digest (e.g., OpenSSL, something that uses PKCS#11, your own tool) then you can give that digest to the tool (or the library), get it signed and append that signature where you need it.

**Comment by supreetd21** [comment]
Okay, got it. Thus, I started using the PKCS engine for OpenSSL for signing CSR's.

I have been trying using the PKCS engine for OpenSSL as well(https://github.com/OpenSC/libp11)
```
engine -t dynamic -pre SO_PATH:/usr/local/Cellar/engine_pkcs11/0.1.8/lib/engines/engine_pkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/Library/OpenSC/lib/opensc-pkcs11.so
```
```
req -engine pkcs11 -keyform engine -key 02 -new -x509 -in /Users/supreetdeshpande/Desktop/sample.csr -out p.pem
```

It prompts me for the PIN and even on entering the correct password it fails with 'User not logged in'.
I've been using OpenSSL 1.0.2, these were the failures I got.
```
4538725996:error:8000A101:PKCS11 library:PKCS11_rsa_sign:User not logged in:p11_ops.c:131:
4538725996:error:0D0DC006:asn1 encoding routines:ASN1_item_sign_ctx:EVP lib:a_sign.c:306:
```

I'm not sure if this is a YubiKey issue or is it a PKCS11 provider issue. (Had a similar issue with https://github.com/LudovicRousseau/PyKCS11/blob/master/samples/signature.py)
Reference :https://developers.yubico.com/YubiHSM2/Usage_Guides/OpenSSL_with_pkcs11_engine.html

Could you let me know any channel where I could post such issues?

**Comment by a-dma** [comment]
It works for me using OpenSSL 1.1, try putting everything into a config file first. Something like

```
openssl_conf = openssl_init

[openssl_init]
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = /usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so
MODULE_PATH = /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so
init = 0

[ req ]
distinguished_name     = req_distinguished_name

[ req_distinguished_name ]
countryName                    = Country Name (2 letter code)
countryName_default            = AU
countryName_min                = 2
countryName_max                = 2
```

Save that as `openssl.conf` and then add `OPENSSL_CONF=openssl.conf` before your command (or just export it). Change the paths to match your installation.

**Comment by supreetd21** [comment]
Thanks, @a-dma for the reply,

I tried the above script with the following script. 
Had to do a few changes to make it work.
```
openssl_conf = openssl_init

[openssl_init]
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = /usr/local/Cellar/engine_pkcs11/0.1.8/lib/engines/engine_pkcs11.so
MODULE_PATH = /Library/OpenSC/lib/opensc-pkcs11.so
init = 0

[ req ]
distinguished_name     = req_distinguished_name
prompt = no

[ req_distinguished_name ]
countryName                    = AU
```

I didn't get the prompt for the certificate but it failed with the same error.
Is it something to do with 'touching' the Key? Can we configure the touch policy?

Also, I'm using the vanilla version of engine-pkcs11(`brew install engine_pkcs11`) - Have you tried using that version?
I'm checking its compatible with OpenSSL 1.0.2. Would you have any idea on this front?

**Comment by a-dma** [comment]
I'm using Linux and have not tried on macOS. If you have a touch policy set then you should see the device starting to blink when in requires a touch. Unfortunately there is no easy way to tell the client to prompt the user for a touch, so you'll have to know it yourself. Alternatively you can disable touch but this can only be done at key generation (check the `--touch-policy` flag).

Given that the engine_pkcs11 on brew depends on OpenSSL 1.0.2 I assume they are compatible. Maybe you can try to spin up a Linux VM with OpenSSL 1.1 and if you have better luck with that?

**Comment by supreetd21** [comment]
Hi @a-dma , 
It worked with a Linux VM. Maybe some issue with MacOS. Thanks for the help!
I'm trying generating the keys on the device through the tool.

> opensc-tool --list-algorithms
```
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID 00 00
Algorithm: rsa
Key length: 1024
Flags: padding ( none ) hashes ( )

Algorithm: rsa
Key length: 2048
Flags: padding ( none ) hashes ( )

Algorithm: rsa
Key length: 3072
Flags: padding ( none ) hashes ( )

Algorithm: ec
Key length: 256
Flags:

Algorithm: ec
Key length: 384
Flags:
```
Now, I run the generate keypair command but it fails.

> pkcs11-tool --module /usr/lib/opensc-pkcs11.so --login --pin xxxxxx --keypairgen --key-type rsa:1024 --label "my_key" --usage-sign
```
Using slot 0 with a present token (0x0)
error: Generate RSA mechanism not supported
Aborting.
```
Would you know the reason for such an issue?

**Comment by a-dma** [comment]
what does `pkcs11-tool --module /usr/lib/opensc/pkcs11.so -M` return? Also, set the `OPENSC_DEBUG` environment variable to a number to get more debug.

**Comment by supreetd21** [comment]
Hi,
>pkcs11-tool --module /usr/lib/opensc-pkcs11.so -M
```
Using slot 0 with a present token (0x0)
Supported mechanisms:
  SHA-1, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest
  MD5, digest
  RIPEMD160, digest
  GOSTR3411, digest
  ECDSA, keySize={256,384}, hw, sign, other flags=0x1800000
  ECDH1-COFACTOR-DERIVE, keySize={256,384}, hw, derive, other flags=0x1800000
  ECDH1-DERIVE, keySize={256,384}, hw, derive, other flags=0x1800000
  RSA-X-509, keySize={1024,3072}, hw, decrypt, sign, verify
  RSA-PKCS, keySize={1024,3072}, hw, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={1024,3072}, sign, verify
  SHA256-RSA-PKCS, keySize={1024,3072}, sign, verify
  SHA384-RSA-PKCS, keySize={1024,3072}, sign, verify
  SHA512-RSA-PKCS, keySize={1024,3072}, sign, verify
  MD5-RSA-PKCS, keySize={1024,3072}, sign, verify
  RIPEMD160-RSA-PKCS, keySize={1024,3072}, sign, verify
```

Here's the link to the OpenSC Debug logs.
[Link](https://gist.github.com/supreetd21/7ced0a75cd719d42497865523f4635e2)

I can see here that RSA 1024 is supported in the mechanisms,

**Comment by a-dma** [comment]
As you can see from that list the `CKM_RSA_PKCS_KEY_PAIR_GEN` mechanism is not present and therefore generating keys is not allowed.

**Comment by qpernil** [comment]
This should work with libykcs11.so (or libykcs11.dylib on macos) from yubico-piv-tool 2.0.0

/Per
