### ISSUE TITLE
YK5NFC PIV PKCS#11 changing management key breaks provate key password

### ISSUE THREAD

**Issue by cederom** [Yubico/yubico-piv-tool#208]
Hello world,

I am using Yubikey5NFC PIV to store a key and certificate from PKCS#11 file. With default PIN/PUK/MGMK all works fine. When I change PIN and PUK all works fine. When I change management key I can no longer use uploaded key+cerfiticate..
* No matter what is the order of mgm key change and key upload or vice vrsa.
* I am using OpenCD-PKCS on windows client.
* Keys are generated and managed on FreeBSD.
* With default pin/puk/mgm all works fine but I do not want to leave default mgm key untouched.
* I did not set key password, even removed password from a key that got into pkcs11.

What is the relation between mgm key and pin/puk slot contents?

Any hints appreciated :-)

**Comment by cederom** [comment]
Okay, so the problem is the conflict between `yubico-piv-tool` and `ykman` that seems to manage token in a different way. When using only `yubico-piv-tool` I can change all PIN, PUK, MGM KEY. When using `ykman` then I can work with token via `yubico-piv-tool` but that token then does not work correctly with `OpenSC-PKCS11`..

```
% yubico-piv-tool -V                                                                   │
yubico-piv-tool 1.7.0

% ykman -v
YubiKey Manager (ykman) version: 3.0.0
Libraries:
    libykpers 1.19.0
    libusb 1.0.0

% uname -a
FreeBSD 0xCFMX4 13.0-CURRENT FreeBSD 13.0-CURRENT r350861 GENERIC  amd64
```

It would be nice to put that info on your websites / guides if this is intended behavior.. it stole some hours of my life while getting familiar with this amazingly nice solution ;-)

**Comment by a-dma** [comment]
How are you changing the management key?

Are you using the `--protect` flag in `ykman`? That does additional work to protect the management key by using the PIN and `yubico-piv-tool` doesn't implement that logic.

**Comment by cederom** [comment]
Hello @a-dma I am not using `--protect` simply `change-mgm-key` and similar in `ykman` which seemed simpler in use for me this is why I was using `ykman` for token management and `yubico-piv-tool` for keys management in piv mode.. not I am only using one and that seems to work :-)

**Comment by a-dma** [comment]
In that case, could you please provide a list of commands that result in an error? It sounds like nothing should interfere if you're not protecting the management key.

cc @dagheyman

**Comment by cederom** [comment]
Hmm, today I have tried to use that token with OpenVPN on windows using `opensc-pkcs11.dll` provider.. token that was prepared with `yubico-piv-tool` and I got the same problem again as working with `ykman` - the client could not use password to decrypt private key :-(

* chaning management key breaks PKCS11 interface both on `yubico-piv-tool` and `ykman`.
* change of PIN and PUK does not break PKCS1.
* I am uploading password less private key and certificate from a generated p12 file.
* no difference if I upload key+cert before or after mgmt key change.

Maybe I am doing something wrong?? Any hints welcome :-)

**Comment by a-dma** [comment]
If you're using OpenSC's module I don't think there is any way to specify the management key with that. I believe they just assume the default key and use that.

**Comment by cederom** [comment]
I don't really understand how management key is related with __reading__ piv keys / accessing slot data. Management key is necessary only to __write__ new key to they piv and/or manage its slots. This is why it is called __management__ key, not __access__ key, right?

There is one way to protect access to the key and it is PIN.

There are two ways to manage piv. One is PUK that can be used to reset invalid PIN counter. Second is management key that allows modification of piv.

Therefore I should change my management key in order to avoid my piv modification by a third party.

The only situation where none of above is necessary is the piv reset to a default state that also destroys key/certificate/slot data.

I don't understand how changing management key can impact reading the key when valid PIN is entered? Why changing management key breaks my piv? This smells like a bug right?

**Comment by jmyreen** [comment]
Not being able to read the private key is a feature, not a bug. The whole
point of the security token is to protect the key. Why do you need to read
it?

Johan Myréen
(Not affiliated with Yubico)

Den tors 22 aug. 2019 22:36Tomasz CEDRO <notifications@github.com> skrev:

**Comment by a-dma** [comment]
What do you mean by reading? As others have said, extracting a private key is not possible by design. If you're talking about public keys then the only way to do that with PIV a) during key generation or b) after you've loaded a certificate containing that public key, in that case you can read that certificate without having to provide a Management Key or a PIN.

As I said, I think that if you provide a minimal set of commands to reproduce the issue then it's easier to avoid misunderstandings.

**Comment by cederom** [comment]
cheeezzzz. by reading i mean operating on a key not extracting the key. by writing i mean programming new key into slot.

again. when i chnage mgmt key piv becomes useless  for opensc (read). it only works with default mgmt key.

this is a problem because with default mgmt key anyone can modify (write) my piv.

**Comment by cederom** [comment]
# Scenario

Scenario is simple, I have a Private Key and Certificate that is used by OpenVPN client.
* They work fine when used as file.
* They work fine when used on YK5NFC PIV with default settings after reset.
* They work fine when PIN and PUK are changed on PIV.
* They stop working when I change PIV MGMT KEY.

# Environment

I am using Windows OpenVPN for a client, but I will show you here what is the problem t ohave everything on a single commandline.

```
% uname -a
FreeBSD 0xCFMX4 13.0-CURRENT FreeBSD 13.0-CURRENT r350861 GENERIC  amd64

% ykman -v
YubiKey Manager (ykman) version: 3.0.0
Libraries:
    libykpers 1.19.0
    libusb 1.0.0

% yubico-piv-tool --version
yubico-piv-tool 1.7.0

% openvpn --version
OpenVPN 2.4.7 amd64-portbld-freebsd13.0 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [MH/RECVDA] [AEAD] built on Aug 18 2019
library versions: OpenSSL 1.1.1c-freebsd  28 May 2019, LZO 2.10
Originally developed by James Yonan
Copyright (C) 2002-2018 OpenVPN Inc <sales@openvpn.net>
Compile time defines: enable_async_push=no enable_comp_stub=no enable_crypto=yes enable_crypto_ofb_cfb=yes enable_debug=yes enable_def_auth=yes enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=needless enable_fragment=yes enable_iproute2=no enable_libtool_lock=yes enable_lz4=yes enable_lzo=yes enable_management=yes enable_multihome=yes enable_pam_dlopen=no enable_pedantic=no enable_pf=yes enable_pkcs11=yes enable_plugin_auth_pam=yes enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=no enable_server=yes enable_shared=yes enable_shared_with_static_runtimes=no enable_silent_rules=no enable_small=no enable_static=yes enable_strict=yes enable_strict_options=no enable_systemd=no enable_werror=no enable_win32_dll=yes enable_x509_alt_username=no with_aix_soname=aix with_crypto_library=openssl with_gnu_ld=yes with_mem_check=no with_sysroot=no
```

# How to reproduce

1. Look at current PIV:
```
% yubico-piv-tool -astatus
Version:        5.1.2
Serial Number:  NNN
CHUID:  No data available
CCC:    No data available
Slot 9a:
        Algorithm:      RSA2048
        Subject DN:     CN=XXX
        Issuer DN:      CN=XXX
        Fingerprint:    XXXYYYZZZ
        Not Before:     Aug 18 16:29:12 2019 GMT
        Not After:      Aug 18 16:29:12 2020 GMT
PIN tries left: 3
``` 

### I WILL UPDATE THIS COMMENT SO I WILL NOT USE RESULTS WHEN BROWSER FAILS. THIS MESSAGE WILL DISAPPEAR WHEN FINISHED :-)

**Comment by mouse07410** [comment]
Your token will not be PIV compliant until you create CHUID and CCC containers. `yubico-piv-tool` can do it for you.

With default management key, Windows does is own thing, so it doesn't mind the non-compliance.

**Comment by cederom** [comment]
Thanks @mouse07410 I will double check that and report back :-)

**Comment by qpernil** [comment]
Reading data objects and using private keys is protected by the PIN, and is independent of the MGMT KEY, i.e. changing the MGMT_KEY will not change the PIN or the requirement to verify the PIN before accessing objects as stated. PUK is only used for unblocking the PIN. Both PIN and PUK must be blocked before the reset command can be used. All of this is enforced by the YubiKey.

yubico-piv-tool 2.0.0 is a major update to ykcs11, which is now a fairly complete PKCS11 implementation.
It maps the MGMT_KEY as the SO PIN in PKCS11, so any application where you can specify the SO PIN should work with a non-default MGMT KEY.
