### ISSUE TITLE
build-and-test.sh removes all autoremove packages without confirmation

### ISSUE THREAD

**Issue by mzpqnxow** [Yubico/yubico-piv-tool#213]
I had an unpleasant experience today where the build-and-test.sh script performed an autoremove of all suggested packages without any confirmation (Debian 10)

These packages were erroneously marked as auto removable after a major distribution upgrade and this effectively hosed my system, though I was able to kill apt once I realized what was happening.

This really ought to ask for confirmation before performing package removal, no?

EDIT: Yes, completely hosed. I am going to be unable to work for several hours (minimum) as I had a custom kernel as well as patched nvidia drivers... *sigh*

**Comment by a-dma** [comment]
Ouch, sorry to hear that.

The `build-and-test.sh` script is meant to be run by Travis and shouldn't be used directly.
The instructions to build from source are in the [README](https://github.com/Yubico/yubico-piv-tool#building).

I agree that we should move that script somewhere else, where is less visible, for example in `build-aux`.

@mrmekon since you were the last to touch this, do you have any opinions or anything to add?

**Comment by mrmekon** [comment]
Oof, sorry @mzpqnxow!  I agree, let's move it out of the root.  Even better, let's make it exit with a warning if you don't set an `I_AM_A_CI` environment variable?

**Comment by a-dma** [comment]
Sure, `TRAVIS_OS_NAME` should be enough, no?

**Comment by mzpqnxow** [comment]
> Ouch, sorry to hear that.
> 
> The `build-and-test.sh` script is meant to be run by Travis and shouldn't be used directly.
> The instructions to build from source are in the [README](https://github.com/Yubico/yubico-piv-tool#building).
> 
> I agree that we should move that script somewhere else, where is less visible, for example in `build-aux`.
> 
> @mrmekon since you were the last to touch this, do you have any opinions or anything to add?

Ah, so my mistake then, I guess I got a little over-eager when I saw the Makefile (to be honest, I don't recall if I even read it, I usually do to at least see what targets are available)

Either way, thank you for "fixing" this, even though it appears it is not *technically* broken. Just problematic for fools like me that didn't read the build instructions carefully (or at all!)

**Comment by aveenismail** [comment]
Non of the files in question are part of the code base any more. Closing this ticket
