### ISSUE TITLE
request-certificate failure

### ISSUE THREAD

**Issue by aphuang2013** [Yubico/yubico-piv-tool#214]
1) using -a generate to generate a RSA key on slot 9a
2) fail to generate CSR with the following command
====
yubico-piv-tool.exe -P 123456 -s 9a -S "/CN=test1" -a request-certificate -i \temp\pubkey.pem -o ABCD.csr
Failed signing request.​
====
3) try the same operation with ykman and it works
====
"\Program Files\Yubico\YubiKey Manager\ykman.exe" piv generate-csr -P 123456 -s "/CN=test2" 9a \temp\pubkey.pem ABC.csr
C:\temp>more ABC.csr
-----BEGIN CERTIFICATE REQUEST-----​
MIICajCCAVICAQAwFDESMBAGA1UEAw
…
====

is there something I missed in the request?

**Comment by a-dma** [comment]
You're missing the verification action. Try adding `-a verify` before `-a request-certificate`.

**Comment by aphuang2013** [comment]
thank you, it was not clear to me that -a verify-pin must go before "-a request-certificate" in the argument list.  once I understand the sequence, it works.
