### ISSUE TITLE
Can't interact if serial-api-visible flag is unset

### ISSUE THREAD

**Issue by avtobiff** [Yubico/yubico-piv-tool#215]
Hi!

Tried using the PIV functionality, but nothing worked.

It was not even possible to retrieve status
```
$ yubico-piv-tool -a status -v2
trying to connect to reader 'Yubico YubiKey OTP+FIDO+CCID 00 00'.
> 00 a4 04 00 05 a0 00 00 03 08 
< 61 11 4f 06 00 00 10 00 01 00 79 07 4f 05 a0 00 00 03 08 90 00 
> 00 fd 00 00 00 
< 05 01 02 90 00 
> 00 f8 00 00 00 
< 69 85 
Failed retrieving serial number: 6985
Failed to connect to reader.
```

An internet search showed similar issues #125, #146, and #147, and
also other bug trackers mentioning udev rules etc. Everything was
setup and working correctly AFAICT: pcscd.service, pcscd.socket,
udev rules etc.

However, another search for the "Failed retrieving serial number"
yielded yubico/yubikey-personalization#31. The flag `serial-api-visible`
is needed to show the serial number.

Following the advice to enable `serial-api-visible` made yubico-piv-tool
work fine.

I suggest a better error message, perhaps some hint that the flag
'serial-api-visible' is needed for yubico-piv-tool communication to
work.

**Comment by klali** [comment]
This is fixed on master (in c61d6c6f2303d9bc579fb33c8617628d8ed1244b) but not released yet, we're gearing up for a new release.
