### ISSUE TITLE
SCardConnect failed, rc=8010000b

### ISSUE THREAD

**Issue by KirbyDE** [Yubico/yubico-piv-tool#218]
I am getting this error on Windows 10 Pro (Version 1909 Build 183635.35) with Version 1.7.0:

```
c:\Yubico\bin>yubico-piv-tool -a status -v 10
trying to connect to reader 'Yubico Yubikey 4 OTP+U2F+CCID 0'.
SCardConnect failed, rc=8010000b
error: no usable reader found.
Failed to connect to reader.
```

Interestingly, this does work just fine after starting YubiKey Manager (it does not have to be kept open, just opening it once is enough).

Is there anything that can be done to fix this?

**Comment by a-dma** [comment]
It looks like a sharing violation. Are you also running gpg-agent or something else that is opening the card with exclusive access?

**Comment by qpernil** [comment]
YubiKey Manager closes the pgp agent, which could explain this. This is a known issue that doesn't have a good solution that we could implement in the ykcs11/ykpiv libraries. The root cause is that someone else is hogging the USB device.
