### ISSUE TITLE
Signature output is not binary

### ISSUE THREAD

**Issue by antonio-fr** [Yubico/yubico-piv-tool#221]
In the current 1.7.0 version, the sign output is not binary but text mode. In Windows, it translate all x0a in x0dx0a in the DER signature, making it misencoded and not valid. Since it seems not possible to change the output, this renders many signatures (around 1 over 4) using windows invalid. I can't see any reason why the signature DER is not in binary.

For now, a workaround is to check DER encoding and change x0dx0a to x0a wherever the length is less than the bit stream. As we need the DER for an other system, this is very overhead processing.

Is it possible to force binary output from command line with an argument (like -f binary) ? Is there any way to change the sign output encoding (to hex or base64 based) ?

**Comment by antonio-fr** [comment]
Additionally, there's the same issue with the input :
`yubico-piv-tool --pin xxxxxx -a verify-pin -f binary --sign -s 9c -H SHA384 -A ECCP384 -i - -o -`
gives an bad signature for input = 0xf5b6fabe341407de1f54d60ae6819a8bced9d83698569b0167978f5ff31a5824 for example.

The workaround here, to get a cross-platform behavior, is to input through a file, so writing the data in a file before calling yubico-piv-tool.

**Comment by klali** [comment]
I guess that the sign flag should support the --format used for the read/write object.
Without this the workaround is to use files for input/output, that way the tool knows enough to open the files as binary, when using STDIN/STDOUT this is hard.

**Comment by antonio-fr** [comment]
I think that the yubico-piv-tool must output in binary mode when the output is DER, even in stdout.
And, it must follow the "-f" argument for the stdin.

**Comment by qpernil** [comment]
Redirecting to a file (incuding stdout, i.e. not redirecting explicitly) has problems in Windows as the file is opened in text mode outside the control of the program (yubico-piv-tool). If you use the -o option with a file name the application will open the file itself, in binary mode.
