### ISSUE TITLE
 PKCS8 cert fails to sign with code 6a80

### ISSUE THREAD

**Issue by LuckyDucky583** [Yubico/yubico-piv-tool#222]
Hi, I am trying to sign a pkcs8 certificate for my Yubikey 5 NFC, but it keeps throwing the error message "Failed sign command with code 6a80". Unfortunately, I am unable to find out what code 6a80 stands for. What could be the reason this keeps happening?

**Comment by qpernil** [comment]
The code is SW_ERR_INCORRECT_PARAM. Most likely the key id is incorrect. Keep in mind that mapping from CKA_ID to PIV slots in ykcs11 is broken (compared to opensc) in 1.7.0, please try this again with the recent 2.0.0 release.
