### ISSUE TITLE
Unblocking pin with pkcs11

### ISSUE THREAD

**Issue by Justinette2175** [Yubico/yubico-piv-tool#233]
Hi, I am creating a user interface that allows for yubikey management within an application. 

I saw that you will soon be releasing the ability to read PIN-related flags from C_GetTokenInfo, which we're looking forward to using. 

In the meantime, ss there a way to allow users to unblock their PIN by entering the PUK, using the PKCS11 library? I can only seem to find information on C_SetPIN.

**Comment by qpernil** [comment]
With the as-yet unreleased 2.0.1 you can specify pin:123456 as the new PIN and puk:12345678 as the old PIN in C_SetPin

**Comment by Justinette2175** [comment]
@qpernil That's great, thank you. Do you know when that will be released just so I can set myself a reminder to implement it then?

**Comment by qpernil** [comment]
The release will be called 2.1.0 (since we added features) and is planned for May 25.
