### ISSUE TITLE
memory leak in yubico-piv-tool.c

### ISSUE THREAD

**Issue by invd** [Yubico/yubico-piv-tool#235]
A number of paths in the `main()` that do not correctly free the ykpiv state before returning. As far as I can see, there is no practical impact during regular usage since this happens directly before the program exit, but it would be cleaner to free it explicitly.

This was found via fuzzing and AddressSanitizer.

`ykpiv_init()` allocates the memory in question at 
https://github.com/Yubico/yubico-piv-tool/blob/53d7115b7106685ee91655f787fcd5fdff2ee1e6/tool/yubico-piv-tool.c#L2027 

Once the initialization call was successful, `state` will hold a buffer that has to be deallocated using `ykpiv_done(state)`. 
The error handling cases in the second for loop over `args_info.action_given` do this correctly.
**Example:**
https://github.com/Yubico/yubico-piv-tool/blob/53d7115b7106685ee91655f787fcd5fdff2ee1e6/tool/yubico-piv-tool.c#L2124
https://github.com/Yubico/yubico-piv-tool/blob/53d7115b7106685ee91655f787fcd5fdff2ee1e6/tool/yubico-piv-tool.c#L2139
https://github.com/Yubico/yubico-piv-tool/blob/53d7115b7106685ee91655f787fcd5fdff2ee1e6/tool/yubico-piv-tool.c#L2364

However, the error handling cases in the first for loop over `args_info.action_given` will directly return.
**Example:**
https://github.com/Yubico/yubico-piv-tool/blob/53d7115b7106685ee91655f787fcd5fdff2ee1e6/tool/yubico-piv-tool.c#L1970
https://github.com/Yubico/yubico-piv-tool/blob/53d7115b7106685ee91655f787fcd5fdff2ee1e6/tool/yubico-piv-tool.c#L1978

**Comment by qpernil** [comment]
Thanks a lot for your contribution, I have checked in a fix for this on master, and it will be part of the upcoming 2.1.0 release.

Cheers !
