### ISSUE TITLE
memory leak in yubico-piv-tool.c

### ISSUE THREAD

**Issue by invd** [Yubico/yubico-piv-tool#236]
In addition to #235, there are a number of memory leaks that happen through the `cmdline.c` getgenopt code.

Among them:
- multiple `malloc()` via `gengetopt_strdup()`
- `realloc()` via `update_multiple_arg()`
- multiple `malloc()` via `get_multiple_arg_token()`

After staring at the generated `cmdline.c` code for a while, I've tried a few workarounds and spent some time with `gdb` before finding the actual source of the problem in the `main()` in `yubico-piv-tool.c`.

Internally, the command line parser will 

1. call `cmdline_parser_init()` **twice** (initialize internal + external struct)
1. call `cmdline_parser_free()` **once** (to free it's internal `args_info` struct)

It is the job of the calling function - in this case the `main()` - to trigger the second `cmdline_parser_free()` once it is finished using the struct.

The struct is defined here:
https://github.com/Yubico/yubico-piv-tool/blob/d5a78951119c94bf232472900be74fdc651eb36e/tool/yubico-piv-tool.c#L1953

It will contain the allocated buffers after this call is successful:
https://github.com/Yubico/yubico-piv-tool/blob/d5a78951119c94bf232472900be74fdc651eb36e/tool/yubico-piv-tool.c#L1963

Correspondingly, `cmdline_parser_free(&args_info);` has to be called before `return` to correctly deallocate the buffers. _See the example program in the [gengetopt](https://www.gnu.org/software/gengetopt/gengetopt.html) documentation to confirm that this is intended._

Like #235, there is no practical impact of the leak, but fixing it will prevent leak warnings with tools like AddressSanitizer.

**Comment by qpernil** [comment]
This has been fixed in master. Thx for the great analysis and contribution !
