### ISSUE TITLE
file descriptor leak in yubico-piv-tool.c

### ISSUE THREAD

**Issue by invd** [Yubico/yubico-piv-tool#237]
The `test_signature([...])` function in `yubico-piv-tool.c` can leak the file descriptor of `input_file` due to insufficient error handling.

Function definition:
https://github.com/Yubico/yubico-piv-tool/blob/d5a78951119c94bf232472900be74fdc651eb36e/tool/yubico-piv-tool.c#L1547

Assignment of `input_file`:
https://github.com/Yubico/yubico-piv-tool/blob/d5a78951119c94bf232472900be74fdc651eb36e/tool/yubico-piv-tool.c#L1556

Leak position no.1:
https://github.com/Yubico/yubico-piv-tool/blob/d5a78951119c94bf232472900be74fdc651eb36e/tool/yubico-piv-tool.c#L1582

Leak position no. 2:
https://github.com/Yubico/yubico-piv-tool/blob/d5a78951119c94bf232472900be74fdc651eb36e/tool/yubico-piv-tool.c#L1590

I suggest replacing those `return false;` statements with `goto test_out;`.

As far as I can see, there is no practical impact on functionality or security during regular cli usage.

**Comment by qpernil** [comment]
This has been fixed in master. Thx for the contribution !
