### ISSUE TITLE
potential undefined behavior in _ykpiv_save_object()

### ISSUE THREAD

**Issue by invd** [Yubico/yubico-piv-tool#239]
During my fuzzing analysis, the UndefinedBehavior sanitizer reported an issue in the following line:
https://github.com/Yubico/yubico-piv-tool/blob/d5a78951119c94bf232472900be74fdc651eb36e/lib/ykpiv.c#L1750

>  ykpiv.c:1761:19: runtime error: null pointer passed as argument 2, which is declared to never be null 
> /usr/include/string.h:43:28: note: nonnull attribute specified here

_Note: the line number difference is due to local code changes._

According to my understanding, it can happen that `_ykpiv_save_object()` is called with an `indata` of `NULL`. 
It looks reasonable to catch this case before performing the `memcpy()`.

This issue was discussed with @nevun and has no known security impact.

**Comment by qpernil** [comment]
The code relies to memcpy with len == 0 being a no-op, which is usually true but is not guaranteed by the specification of memcpy. This has been fixed in master by adding a guard for the null case. Thx for the contribution !
