### ISSUE TITLE
PIN retries

### ISSUE THREAD

**Issue by aftershoq** [Yubico/yubico-piv-tool#24]
We have some older Yubikey NEOs (3.3.6) and PIV Tool v0.1.6 can change PIN/PUK retries. 

However, we cannot change the PIN/PUK retries on our Yubikey NEOs v3.4.2 using the PIV Tool v0.1.6. We have tried on both Windows and MAC tools and multiple Yubikeys of each version. We are using same command:

yubico-piv-tool.exe -a pin-retries --pin-retries 10 --puk-retries 10 -P xxxxxx - N yyyyyy

Thanks!

**Comment by klali** [comment]
There's a recent change in the neo so that setting pin retries requires the pin to be verified. If you add -a verify before -a pin-retries it should work.

**Comment by aftershoq** [comment]
Thanks for quick response. It works with "-a verify-pin" as suggested. Thanks again for help.
