### ISSUE TITLE
potential segfault in import_key() in yubico-piv-tool.c

### ISSUE THREAD

**Issue by invd** [Yubico/yubico-piv-tool#240]
This issue was found during fuzzing.

It appears that there are code paths & input files in `import_key()` that leave `private_key`` uninitialized when calling the following line:
https://github.com/Yubico/yubico-piv-tool/blob/d5a78951119c94bf232472900be74fdc651eb36e/tool/yubico-piv-tool.c#L390

This can lead to a segmentation fault on the NULL pointer in the following code position:
`AddressSanitizer: SEGV on unknown address 0x000000000000`

Debug information before _L390_ is reached:
```
(gdb) print private_key
$3 = (EVP_PKEY *) 0x0
```

As a workaround, I used
```C
    if(!private_key) {
      goto import_out;
    }
```

This issue was discussed with @nevun .

**Comment by qpernil** [comment]
This issue has been fixe in master. Thx for the contribution !
