### ISSUE TITLE
memory leak in ykpiv_util_generate_key() in lib/util.c

### ISSUE THREAD

**Issue by invd** [Yubico/yubico-piv-tool#241]
During analysis, I noticed that there is an incorrect free in libykpiv:

https://github.com/Yubico/yubico-piv-tool/blob/d5a78951119c94bf232472900be74fdc651eb36e/lib/util.c#L994-L995

In _L995_, it does not make sense to free `ptr_exp`. This is likely a copy paste error. 

Due to the program structure, `if(ptr_point)` and `if(ptr_exp)` are mutually exclusive, so effectively `_ykpiv_free(state, NULL);` is called. This is harmless since `_ykpiv_free()` will perform no action on null pointers.
As far as I can see, the only practical impact on the program is that `ptr_point` will stay allocated in cases where it should be deallocated, which causes a memory leak.

I've discussed this issue with @nevun .

**Comment by qpernil** [comment]
This issue has been fixed in master. Thx for the contribution !
