### ISSUE TITLE
PIV stands for Personal Identity Verification

### ISSUE THREAD

**Issue by burnett86** [Yubico/yubico-piv-tool#242]
The README says, "The Yubico PIV tool is used for interacting with the Privilege and Identification Card (PIV) application on a YubiKey". However, https://piv.idmanagement.gov/, says PIV stands for Personal Identity Verification. There is something called the USPIC (where the PIC stands for Privilege etc.). But that is not the same thing.

**Comment by qpernil** [comment]
This has been fixed in master, and will be included in the upcoming 2.1.0 release. Thanks for the contribution!
