### ISSUE TITLE
memory leaks via test_signature() in yubico-piv-tool.c

### ISSUE THREAD

**Issue by invd** [Yubico/yubico-piv-tool#243]
During analysis, I noticed that there are a number of cases where memory allocated via OpenSSL is not correctly deallocated again.

I've tracked down two cases to `test_signature()`:

**No. 1** 
https://github.com/Yubico/yubico-piv-tool/blob/1808edf3ed5da466562fd546616eb6b65f863773/tool/yubico-piv-tool.c#L1593-L1600

The message digest context is created (=allocted and initialized) via OpenSSL but never cleaned up.

Proposed solution within this segment:
```C
 EVP_MD_CTX_destroy(mdctx);
```
See the relevant [OpenSSL manpage](https://www.openssl.org/docs/man1.0.2/man3/EVP_MD_CTX_create.html) for documentation .

**No 2.**
https://github.com/Yubico/yubico-piv-tool/blob/1808edf3ed5da466562fd546616eb6b65f863773/tool/yubico-piv-tool.c#L1612

After this OpenSSL call succeeds, `pubkey` points to an `EVP_PKEY` structure that must be explicitly deallocated, see the [OpenSSL manpage](https://www.openssl.org/docs/man1.1.0/man3/EVP_PKEY_free.html). 

However, the responsible cleanup section does not touch it:
https://github.com/Yubico/yubico-piv-tool/blob/1808edf3ed5da466562fd546616eb6b65f863773/tool/yubico-piv-tool.c#L1673-L1680

I suggest a cleaner variable definition
```C
EVP_PKEY *pubkey = NULL;
```
and explicit cleanup in `test_out:`
```C
if(pubkey) {
  EVP_PKEY_free(pubkey);
}
```

**Comment by qpernil** [comment]
This issue has been adressed as the reporter recommends. Also plugged similar issues in test code. Thanks for the contribution !
