### ISSUE TITLE
POSIX packages listed to build differ from what's available on Debian

### ISSUE THREAD

**Issue by 05nelsonm** [Yubico/yubico-piv-tool#244]
The currently listed packages in the README for building from source differ from those available on Tails OS (Debian Buster):

Packages currently listed:
`autoconf automake libtool libssl pkg-config check libpcsc gengetopt help2man`

Packages I used:
`autoconf automake libtool libssl-dev pkg-config check libpcsclite-dev gengetopt help2man make`

 - `libssl` does not exist in the PM.
     - Would not build properly with already installed `libssl1.1` package.
     - Using `libssl-dev` worked.
 - `libpcsc` does not exist in the PM.
     - would not build properly with alternatively available `libpcsclite1` package.
     - Using `libpcsclite-dev` worked.
 - Needed to install `make` to build in accordance with README instructions.

**Comment by 05nelsonm** [comment]
See PR #245

**Comment by aveenismail** [comment]
The list of requirement is now updated
