### ISSUE TITLE
add extensions to selfsign-certificate

### ISSUE THREAD

**Issue by My1** [Yubico/yubico-piv-tool#246]
currently as far as at least the help goes there does not seem to be a way of adding any extensions to the the certificate, and it would be nice to have an option to do so

**Comment by qpernil** [comment]
To do that I would suggest using openssl with the pkcs11 engine and ykcs11. There is a 2.1 release upcoming, and this feature is not planned for it I'm afraid.

**Comment by qpernil** [comment]
I can also add that the upcoming 2.1 release will have a feature that adds the attestation certificate chain to a certificate request as extensions, which could then be used to ensure that the key in the request was generated on a YubiKey (and thus doesn't exist anywhere else)
