### ISSUE TITLE
YKCS module failure with Veracrypt 

### ISSUE THREAD

**Issue by Mahaaveer** [Yubico/yubico-piv-tool#247]
My goal is to access the certificate stored in Yubikey 4 to use as keyfile in veracrypt.
when i try to set up the token library in veracrypt, libykcs11-1.dll returns the error as specified module could not be found:

![VeraCrypt_2B3hRqbPyd](https://user-images.githubusercontent.com/8575912/82173208-ecf4e480-98bb-11ea-92d3-c5d682bde014.png)

However, i was able to use opensc-pkcs11.dll to view the files inside yubikey:
![VeraCrypt_Format_0i4GWNCrhB](https://user-images.githubusercontent.com/8575912/82173836-321a1600-98be-11ea-9979-60af3e503e33.png)

 but veracrypt could not access it and returns error as General error:
![VeraCrypt_Format_EjBmV1t2Gi](https://user-images.githubusercontent.com/8575912/82173864-478f4000-98be-11ea-947a-cd69f635137e.png)

What is the right way to implement this? Thanks!

**Comment by mouse07410** [comment]
Consider that certificates were designed to be public, and that presumably anybody would be able to get hold of your cert, load a smart card with it, and using it, get VeraCrypt decrypt your filesystem.

What Veracrypt is doing would be OK for dumb USB drives. Using a PIV (or OpenPGP) token like this is like driving nails with a microscope - possible, but neither smart nor cost-effective.

**Comment by Mahaaveer** [comment]
> 
> 
> Consider that certificates were designed to be public, and that presumably anybody would be able to get hold of your cert, load a smart card with it, and using it, get VeraCrypt decrypt your filesystem.
> 
> What Veracrypt is doing would be OK for dumb USB drives. Using a PIV (or OpenPGP) token like this is like driving nails with a microscope - possible, but neither smart nor cost-effective.

I agree, but i want to use it for another purpose... lets say i have python script running on startup which mounts a veracrypt container..... the mounting happens only when yubikey is plugged in as it holds the keyfile.

i am aware the design has its flaws but the idea is to "make certain folders available only if yubikey is plugged in"

any ideas how i could possibly implement this ? also, the data in question is not that sensitive to be worried about. 

just out of curiosity and "something is better than nothing" :)

**Comment by qpernil** [comment]
When I tested this on Windows for the 2.0.0 release the problem was that VeraCrypt couldn't load the ykcs11 dll (or it's dependencies). I verified this using pkcs11-spy, which can be downloaded from the opensc for Windows project. From it's log it was clear it failes to load ykcs11, and thus ykcs11 never even gets called. Why that is is a mystery to me. One theory I had was that there might be a conflicting openssl dll somewhere on the path, but thats only speculation. I also built a dummy pkcs11 dll with just enough functionality to allow VeraCrypt to load it, and with that it worked.

A final thought on this is that up until the upcoming 2.1 release we cross-compiled the Windows release on Linux, perhaps this has something to do with it as well. From 2.1 we support cmake using the Visual Studio build tools. We will test this again for that release.

**Comment by qpernil** [comment]
Regarding your error above with opensc-pkcs11 I think it happens because opensc-pkcs11 indicates that certain objects exists even though they do not contain any data. A YubiKey doesn't normally contain any data in the 3 objects your listing shows (Although it could if you have written to them)

**Comment by mouse07410** [comment]
If all you need is an unprotected for from Yubikey - then `pkcs15-tool --read-certificate 03` will give you that certificate in PEM format when Yubikey is inserted.

As to whether this whole approach is better than nothing - it's up to you. I have my opinion.

**Comment by Mahaaveer** [comment]
> 
> 
> Regarding your error above with opensc-pkcs11 I think it happens because opensc-pkcs11 indicates that certain objects exists even though they do not contain any data. A YubiKey doesn't normally contain any data in the 3 objects your listing shows (Although it could if you have written to them)

i tried calling the .crt file by token://slot/0/file/filename.crt and i cannot find the file. Again, there are those 3 objects of  crt file i added. how do i add data to those three files?

Thanks!

**Comment by Mahaaveer** [comment]
> 
> 
> If all you need is an unprotected certificate from Yubikey - then `pkcs15-tool --read-certificate 03` will give you that certificate in PEM format when Yubikey is inserted.
> 
> As to whether this whole approach is better than nothing - it's up to you. I have my opinion.

Thanks! will try this one

**Comment by qpernil** [comment]
To read/write data to PIV slots please see the following link:
https://developers.yubico.com/yubico-piv-tool/Actions/read_write_objects.html

**Comment by qpernil** [comment]
Regarding file names I think you need to use the exact filenames as listed, no extensions. Keep in mind that there aren't really any file names in the PIV application, they are just something that the PKCS11 implementation you use map the slot IDs to. And the URL format you use in VeraCrypt is specific to VeraCrypt.

**Comment by 0xWhoa** [comment]
I managed to solve it:
When attempting to load `libykcs11.dll` with Veracrypt, it is then looking for `libcrypto-1_1-x64.dll` and `libykpiv.dll` in `C:\Windows\System32\` folder but they don't exist there.
Copying those DLLs from `C:\Program Files\Yubico\Yubico PIV Tool\bin` to `C:\Windows\System32\` solved it for me.
I hope this helps.

**Comment by qpernil** [comment]
OK, to me that would indicate that VeraCrypt probably sets the search path for dependent libraries restrictively, for security reasons presumably. Thx for the info!

**Comment by photographer-mememe** [comment]
When I try copying the dll's from "Yubico PIV Tool\bin" to System32 and loading that into Veracrypt, it see's no slots/objects from the Yubikey 5 series. But using opensc-pkcs11.dll shows me Fingerprints, Facial Image, and Printed Information.
![Untitled-1](https://user-images.githubusercontent.com/24559868/153663636-cebdb42a-6b60-4c70-ab0a-d2a9953d1e61.gif)

**Comment by qpernil** [comment]
I think the above is based on the fact that the PIV spec says these objects are mandatory, and opensc-pkcs11 apparently always shows those objects when they are listed via the FindObjects pkcs11 API. The way it finds objects, and what labels it puts on them is up to the specific pkcs11 module, the objects have no names in PIV, only slot ids. libykcs11.dll will show objects based mainly on the objects actually being provisioned, but the full logic is rather complex, and also depends on the YubiKey model.

**Comment by qpernil** [comment]
I'm closing this issue now for lack of activity, and also that it would seem the fix has to be done by VeraCrypt.

**Comment by owenhayman** [comment]
Apologies for necroing this thread, but thought I would add a touch more context here on the initial issue for anyone who might encounter it in the future, as I too encountered this issue today.

@qpernil was right about the DLL search path being restricted - the code responsible for this restriction can be found in [src/Common/Dlgcode.c](https://github.com/veracrypt/VeraCrypt/blob/master/src/Common/Dlgcode.c#L3711). This restricts the DLL search path to the "C:\Windows\System32" directory.

For anyone who is interested, circumventing this restriction can be achieved by recompiling the VeraCrypt code with "[src/Common/Dlgcode.c](https://github.com/veracrypt/VeraCrypt/blob/master/src/Common/Dlgcode.c#L3712-L3714)" lines 3712, 3713, and 3714 removed, or the function pointers set to a nullptr. This will remove the restriction, expanding the search to include the current working directory, PATH, and other "normal" search paths. This in turn allows the application to find libykcs.dll's dependencies in the current working directory (ideal if using VeraCrypt portable & want to use yubikey with it).

Recompiling VeraCrypt is a massive PITA, however It is also possible to patch the offending instructions out of the "VeraCrypt-x64.exe" binary directly. The image below shows a low-level IL representation of the patch performed using [Binary Ninja](https://binary.ninja/):

![InitApp_patch](https://github.com/Yubico/yubico-piv-tool/assets/10144532/5f5dddf4-358c-455d-9160-02d17ce1db62)

This patch removes the Kernel32.dll "GetProcAddress" calls for "SetDllDirectoryW", "SetSearchPathMode", and "SetDefaultDllDirectories", setting the function pointers to nullptr instead, which is handled gracefully by the application.

The binary's built-in file integrity check function "VerifyModuleSignature" also needs to be patched in order for the executable to run without errors, as after patching, the file's digital signature will no longer match. The function can also be found in "[src/Common/Dlgcode.c](https://github.com/veracrypt/VeraCrypt/blob/44c9c077f379e65ef45952e1e78059cdec2fa36f/src/Common/Dlgcode.c#L1024)".

The image below shows an assembly-level representation of the patch:

![VerifyModuleSignature_patch](https://github.com/Yubico/yubico-piv-tool/assets/10144532/9390e330-f52f-4170-b77b-23b39a26ea67)

This patch forces the application to take a branch that always returns True. The branch taken can be found in the corresponding C code in "[src/Common/Dlgcode.c](https://github.com/veracrypt/VeraCrypt/blob/master/src/Common/Dlgcode.c#L1036)".

After patching the binary, VeraCrypt is able to locate and load the DLL's dependencies, and you can use the YubiKey suppled DLL without issues.

**Disclaimer:**

I am stupid. It is definitely not a good idea to patch a binary by hand that is responsible for complex and sensitive operations such as the encryption of files, partitions and operating systems. Please be careful. While the effects of this patch should not interfere with the rest of the program, this cannot be guaranteed. I do not recommend using a hand-patched VeraCrypt binary on information you don't mind losing. Yes I'm probably still going to use it myself anyway, like I said, I'm stupid lol.

**Resources:**

[Microsoft: secure-loading-of-libraries-to-prevent-dll-preloading-attacks](https://support.microsoft.com/en-us/topic/secure-loading-of-libraries-to-prevent-dll-preloading-attacks-d41303ec-0748-9211-f317-2edc819682e1)

[Microsoft: dynamic-link-library-search-order](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order)
