### ISSUE TITLE
Release v2.1.0

### ISSUE THREAD

**Issue by Justinette2175** [Yubico/yubico-piv-tool#255]
Hi there, 
Just looking for an update on expected release date for v.2.1.0. Seems like it would be nice to have.
Thanks!

**Comment by dainnilsson** [comment]
We're working hard, but still a couple of weeks away. Currently aiming for early July, sorry for the wait!

**Comment by aveenismail** [comment]
2.1.0 was released in July 2020. Closing this ticket
