### ISSUE TITLE
ssh-agent issues OSX yubico-piv-tool-2.1.0

### ISSUE THREAD

**Issue by jorgeelmundoso** [Yubico/yubico-piv-tool#258]
#### Setup
Operating System: MacOS Catalina 10.15.15
yubico-piv-tool: 2.1.0
openssh: OpenSSH_8.2p1, OpenSSL 1.1.1g  21 Apr 2020

#### Goal
I want to cache yubikey pin entry / touch, since i have to log into over 100 hosts in serial.
I used appropriate pin/touch policies.

#### Issue
I have setup my yubikey via:
```
ykman piv generate-key --algorithm=ECCP384 --pin-policy=ONCE --touch-policy=CACHED 9a public_key_9a.pem
ykman piv generate-certificate --valid-days=$((365*5)) --subject="cached" 9a public_key_9a.pem
```

I use openssh 8.2p1, ssh-agent, not the one coming with MacOS, and added my keys via
```
# workaround for ssh-agent error  `provider not whitelisted`
cp /usr/local/Cellar/yubico-piv-tool/2.0.0/lib/libykcs11.1.dylib /usr/local/lib/libykcs11_nolink.dylib 

ssh-add -s /usr/local/lib/libykcs11_nolink.dylib
 ```

If I try using ssh with the generated key loaded into ssh-agent i come until:
```
debug: /tmp/yubico-piv-tool-20200708-10391-1yjvr7k/yubico-piv-tool-2.1.0/ykcs11/ykcs11.c:1907 (C_FindObjects): Returning 1 objects, 0 remaining
debug: /tmp/yubico-piv-tool-20200708-10391-1yjvr7k/yubico-piv-tool-2.1.0/ykcs11/objects.c:519 (get_proa): For private key object 86, get
debug: /tmp/yubico-piv-tool-20200708-10391-1yjvr7k/yubico-piv-tool-2.1.0/ykcs11/objects.c:710 (get_proa): ALWAYS AUTHENTICATE
debug1: pkcs11_check_obj_bool_attrib: provider 0x7fa584c1ebe0 slot 0 object 86: attrib 514 = 0
Going to send 54 bytes in this go.
> 00 87 14 9a 36 .... (and so on)

```

Then when I touch the key it fails with:
```
Sign command failed with code 6982.
debug: /tmp/yubico-piv-tool-20200708-10391-1yjvr7k/yubico-piv-tool-2.1.0/ykcs11/mechanisms.c:299 (sign_mechanism_final): ykpiv_sign_data with key 9a failed: Authentication error
debug: /tmp/yubico-piv-tool-20200708-10391-1yjvr7k/yubico-piv-tool-2.1.0/ykcs11/ykcs11.c:2874 (C_Sign): sign_mechanism_final failed
C_Sign failed: 257
process_sign: ECDSA_sign returns 0
debug1: pkcs11_k11_free: parent 0x7fa584e05220 ptr 0x0 idx 1
process_sign_request2: sshkey_sign: error in libcrypto
```

If i use RSA2048 as instead of ECCP384 for the algorithm I get a similar error:
```
Sign command failed with code 6982.
debug: /tmp/yubico-piv-tool-20200708-10391-1yjvr7k/yubico-piv-tool-2.1.0/ykcs11/mechanisms.c:299 (sign_mechanism_final): ykpiv_sign_data with key 9a failed: Authentication error
debug: /tmp/yubico-piv-tool-20200708-10391-1yjvr7k/yubico-piv-tool-2.1.0/ykcs11/ykcs11.c:2874 (C_Sign): sign_mechanism_final failed
C_Sign failed: 257
debug1: pkcs11_k11_free: parent 0x7fc225d1d380 ptr 0x0 idx 1
process_sign_request2: sshkey_sign: error in libcrypto
```

I had it working with RSA2048 on MacOS Mojave and yubico-piv-tool 2.0.0
I cant reproduce it since i can't downgrade to yubico-piv-tool 2.0.0 ( brew has no prior version for it)
and downgrading Catalina would be too risky and time intensive.

I attached the logs from the failed ECCP384 key authentication attempt.

[ECCP384_auth.log](https://github.com/Yubico/yubico-piv-tool/files/4902130/ECCP384_auth.log)

**Comment by aveenismail** [comment]
Hi  @ jorgeelmundoso

Sorry that it had taken so long to answer.

Unfortunately, the authentication requirement (tex PIN and touch policy) is hard coded in the YKCS11 module and is not effected by the configured PIN and touch policy. Thus in YKCS11, the key in slot 9c will always require PIN authentication when signing or decrypting but all the other keys on the other slots will use the cached PIN.

Making the authentication policy in YKCS11 reflect the configured policy is under consideration, but still not part of a planed future release.

**Comment by aveenismail** [comment]
Sorry again, I may have misunderstood the issue. 

Did it take time before the the error showed up? Was the YubiKey blinking? It could be that it was expecting a touch, not a PIN, and that could be a different setting

**Comment by mouse07410** [comment]
In my case, touch is not programmed. So, it cannot expect or wait for touch.

**Comment by qpernil** [comment]
Closing this issue now for lack of activity. Please reopen as needed.
