### ISSUE TITLE
pkgconfig path is hardcoded to /usr/lib/pkgconfig instead of honoring LIB_SUFFIX

### ISSUE THREAD

**Issue by Jakuje** [Yubico/yubico-piv-tool#259]
This worked fine in Fedora in previous version, but not with cmake.

**Comment by Jakuje** [comment]
Workaround is to provide different `YKPIV_INSTALL_PKGCONFIG_DIR` on cmake commandline (example from my Fedora package):
```
cmake . -DYKPIV_INSTALL_PKGCONFIG_DIR=%{_libdir}/pkgconfig/
```
But it is very far from perfect and it should be fixed in yubico-piv-tool cmake files to work out of box.

**Comment by aveenismail** [comment]
Just committed a fix to set the default pkgconfig directory to ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/pkgconfig

Would that be sufficient?

**Comment by Jakuje** [comment]
It should work. Can you point me out to the particular commit that fixes it so I can verify?

**Comment by aveenismail** [comment]
What is on master branch now includes the fix. The fix was done in 2 commits, the second of which is: https://github.com/Yubico/yubico-piv-tool/commit/283e2e7c3af7138752f1df181bdce5fabd53ed1b

Thanks in advance for verifying

**Comment by Jakuje** [comment]
Thank you. It looks like it builds fine with the above two patches and without the workaround I use. I think you can close this issue.

**Comment by aveenismail** [comment]
Great. Thank you.
