### ISSUE TITLE
[v 2.1] symbol lookup error: yubico-piv-tool: undefined symbol: open_file

### ISSUE THREAD

**Issue by AngusMcGyver** [Yubico/yubico-piv-tool#260]
Hey there,

after upgrade from version **2.0.0-2\~ppa1\~xenial1** to **2.1.0\~ppa23\~xenial1**
i got the following error:

> $ yubico-piv-tool -a status
> yubico-piv-tool: symbol lookup error: yubico-piv-tool: undefined symbol: open_file

and

> $ /usr/bin/yubico-piv-tool -a change-pin
> /usr/bin/yubico-piv-tool: symbol lookup error: /usr/bin/yubico-piv-tool: undefined symbol: read_pw

the system is a **Ubuntu Xenial 16.04 LTS** with this ppa:
> deb http://ppa.launchpad.net/yubico/stable/ubuntu xenial main

downgrade doesn't work, can't find the deb package for version 2.0 on the server:
> http://ppa.launchpad.net/yubico/stable/ubuntu/pool/main/y/yubico-piv-tool/

What can i do to use the piv tool again?

**Comment by OliverO2** [comment]
On Ubuntu 20.04 LTS (focal):
```
# yubico-piv-tool
yubico-piv-tool: symbol lookup error: yubico-piv-tool: undefined symbol: get_touch_policy
```
Package version and architecture:
```
yubico-piv-tool 2.1.0~ppa22~focal1 amd64
```

**Comment by a-dma** [comment]
ping @aveenismail in case you missed this

**Comment by aveenismail** [comment]
@a-dma I have missed this. Thank you for the ping

@AngusMcGyver and @OliverO2 I'll look into this today

**Comment by OliverO2** [comment]
@a-dma Thanks for responding. Will be ready to test once you have updated the package in the ppa.

**Comment by mhalano** [comment]
Same problem here:
yubico-piv-tool: symbol lookup error: yubico-piv-tool: undefined symbol: get_touch_policy
Using Ubuntu 20.04 LTS Focal

**Comment by mhalano** [comment]
I did a quick execution and command is working as expected.

**Comment by OliverO2** [comment]
@aveenismail 
Running `yubico-piv-tool` without arguments and `yubico-piv-tool -a status` now works as expected. Thanks for fixing it!

**Comment by AngusMcGyver** [comment]
i can confirm it works again. thanks for the fix.
