### ISSUE TITLE
Missing cmdline.c

### ISSUE THREAD

**Issue by martinscholz83** [Yubico/yubico-piv-tool#263]
When trying to build on windows i got this error
```
CMake Error at tool/CMakeLists.txt:56 (add_executable):
  Cannot find source file:
    cmdline.c
  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
CMake Error at tool/CMakeLists.txt:56 (add_executable):
  No SOURCES given to target: yubico-piv-tool
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
When looking at [gitignore](https://github.com/Yubico/yubico-piv-tool/blob/master/.gitignore#L76)it is ignored. Is this correct?

**Comment by nevun** [comment]
Please look at how we build for windows in our Github Action: https://github.com/Yubico/yubico-piv-tool/blob/master/.github/workflows/windows_build.yml

The tool `gengetopt` is not readily available for Windows so we generate the missing files using linux first, and then build with the generated files on Windows.

Easiest for you if you really want to build it yourself is to download the release source-tarball from here which includes the generated files:  https://developers.yubico.com/yubico-piv-tool/Releases/

Sorry for the inconvenience.

**Comment by martinscholz83** [comment]
May i can ask you another question? What is the purpose of `ykpiv_util_read_mscmap` function? Is a call to this function returns a `cmapfile` like on windows the PIV minidriver is presenting you?

**Comment by nevun** [comment]
There are some shared code between these projects. Calling this function without having the Yubico Smart Card Minidriver set up and running is probably not going to bring much. I am however not that familiar with this area.
