### ISSUE TITLE
yubico-piv-tool 1.4.2 doesn't check USB labels properly

### ISSUE THREAD

**Issue by bmomjian** [Yubico/yubico-piv-tool#266]
I am using yubico-piv-tool 1.4.2-2 on Debian 10/Buster.  It uses libccid 1.4.30-1.  That version of libccid includes USB labels for the Yubico hardware listed below:

```
Yubico Yubikey NEO OTP+CCID
Yubico Yubikey NEO CCID
Yubico Yubikey NEO U2F+CCID
Yubico Yubikey NEO OTP+U2F+CCID
Yubico YubiKey CCID
Yubico YubiKey OTP+CCID
Yubico YubiKey FIDO+CCID
Yubico YubiKey OTP+FIDO+CCID
```

Notice that the last four entries show as YubiKey (capital K), while the previous ones show with lower-case K.  The upper-case K causes yubico-piv-tool 1.4.2-2 to fail with:

```
$ yubico-piv-tool -v -a verify-pin -P 000000
skipping reader 'Yubico YubiKey OTP+FIDO+CCID 00 00' since it doesn't match 'Yubikey'.
error: no usable reader found.
Failed to connect to reader.
```

Modifying the file to use lower-case K allows yubico-piv-tool to work.  I asked the libccid maintainer to use lower-case K, but they said Yubico has registered the devices with upper-case K, so it is best for the tools to be modified to use upper or lower-case K, or to use the vendor id.  You can see the details of the discussion here, https://github.com/LudovicRousseau/CCID/issues/74

Other Yubico tools might also need updating for this.

**Comment by bmomjian** [comment]
Looking at the docs, it looks like you can control the USB reader label it checks for:

 ` -r, --reader=STRING      Only use a matching reader  (default=`Yubikey')`

I suggest it default to check for upper and lower-case K.  It looks like the 2.0 version needs the same change.

**Comment by nevun** [comment]
Hi!

The latest release of `yubico-piv-tool` is `2.1.1`. 
I believe the reader match was changed to be case-insensitive in 2018 with this commit:
https://github.com/Yubico/yubico-piv-tool/commit/6e51db8c80f538f1cb6a88dfd6ffc93122f11912

There are multiple CVEs listed for older versions of the yubico-piv-tool so I do recommend running 2.1.1 anyhow.

Unfortunately debian have not backported or updated their `yubico-piv-tool` and going from 1.4.2 to  2.1.1 is not that easy. If you were on Ubuntu you could use our PPA to download a newer version: https://support.yubico.com/support/solutions/articles/15000010964-enabling-the-yubico-ppa-on-ubuntu

**Comment by bmomjian** [comment]
OK, great to know. I have modified the USB file for my version of Debian and hope to use the newer version of yubico-piv-tool at some time in the future.  Thanks.
