### ISSUE TITLE
Phantom SSH key

### ISSUE THREAD

**Issue by deni** [Yubico/yubico-piv-tool#267]
Hi,

I've reset my PIV applet using
`yubico-piv-tool -a reset`

but
`ssh-keygen -D /usr/local/lib/libykcs11.dylib -e`

keeps returning 1 SSH key!

How can I find out where this is coming from — it is driving me crazy.

Thanks,
Denis

**Comment by qpernil** [comment]
You are probably getting the attestation key, which is exposed through the pkcs11 api as a normal key/certificate. Unfortunately the ssh-keygen command doesn't show you which key is which so to speak. Attestation keys are not affected by a reset. (But you can import/generate your own.

**Comment by deni** [comment]
Thanks - that makes good sense. Is there a good way of getting an overview of all the keys on the device?

I find it to be a reoccurring problem that so many slots make it hard for me to get an overview - something listing everything (even beyond PIV) would be awesome.

And I guess this is also kind of a PIV thing but is there anyway to tell which keys are which when listing then through SSH?

**Comment by deni** [comment]
Also, let me add that I decided to remove the attestation key from the device despite knowing that I cannot recover that functionality. I issued:

```
yubico-piv-tool -a delete-certificate -s f9
```

Now

```
ssh-keygen -D /usr/local/lib/libykcs11.dylib -e
```

No longer returns any keys 😄

**Comment by qpernil** [comment]
That command actually just writes an empty certificate to the certificate object that corresponds to the key slot. The key is still there. You can still see the key object through the ykcs11 pkcs11 api. In PIV there is a key object and a certificate object corresponding to it for each slot. There is no PIV command to delete a key. If you want to remove a key you have to generate or import a new key to that slot. Typically also importing a corresponding certificate, but may not be important if you just want to get rid of a key. PIV doesn't enforce that they match ...

**Comment by qpernil** [comment]
I realize it's too late now, but you could have saved the certificate and restored it later to enable attestation again, if you left the key in place. (Which you did with the above command).

**Comment by qpernil** [comment]
To clarify a bit ... We are able to detect the key without the certificate because of relatively recent and proprietary additions to the YubiKey PIV application that allows us to get an attestation or metadata about keys regardless of the certificate slot. Without those features you can only tell that you have a key by trying to use it. So you can't read out the public key other than by reading the cert (and hoping it matches, i.e. that the device is properly provisioned).
