### ISSUE TITLE
yubico-piv-tool import SSH certificate 

### ISSUE THREAD

**Issue by mcarrer** [Yubico/yubico-piv-tool#269]
All, I am trying to use a YubiKey 5C with PIV and SSH Certificates.
I created an SSH CA, an SSH user's identity, and signed the user's public key with the CA.

```
ssh-keygen -t rsa -b 2048 -f ssh_ca_key -C CA -P ""
ssh-keygen -t rsa -b 2048 -f user_key -C "john.doe" -P "" -m PEM
ssh-keygen -s ssh_ca_key -I john.doe -n acme user_key.pub
```

Then, I imported the user's private key into the YubiKey.
```
> yubico-piv-tool -s 9a -a import-key -i user_key --pin-policy=never
Successfully imported a new private key.
```

Finally, I tried to import the user's SSH certificate into the YubiKey but none of the following options worked.
```
> yubico-piv-tool -s 9a -a import-certificate -i user_key-cert.pub
Failed loading certificate for import.

> yubico-piv-tool -s 9a -a import-certificate -K SSH -i user_key-cert.pub
Unknown key format.
```

My ultimate goal is to have the SSH CA public key in the .ssh/authorized_keys file on the remote server as a cert-authority and then login via SSH through the following:

```
ssh -I PATH/libykcs11.so user@remoteserver
```

Is the SSH key format supported by the current yubico-piv-tool? If not, is the support in roadmap?
Once the certificate is imported, will the SSH YKCS11 module support it during the authentication process?

Are they other ways to achieve an SSH certificate authentication with the key and the cert stored in the YubiKey?

I am using yubico-piv-tool version 2.1.1, YubiKey firmware version 5.2.6.

**Comment by mcarrer** [comment]
Any comment on this?

**Comment by a-dma** [comment]
Hi, there is no support for SSH certificates in yubico-piv-tool, the `-K SSH` option is only supported for keys.

While there is no technical limitation for storing the certificate in that format I'm not aware of anything that would be able to use it. YKCS11 and PKCS#11 in general only understands X.509 certificate (unless you count WTLS).

A modified SSH agent that speak "PIV" directly through libykpiv (or equivalent) would be needed.

**Comment by qpernil** [comment]
I would point to the following, which is not exactly what you're asking for but might serve as a starting point.
https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html

In short, you can't use ssh certs in PIV on the YubiKey through Yubico support libraries as they only support X.509 certificates at present. But storing the certificate on the YubiKey is normally not needed as it is public information.

**Comment by qpernil** [comment]
Here is better resource for SSH certificates: https://developers.yubico.com/PIV/Guides/SSH_user_certificates.html
Closing the issue now, feel free to submit a new one if needed.
