### ISSUE TITLE
User login problem with Yubikey after un-plugged and re-plugged in (even with re-initialization)

### ISSUE THREAD

**Issue by alpheuswinterborn** [Yubico/yubico-piv-tool#270]
[iaik.zip](https://github.com/Yubico/yubico-piv-tool/files/5450752/iaik.zip)

I am using IAIK PKCS#11 wrapper
(Reference: https://jce.iaik.tugraz.at/product-category/pkcs11+evaluationversions/)

The situation I am creating is that the PKCS#11 module is initialized, the user is able to login using PKCS#11 user PIN.

Then, the Yubikey is plugged out and re-plugged in. Further login as user produces the error CKR_PIN_INCORRECT. 
Even if the module is re-initialized after re-plugged in. The user logins with the same error CKR_PIN_INCORRECT.

The attached zip file contains the code to re-produce the problem. Comments are indicated as to when the Yubikey is unplugged and re-plugged in, when the user logon with the error: CKR_PIN_INCORRECT.

Thank you.

**Comment by qpernil** [comment]
libykcs11 does not reconnect removed YubiKeys. PR #271 Should fix this
