### ISSUE TITLE
Generating key pairs using pkcs11-tool

### ISSUE THREAD

**Issue by johughes99** [Yubico/yubico-piv-tool#278]
I  have just purchased a Yubikey 5 NFC to do some testing and trying to generate various key pairs on it.

So I have tried:

`pkcs11-tool --module /usr/local/lib/libykcs11.so --login --login-type so --keypairgen --id 4 --key-type EC:prime256v1
Using slot 0 with a present token (0x0)
Logging in to "YubiKey PIV #13679975".
Please enter SO PIN: 
error: PKCS11 function C_Login failed: rv = CKR_USER_PIN_NOT_INITIALIZED (0x102)
Aborting.
`  
Understanding that for this Yubikey only the SO can generate key pairs. 

Therefore pkcs11-tool believes the user's PIN has not been initialized - so I try

`johughes@ubuntu:~$ pkcs11-tool --module /usr/local/lib/libykcs11.so --login --login-type so --so-pin 123456 --init-pin
Using slot 0 with a present token (0x0)
error: PKCS11 function C_Login failed: rv = CKR_USER_PIN_NOT_INITIALIZED (0x102)
Aborting.
`
Hence doesn't appear to be a way to init the user's PIN using pkcs11-tool - at least on a Yubikey

So my question - in around about way - what do I need to do using yubico-piv-tool to init the users PIN so that pkcs11-tool recognizes this.

As an aside - I did yubico-piv-tool -a change-pin xxxxxx successfully.  And I thought this was changing (and setting) the user PIN.

I'm using the latest yubico-piv-tool and opensc 0.21rc2

**Comment by johughes99** [comment]
In digging into it further - and writing some code to see what is happening I got the following when trying to logon as a SO using C_Login

`debug: /home/johughes/Downloads/yubico-piv-tool-2.1.1/ykcs11/token.c:341 (token_login): Device configuration invalid, no PIN-protected MGM key available`

**Comment by qpernil** [comment]
The SO pin maps to the admin key, which is normally a 24-byte 3DES key in PIV. This should be specified as a 48 byte string containing the hex-encoded adm key. There is also an alternate way to set up a YubiKey where this admin key is stored in a PIN-protected slot on the key, allowing the library to authenticate using PIN, read the admin key and then authenticate with this stored admin key, while the user only knows the PIN. When set up like that the admin key will be randomly generated. 
The library will try to use this mode if you specify a normal-length PIN (6-8 characters) when trying to log in as SO. In your case there was no admin key stored in the PIN-protected slot, hence the error message. What you need to do is to use the 48-character 'PIN' that encodes your admin key. By default this key is 010203040506070801020304050607080102030405060708 (in hex).

**Comment by qpernil** [comment]
The initial error message, CKR_USER_PIN_NOT_INITIALIZED, was because of the missing stored adm key (assuming you used a pin of length 6-8 characters).

**Comment by qpernil** [comment]
To explain a little further, the adm key is not really a PIN, it is a 3DES key used to perform a challenge-response authentication with the yubikey. Hence you cannot find out the value of it by spying on the USB communications. This key is what allows you to  create or delete other keys in PIV. To work around this behavior and allow all operations with the PIN Yubico support libraries allow you to set it up with the admin key stored in the YubiKey itself in a PIN-protected slot.

**Comment by johughes99** [comment]
Its ok - I got around it - by using YubiKey Manager and  then resetting the token plus  changing the PIN. PUK and MGM - including making sure the MGM was PIN protected.
