### ISSUE TITLE
Segmentation error on finding objects with CKA_KEY_TYPE

### ISSUE THREAD

**Issue by johughes99** [Yubico/yubico-piv-tool#279]
I was trying to find various objects on the token with the CKA_ID specified in the attribute template when calling C_FindObjectsInit.  This works fine.

But every time I tried to specify CKA_KEY_TYPE as CKK_RSA I got a segmentation error.

**Comment by qpernil** [comment]
Would you mind providing a minimal code sample to trigger this problem? 
Thx

**Comment by johughes99** [comment]
I will get something to you for tomorrow morning.

**Comment by johughes99** [comment]
Here is the simple code test.  You will have to edit the source to the path of the .so and of course the PIN if you are not using the default.

Also note that searching using CKA_EC_PARAMS does not appear to work - although looking more into this. When running in debug mode I cant see and DBG output that shows it is looking at the CKA_EC_PARAM attribute when processing attributes

[main_test.zip](https://github.com/Yubico/yubico-piv-tool/files/5617720/main_test.zip)

**Comment by johughes99** [comment]
Finding object via CKA_EC_PARAMS does work.  Having reset the device I had forgotten to populate it with some EC key pairs

**Comment by qpernil** [comment]
If you could run your test with the environment variable YKCS11_DBG=1 it would be great as well.

**Comment by qpernil** [comment]
I found the problem - You are passing in the value CKK_RSA to the template, it should be a pointer to a CK_ULONG holding that value. My compiler doesn't warn about that by default.

**Comment by johughes99** [comment]
[debug.log](https://github.com/Yubico/yubico-piv-tool/files/5618486/debug.log)

Here it is.  Following PIV reset i have added 1 x RSA-1024 key pair and another RSA-2048 key pair.  The token also have a NIST P-256 and P-384 key pair on it.  Although the failure also occurred before I put on the EC key pairs.

What is very strange though is when I did a pkcs11-tool --module /usr/local/lib/libykcs11.so --login --login-type so -O

Most of the objects talk about the key being retired.

So for instance the RSA-2048 I generated on the devie says:

`Public Key Object; RSA 2048 bits
  label:      Public key for Retired Key 8
  ID:         0c
  Usage:      encrypt, verify
  Access:     local
`
But I actually specified a totally different label.. So YKCS11 ignored the attribute I supplied and added a new one of its own choosing

**Comment by johughes99** [comment]
You are right - silly mistake.

**Comment by qpernil** [comment]
ykcs11 tries to map the pkcs#11 spec with the PIV spec that governs hot the actual YubiKey PIV application behaves. The YubiKey PIV application support 20 'retired key' slots in addition to the 4 normal PIV slots. Not the old YubiKey NEO though.
The PIV application only has 2 types of objects - private keys and certificate slots. Each of the 24 slots is actually a pair of (private key, certificate slot). Keys can be generated or imported, certificate slots can be written and read. There are also some more slots for non-certificate use, and some of those are PIN-protected. There is no direct way to store labels, so they are hardcoded in the supporting library instead. The attribute CKA_ID is used to determine which slot an object belongs to. For each certificate slot we make a certificate, a public key and a data object available, and for the private key there is a private key object. All four object for a given slot pair has the same CKA_ID, and the value of CKA_ID is a single byte matching the ids used by the pkcs## modulein the opensc package. So to generate a key in a certain slot you specify the proper CKA_ID. There will also be an extra certificate object per key, containing a certificate for that public key signed by the attestation key on the YubiKey. These are generated on the fly so will be different each time you open the first session on a slot.

**Comment by qpernil** [comment]
See https://developers.yubico.com/yubico-piv-tool/YKCS11/ for more on this mapping.

**Comment by qpernil** [comment]
Another thing that I'd like to point out is that we create attestations for all keys when the first session is opened on a slot. Thus it will take some time to do this, and that time grows with the number of keys in PIV. (Creating an attestation means signing a certificate in the YubiKey). To avoid this delay in a long-living application it should avoid closing all sessions to a slot. Conversely it should close all sessions to re-read the contents of the key.
