### ISSUE TITLE
piv-tool --serial vs ykman list documentation on conversion missing

### ISSUE THREAD

**Issue by Torxed** [Yubico/yubico-piv-tool#284]
Hi.

I'm guessing the serial from `pkcs15-tool --list-info --reader 0`/`piv-tool --serial --reader 0` is the base for what `ykman list` gives out. But finding documentation anywhere on Yubico's documentation resources appears to be impossible.

So I'm requesting some clarification and/or update to the documentation on how to convert between these two formats.
The reason is that some command-line executions require the `piv-tool` but when many yubikey's are inserted you need to verify which reader contains the correct `serial` device. And that requires converting between the formats.

I can give more detail on the backround if needed, but bottom line is. How do you get the hardware serial printed on the yubikey from `piv-tool` and how do you ensure that you're working against the same/correct device? The FIDO serial in ykman returns the int in bytes where as the serial from piv-tool is taken some where else.

**Comment by dainnilsson** [comment]
Are you asking about `piv-tool` from OpenSC? This repository is for the Yubico specific tool `yubico-piv-tool`, which is not the same thing. I don't know if the OpenSC tools are able to read out the serial number of a YubiKey.

**Comment by Torxed** [comment]
I assumed (mistakenly) that `piv-tool` was an alias to this repo. I now
assume that this tool has this support then and will investigate :)

**Comment by Torxed** [comment]
Closing this as the tool was not an alias.
