### ISSUE TITLE
No update information included with update

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Yubico/yubico-piv-tool#285]
I managed to find [release notes on your website](https://developers.yubico.com/yubico-piv-tool/Release_Notes.html). Yet, you are not giving change logs that `apt-listchanges`, or, say, Mint's Update Manager, can read. Thereby - by forcing the user to hunt for a website - you undo one of the good things about Linux! Still, perhaps it was just a temporary omission.

EDIT: I should say that I am using this PPA: `deb http://ppa.launchpad.net/yubico/stable/ubuntu focal main`

**Comment by qpernil** [comment]
This issue has been fixed, closing.
