### ISSUE TITLE
No ability to target a specific Yubikey with more than one Yubikey connected.

### ISSUE THREAD

**Issue by arealpersonforreallyreal** [Yubico/yubico-piv-tool#287]
Example scenario:
Admin logs into workstation with PIV profile of their admin Yubikey (Yubikey A).  Admin is charged with assisting the provisioning of, or clearing of, a second key (Yubikey B).

Admins/power-users need the ability to command yubico-piv-tool to target a specific key for commands/actions using a unique attribute such as the Yubikey Serial Number in a predictable, controllable, and scriptable way.

Thank you for your attention!

**Comment by mouse07410** [comment]
I support this enhancement request.

**Comment by qpernil** [comment]
You can use the -r to specify which PCSC reader to use, it will look for the string you specify within the actual reader name.

**Comment by qpernil** [comment]
And you can use something like
pkcs11-tool --module /usr/local/lib/libykcs11.dylib --list-slots
to list the available slots

**Comment by qpernil** [comment]
Of you have PCSC reader names where one is a substring of the other (such as foo and foo01) you can request an exact match by prefixing the reader name with '@', i.e @foo in the example above. Without the '@' you could get either one depending on which one is listed first by the PCSC subsystem.

**Comment by qpernil** [comment]
And a heads-up: Sometimes the PCSC reader is locked by other things in the system, ykcs11 will then list that slot as empty, and yubico-piv-tool will fail to use that reader. This is true even of the other application is not using PIV, as the lock is on the PCSC reader level.

**Comment by aseigler** [comment]
Agreed this functionality is already present in the yubico-piv-tool directly.  You can `yubico-piv-tool -alist-readers` to list available readers, then use the `-r` option as described to take desired action on specific attached reader.

**Comment by qpernil** [comment]
Closing this issue now as it was answered, please submit a new request if needed.
