### ISSUE TITLE
Silent drop of option "touch-policy=cached" for action "set-mgm-key"

### ISSUE THREAD

**Issue by cyrilchristin** [Yubico/yubico-piv-tool#289]
####   > _Low Priority / Low Impact_ <

### Issue / Bug
The action **"set-mgm-key" will accept the invalid "touch-policy" set to "cached"**, for example:
```
# yubico-piv-tool.exe -v 10 --key=%DEFAULTKEY% -a set-mgm-key -n %DEFAULTKEY% --touch-policy=cached
Connect reader 'Yubico Yubikey 4 OTP+U2F+CCID 0' matching 'Yubikey'.
Authenticating since action 'set-mgm-key' needs that.
Successful application authentication.
Now processing for action 'set-mgm-key'.
Successfully set new management key.
Disconnect card #0000000.
```
However, in reality **the tool has just configured device management key with a "touch-policy" set to "never"** without giving us any indication that our "touch-policy" was silently ignored!

This can be tested by re-running the above command, _which will not request any touch confirmation_.

### Situation / Background
From the [Yubico developers website](https://developers.yubico.com/PIV/Introduction/Yubico_extensions.html), the PIV extension for "Set management key [0xff]" confirms that **per design there is no "cached" policy**, only "none [0xff]" and "required touch [0xfe]" exists.

Upon review of the tool code, we can see this is correctly implemented in _yubico-piv-tool.c/ykpiv.c_, where the only valid argument for "args_info.touch_policy_arg" is "touch_policy_arg_always", anything else will result in "0" aka "never":
https://github.com/Yubico/yubico-piv-tool/blob/4b8a22d59013491582ddc446beece1da2513d1b9/tool/yubico-piv-tool.c#L2281
https://github.com/Yubico/yubico-piv-tool/blob/63931a894a7af22fd038863f2b54386f480982ec/lib/ykpiv.c#L1004-L1013

### Solutions / Discussion
When a user sets the "touch-policy" argument, _**it implies they intend to configure a non-default "touch-policy"**_, aka not "never".

Therefore I see two solution paths on the tool code perspective:

> Additional checks for the "touch-policy" argument upon action "set-mgm-key" indicating that "cached" is not a valid option.

_OR_

> Consider the "touch-policy=cached" argument upon action "set-mgm-key" as "touch-policy=always" and display a warning message to the output.

Regarding the tool --full-help / documentation perspective I would recommend updating the [manual(s)](https://developers.yubico.com/yubico-piv-tool/Manuals/yubico-piv-tool.1.html) to better indicate the valid "touch-policy" options upon action "set-mgm-key" are "always" or "never".

**Comment by qpernil** [comment]
Sorry for the slow response to this issue. The latest release contains a fix according to your first option, i.e. it now indicates that 'cached' is not valid. Closing this issues as solved now.
