### ISSUE TITLE
Use PIN to derive the management key

### ISSUE THREAD

**Issue by jtyr** [Yubico/yubico-piv-tool#29]
How can I initialize Yubikey to use PIN to derive the management key with `yubico-piv-tool` like it's possible with `yubikey-piv-manager`? I have found some [description](https://developers.yubico.com/yubikey-piv-manager/PIN_and_Management_Key.html) (the bottom of the page) but I'm not sure whether `yubico-piv-tool` supports it. I can generate the key:

```
python2 -c "from Crypto.Protocol.KDF import PBKDF2; print ''.join(x.encode('hex') for x in PBKDF2('my_pin', 'my_salt', 24, 10000))"
```

but I don't know how to save the salt on the Yubikey to indicate that the PIN should be used to derive the management key.

**Comment by klali** [comment]
There's (currently?) no support in the yubico-piv-tool for the derived keys and similar of yubikey-piv-manager. Even if you do the derivation by hand there's no good way of writing the object with salt etc.

If you want to script the setup of this my best guess is to use the classes from yubikey-piv-manager from a python script.

**Comment by jtyr** [comment]
Thanks for the explanation. Please could we keep this issue open and turn it into a feature request?

**Comment by trinitronx** [comment]
@klali:  Hmm... So the old tool allowed initializing Management key derived from PIN, but new tool does not?

How exactly does the user unblock a Yubikey initialized in this way without knowing the derived Management key?

**Comment by trinitronx** [comment]
I see in this help article ([yubikey-piv-manager: PIN and Management Key][1]) that the process is discussed:

> Technical description of Key derivation from PIN
> 
> When choosing to use a Management Key derived from the PIN, the following takes place:
> 
> A random 8-byte SALT value is generated and stored on the YubiKey.
> 
> The derived Management Key is calculated as PBKDF2(PIN, SALT, 24, 10000).
> 
> The PBKDF2 function (described in RFC 2898) is run using the PIN (encoded using UTF-8) as the password, for 10000 rounds, to produce a 24 byte key, which is used as the management key.  Whenever the user changes the PIN this process is repeated, using a new SALT and the new PIN.

It is unclear how to retrieve the 8-byte salt value stored on the key without a version of yubikey-piv-manager that supports this Management Key mode.

I'm trying to recover a my yubikey after mistyping PIN too many times (oops!).  However, I realized that I had no PUK saved, and that it was set up in PIN as Management Key mode (another oops!).  The PUK shows as `blocked`, and the only option in Yubikey PIV Manager app is `Reset device`.

I see that `yubico-piv-tool` has option `unblock-pin`, but it only appears to work with PUK 😨 

The article states that PUK is disabled when in this mode, further making things sound like it's unrecoverable:

> The PUK can be used to reset the PIN if it is ever lost or becomes blocked after the maximum number of incorrect attempts. Setting a PUK is optional. If you use your PIN as the Management Key, the PUK is disabled for technical reasons, explained in a later section. The requirements and restrictions of the PUK are the same as for the PIN (see above). If PIN complexity is enforced, the same rules are applied to the PUK. If the PUK ever becomes blocked, either by deliberately choosing to block it or by giving the wrong PUK value 3 times, it can only be unblocked by performing a complete reset

[1]: https://developers.yubico.com/yubikey-piv-manager/PIN_and_Management_Key.html

**Comment by dainnilsson** [comment]
Unless I'm misunderstanding something you're saying that both the PIN and PUK are blocked, but you know the correct value for the PIN? You could manually derive the management key from the PIN and the salt (which could be read off the key using a script), but it probably wouldn't do you any good, as just the management key alone won't allow you to reset or change the PIN or PUK, so your certificates will still be unusable.

I think the only solution here is to do a full reset and re-generate/import certificates and keys.

**Comment by trinitronx** [comment]
@dainnilsson: Yes, I had set up with the mode which derives from PIN.  I do know it, but mistyped too many times by accident.  So I can derive it knowing the salt, but finding it is the issue.

Perhaps I misunderstand the reason for using Managment Key versus PUK?  My assumption was that there were 2 modes:

1. Management Key derived from PIN + salt, PUK blocked
  - Management Key was assumed to function as alternative to PUK & "PIV management operation"
2. PUK and Management key set to user known values
  - PUK can reset PIN
  - Management Key for "PIV management operation"

The documentation isn't quite clear on resetting the PIN in the first mode, it just says it's for "PIV management operation".  , but it does say PUK is blocked.

> Management Key
> All PIV management operation of the YubiKey require a 24 byte 3DES key, known as the Management Key. You can either explicitly set a 24 byte key (the YubiKey PIV Manager can generate one for you), or you can choose to not set a Management Key, instead using the PIN for these operations. If so, you will be asked to provide your PIN instead of your Management Key whenever you perform a management operation, such as importing a new certificate, or generating a new key pair.
>
> NOTE
> See the section Considerations when using a PIN for PIV management!
>
> PUK
> The PUK can be used to reset the PIN if it is ever lost or becomes blocked after the maximum number of incorrect attempts. Setting a PUK is optional. If you use your PIN as the Management Key, the PUK is disabled for technical reasons, explained in a later section. The requirements and restrictions of the PUK are the same as for the PIN (see above). If PIN complexity is enforced, the same rules are applied to the PUK. If the PUK ever becomes blocked, either by deliberately choosing to block it or by giving the wrong PUK value 3 times, it can only be unblocked by performing a complete reset (explained below).

**Comment by trinitronx** [comment]
As you said, in this case there is no way to avoid a full reset and re-generate/import certificates and keys.  After setting all this back up again with PUK, everything is again working.

**Comment by qpernil** [comment]
Since management key derivation is deprecated i'm closing this issues. YubiKey Manager is backwards compatible with a key that has been set up with key derivation (for example using the old piv manager). However, a blocked PUK cannot be reversed without resetting the PIV application, and loosing the keys.
