### ISSUE TITLE
Simple Standalone Application

### ISSUE THREAD

**Issue by drvarun** [Yubico/yubico-piv-tool#292]
Hello Yubico Team,

I am new to Yubico and I am trying to start by creating a simple standalone application in C which uses Yubikey 5C NFC' PIV functionality (Sign). However, I am unable to find simple basic standalone C examples to start with. If you could guide me, it would be great.

I already tested the command-line tools and they are working fine but I want to create my own standalone application.
I suppose it can be done using the PKCS#11 APIs but I have no idea what all header files I need to include and what flags I need to use for compiling a simple standalone application.

Thank you in advance to guide me.
(PS: If there are examples of simple standalone application in other languages like Java, Python, Go, etc., I will be happy to look at it as well)

**Comment by qpernil** [comment]
There are two slightly different approaches to this. One is to use the PKCS11 api, which is a standardized API where you would write your application to use any pkcs#11 implementation (ideally, but some restrictions usually apply), including ykcs11. You would use a standard pkcs11 header file and then dynamically link with the ykcs11 shared library at runtime. Hence there is no pkcs11 include file installed by the piv-tool installer. The other more direct approach if you know you will only work with the YubiKey is to use the proprietary libykpiv library, with it's associated header file. This library directly expose the full functionality of the PIV application on the YubiKey. This is a simpler programming model if starting from scratch.
If you have trouble locating a standard pkcs11 header file there is one included with the source code for ykcs11.

**Comment by qpernil** [comment]
Closing this now, feel free to open a new issue if needed.
