### ISSUE TITLE
Windows x64 build

### ISSUE THREAD

**Issue by ble0** [Yubico/yubico-piv-tool#294]
Is it possible to have windows x64 binary directly instead of building it from the source?
I hope I'm not making a huge request.

**Comment by a-dma** [comment]
Are you aware of this page https://developers.yubico.com/yubico-piv-tool/Releases/?

If so, is it not enough?

**Comment by ble0** [comment]
because it only recognizes yubikey at the moment

**Comment by a-dma** [comment]
As opposed to?

How does that relate to Windows builds?

**Comment by ble0** [comment]
im using a blank card and installed the piv applet, however it is not recognized by the yubico-piv-tool, so Im thinking if there’s a build that is not yubico hardware restricted

**Comment by a-dma** [comment]
There aren't any other builds, at lest not official ones.

Have you tried running `yubico-piv-tool` with a different `--reader` parameter that matches your card reader name?

**Comment by ble0** [comment]
yes I did but as of the moment, it only recognizes yubico smartcards, when I use a generic smartcard, the tool does not recognise it

**Comment by a-dma** [comment]
Hard to tell what is going wrong without a debug trace. Try having a look with `-v2` to see where things go wrong. I don't know what applet you loaded exactly but perhaps it expects slightly different commands.

Alternatively, try `piv-tool` from the OpenSC project.

**Comment by ble0** [comment]
ok i will try that.. tnx

**Comment by qpernil** [comment]
Only recognizing YubiKeys is by design. This library uses some commands that are not in the PIV standard, so non-YubiKey PIV smartcards would likely not work. Closing this issue now as it seems to be resolved. Feel free to open a new issue if needed.
