### ISSUE TITLE
Not the correct architeture??

### ISSUE THREAD

**Issue by ajseesink** [Yubico/yubico-piv-tool#300]
Hi,
I'm not sure i'm on the correct site here, but i'll try. 

I followed the guide on https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html
Steps 1 to 4 are ok. But step 5, exporting the public key, gives me the following error:

dlopen /usr/local/lib/libykcs11.dylib failed: dlopen(/usr/local/lib/libykcs11.dylib, 0x0002): could not use '/usr/local/lib/libykcs11.dylib' because it is not a compatible arch
cannot read public key from pkcs11

The command I used is "ssh-keygen -D /usr/local/lib/libykcs11.dylib -e" 

I downloaded the piv-tool here "https://developers.yubico.com/PIV/Tools.html" 

And, perhaps important, I used the command on a MacBook Air M1. 

Could it be that the tool isn't ready yet for the Apple M1?

**Comment by qpernil** [comment]
Universal binaries will be uploaded soon. In the mean time you can build from source on the M1 mac.

**Comment by qpernil** [comment]
Also, if the application you are using is itself universal you can force it to be run in Rosetta 2 / Intel mode, in which case things will work.

**Comment by ajseesink** [comment]
Thanks. I see the mac arm64 is released as of today 👍 
I tested it, look ok.
