### ISSUE TITLE
EC_GROUP_new_by_curve_name(nid) not freed after use

### ISSUE THREAD

**Issue by bentonstark** [Yubico/yubico-piv-tool#301]
https://github.com/Yubico/yubico-piv-tool/blob/9f545e72d8969a7f3001004b8978721c17a09b5e/tool/yubico-piv-tool.c#L272

ref: https://www.openssl.org/docs/man1.1.0/man3/EC_GROUP_new_by_curve_name.html

EC_GROUP_free frees the memory associated with the EC_GROUP. If group is NULL nothing is done.

**Comment by qpernil** [comment]
This looks fine to me, there is a call to EC_GROUP_clear_free later in that function. I will close this issue now, please feel free to create a new issue if you believe I'm mistaken.

/Per
