### ISSUE TITLE
ykcs11: Allow creating keys with sensitive=true, extractable=false

### ISSUE THREAD

**Issue by wiktor-k** [Yubico/yubico-piv-tool#310]
Hi,

I'm using Yubikey 5C via PKCS#11 interface via `libykcs11.so` and I've got a question/bug report.

A common way of creating keys using `C_GenerateKeyPair` is to pass `CKA_SENSITIVE` attribute with `true` value and `CKA_EXTRACTABLE` with `false` to make sure that the keys cannot be extracted from the token. Unfortunately it seems `CKA_SENSITIVE` is [ignored](https://github.com/Yubico/yubico-piv-tool/blob/master/ykcs11/objects.c#L1702) in ykcs11 and passing `CKA_EXTRACTABLE` with any value causes the generation to [be immediately rejected](https://github.com/Yubico/yubico-piv-tool/blob/master/ykcs11/objects.c#L1708).

I've seen other PKCS#11 drivers that use a little bit different logic: if `CKA_SENSITIVE` is `true` and `CKA_EXTRACTABLE` is `false` they allow the request to proceed (and reject the request in other cases). Reference: https://source.codeaurora.org/external/qoriq/qoriq-components/libpkcs11/tree/src/objects.c#n1262

This issue was identified when working on a Rust library for accessing tokens via PKCS#11 interface: https://github.com/parallaxsecond/parsec/issues/462#issuecomment-876449201

If you agree to change the logic to what other drivers do I could work on a patch.

Thank you for your attention! :wave:

**Comment by mouse07410** [comment]
What's the semantic meaning of the attribute `CKA_SENSITIVE`?

**Comment by wiktor-k** [comment]
@mouse07410 [PKCS#11 spec](https://www.cryptsoft.com/pkcs11doc/STANDARD/pkcs-11v2-20.pdf) gives the following description (p. 83):

> If  the  CKA_SENSITIVE  attribute  is  CK_TRUE,  or  if  the  CKA_EXTRACTABLE attribute  is  CK_FALSE,  then  certain  attributes  of  the  private  key  cannot  be  revealed  in  plaintext  outside  the  token.    Which  attributes  these  are  is  specified  for  each  type  of  private key in the attribute table in the section describing that type of key.

**Comment by mouse07410** [comment]
I don't have the standard at hand.

If `CKA_EXTRACTABLE` is set to `false`, what practical difference does it make whether the other attribute is or isn't explicitly specified?

**Comment by wiktor-k** [comment]
> I don't have the standard at hand.

I have linked to the standard in my previous comment: https://www.cryptsoft.com/pkcs11doc/STANDARD/pkcs-11v2-20.pdf

> If CKA_EXTRACTABLE is set to false, what practical difference does it make whether the other attribute is or isn't explicitly specified?

First of all setting `CKA_EXTRACTABLE` to `false` currently makes the key generation request **fail**. This is my primary concern with ykcs11 that I'd like to rectify.

The difference between extractable and sensitive is subtle but it's also explanined in the spec:

>  Additional  protection  can  be  given  to  private keys and secret keys by marking them as  “sensitive”  or  “unextractable”.    Sensitive  keys cannot be revealed in plaintext off the  token,  and  unextractable  keys  cannot  be  revealed  off  the  token  even  when  encrypted (though they can still be used as keys). 

(7. Security considerations, p. 30)

**Comment by mouse07410** [comment]
In other words, `CKA_SENSITIVE` appears to be a subset of `CKA_EXTRACTABLE`?

What happens if you omit specifying `CKA_SENSITIVE` in the request at all? It fails?

**Comment by wiktor-k** [comment]
@mouse07410 quoting myself from the issue report:

> Unfortunately it seems CKA_SENSITIVE is ignored in ykcs11 and passing CKA_EXTRACTABLE with any value causes the generation to be immediately rejected.

In case you don't see links: https://github.com/Yubico/yubico-piv-tool/blob/master/ykcs11/objects.c#L1702 and https://github.com/Yubico/yubico-piv-tool/blob/master/ykcs11/objects.c#L1708

> What happens if you omit specifying CKA_SENSITIVE in the request at all? It fails?

Presence of CKA_SENSITIVE is not important because it is ignored (see my previous link). (Maybe the value should be checked that it is not `false`?)

CKA_EXTRACTABLE making the request fail is the most annoying problem of them two.

**Comment by mouse07410** [comment]
I see your point now.

I plan to propose a short fix.

**Comment by wiktor-k** [comment]
Thank you @mouse07410!

**Comment by mouse07410** [comment]
@a-dma there are two issues with `ykcs11/objects.c` file:
1. It fails on `CKA_EXTRACTABLE` attribute, which is wrong - it should just silently assume it's set to `false`.
2. It silently ignores `CKA_DERIVE` attribute for creating **RSA keys** which is totally wrong, and only applicable to **EC** keys.

This patch fixes both. I don't want to bother creating a PR, you should be able to handle the patch of this size. :-)

```diff
diff --git a/ykcs11/objects.c b/ykcs11/objects.c
index fca0e30..76a7c62 100644
--- a/ykcs11/objects.c
+++ b/ykcs11/objects.c
@@ -1588,6 +1588,7 @@ CK_RV check_create_ec_key(CK_ATTRIBUTE_PTR templ, CK_ULONG n, CK_BYTE_PTR id,
     case CKA_SUBJECT:
     case CKA_SENSITIVE:
     case CKA_DERIVE:
+    case CKA_EXTRACTABLE:
       // Ignore other attributes
       break;
 
@@ -1699,8 +1700,8 @@ CK_RV check_create_rsa_key(CK_ATTRIBUTE_PTR templ, CK_ULONG n, CK_BYTE_PTR id,
     case CKA_TOKEN:
     case CKA_LABEL:
     case CKA_SUBJECT:
-    case CKA_SENSITIVE:
-    case CKA_DERIVE:
+    case CKA_SENSITIVE: 
+    case CKA_EXTRACTABLE:
       // Ignore other attributes
       break;
 
```

If you care to, it can be more "involved" - e.g., check the value of the given `CKA_EXTRACTABLE` and fail if it's set to `true`, but I personally wouldn't bother...

**Comment by a-dma** [comment]
@wiktor-k, could you please have a look at #311 and see if that solves the problem for you?

I've touched both key generation and key import. If you had a chance to try both that would be much appreciated.

I'll look into `CKA_DERIVE` in another instance. I know it doesn't make sense for RSA in this context, but it hasn't been a problem either so far.

**Comment by wiktor-k** [comment]
Tested and with the minor false<->true adjustment (commented on the PR) this works as expected :+1: 

Thanks for a swift patch @a-dma!

**Comment by wiktor-k** [comment]
As https://github.com/Yubico/yubico-piv-tool/pull/311 is merged I'm closing this ticket (resolved).
