### ISSUE TITLE
[YKCS11] Calling `C_OpenSession` before `C_GetSlotList` fails

### ISSUE THREAD

**Issue by hug-dev** [Yubico/yubico-piv-tool#312]
Hello 👋 

Trying the Yubikey with Parsec we observed a `CKR_SLOT_ID_INVALID` error with the slot ID `0` when calling `C_OpenSession` (just after initialising).
Investigating it a bit more, I saw that it fails at:

```c
  if (slotID >= n_slots) {
    DBG("Invalid slot ID %lu", slotID);
    locking.pfnUnlockMutex(global_mutex);
    rv = CKR_SLOT_ID_INVALID;
    goto opensession_out;
  }
```

I believe that is because `n_slots` is equal to `0` because it is only incremented when calling [`C_GetSlotList`](https://github.com/Yubico/yubico-piv-tool/blob/1fe03a6d3a09dd4eab20ee91cc244b751554cb1c/ykcs11/ykcs11.c#L395).

That would mean that executing `C_GetSlotList` is first needed before executing any operation with a slot ID? That maps with what is done [in the tests](https://github.com/Yubico/yubico-piv-tool/blob/1fe03a6d3a09dd4eab20ee91cc244b751554cb1c/ykcs11/tests/ykcs11_tests.c#L86). Maybe the logic inside `C_GetSlotList` could be moved inside `C_Initialize`?

**Comment by a-dma** [comment]
Hi,

yes, that is indeed the intended behavior. Even though the slot mapping can be static, it doesn't necessarily have to be so.

This is what the specifications mention on the topic:

> A list of CK_SLOT_IDs is returned by C_GetSlotList.  A priori, any value of CK_SLOT_ID can be a valid slot identifier—in particular, a system may have a slot identified by the value 0.  It need not have such a slot, however.

The functionality could probably be moved to the initialization function (I'd have to spend more time thinking about it before giving a definitive answer though) but it would have to be replicated in `C_GetSlotList` to pick up state changes anyway.

I am under the impression that the intended flow is what this module implements, and in my experience that is also what generic PKCS#11 clients normally do.

**Comment by hug-dev** [comment]
Thanks for your answer. I agree that `C_GetSlotList` has to be called by someone in order to find a good, valid, `CK_SLOT_ID` to be used for other operations. However I don't think this is required to be PKCS11 compliant.

In our use-case (for Parsec), one admin calls `C_GetSlotList` to find the list of valid slots and write one of them in the Parsec configuration (there might be multiple HSM plugged in for example, but we only want to use one of them in Parsec). When Parsec starts, it reads the configuration, reads the `CK_SLOT_ID` and tries to open a session with that slot ID, without having called `C_GetSlotList` before (because it does not need it).

**Comment by a-dma** [comment]
I imagined that that's how to did things. I assume that when you say configuration you mean a configuration file or something similarly persistent across different invocations? How do you then ensure that a given slot ID remains valid across different invocations? Or how do you realize that something was enumerated differently in this invocation and what used to be the device in slot X is now the device in slot Y if you blindly open a pre-configured slot?

I'm not trying to tell you how to develop your application and I'm probably assuming a lot of things that I don't know about it, but it sounds like it could be a fragile design in some cases and even dangerous in others.

As for your comment about compliance, I agree that it is not strictly required, and it may happen to just work, but at the same time it is not guaranteed to and as I quoted in my previous message it is very heavily hinted that calling `C_GetSlotList` is the intended behavior.

Given that a client would have to build some logic to recover from a state where its assumptions of the external state are no longer correct, I think that that logic might as well be used as the regular way to build that external state to begin with. Does that make any sense to you or am I being too unreasonable?

**Comment by hug-dev** [comment]
> I assume that when you say configuration you mean a configuration file or something similarly persistent across different invocations?

Yes that's correct, that is a configuration file.

> How do you then ensure that a given slot ID remains valid across different invocations? Or how do you realize that something was enumerated differently in this invocation and what used to be the device in slot X is now the device in slot Y if you blindly open a pre-configured slot?

You make very good points! I agree that it would be more solid if the configuration file instead contained the serial number of the device you want to use and then found the good slot mapping to that. We started with the slot number because of not-too-complete knowledge of PKCS11 at the time. Re-writing that part now, would probably go with the fixed serial number. Those points (specific to our project) were actually proposed by @wiktor-k [here](https://github.com/parallaxsecond/parsec/issues/404#issuecomment-858634017).
However, I don't think this is a big problem for now, because in our use case:
- the devices are not really meant to be un-plugged and plugged often
- the computer where they are plugged is not meant to be rebooted often
I believe that if those two conditions are respected, the slot ID will remain the same.

About this general issue, although I agree that this would be the idiomatic way to use a PKCS#11 implementation, I don't read anything in your quote or elsewhere in the standard that calling `C_GetSlotList` is strictly needed before `C_OpenSession` or other.

To fix this issue on our side with Yubikey, your comment actually made we realise that we could improve slightly (for now) our approach by checking that the slot ID in the configuration is indeed a valid one by calling `C_GetSlotList` before.

**Comment by a-dma** [comment]
>About this general issue, although I agree that this would be the idiomatic way to use a PKCS#11 implementation, I don't read anything in your quote or elsewhere in the standard that calling C_GetSlotList is strictly needed before C_OpenSession or other.

I agree that it's not _strictly_ necessary, but I kind of choose to interpret that as it being so. `C_OpenSession` requires a slot ID and to acquire one, one must call `C_GetSlotList`.

There's a couple of sentences mentioning how the list can change across subsequent invocations of `C_GetSlotList`, and using a saved value would fall into that category. If anything that part, for me, reinforces the fact that `C_GetSlotList` is the right place to handle updating valid slot IDs.

For the record, the sentences I'm referring to are pasted below
>Because C_GetSlotList does not allocate any space of its own, an application will often call C_GetSlotList twice (or sometimes even more times—if an application is trying to get a list of all slots with a token present, then the number of such slots can (unfortunately) change between when the application asks for how many such slots there are and when the application asks for the slots themselves).  However, multiple calls to C_GetSlotList are by no means required.

**Comment by hug-dev** [comment]
That's fine for us! As part of https://github.com/parallaxsecond/parsec/issues/481, we will fix it and make our code work with Yubikey. Thanks for your time 👍
