### ISSUE TITLE
Failed signing file with no error code

### ISSUE THREAD

**Issue by lucy-sha512** [Yubico/yubico-piv-tool#313]
I am trying to sign a file data.txt with ECCP256, everytime I do it generators "failed signing file".  On checking the verborse with -v2 it shows that the hash of the file is generated but it fails during signing with no error code.
What could be the reason for signing failure??

here  is the complete verborse of my sign action

yubico-piv-tool -a verify-pin --sign -s 9c -H SHA512 -A ECCP256 -i data.txt -o data.sig -v2
Connect reader 'Yubico YubiKey OTP+FIDO+CCID 00 00' matching 'Yubikey'.
> 00 a4 04 00 05 a0 00 00 03 08 
< 61 11 4f 06 00 00 10 00 01 00 79 07 4f 05 a0 00 00 03 08 90 00 
> 00 20 00 80 00 
< 63 c3 
> 00 fd 00 00 00 
< 05 02 07 90 00 
> 00 f8 00 00 00 
< 00 eb 8f 8f 90 00 
Action 'verify-pin' does not need authentication.
Now processing for action 'verify-pin'.
Enter PIN: 
> 00 20 00 80 08 34 36 39 39 30 31 ff ff 
< 90 00 
Successfully verified PIN.
file hashed as: 5c 97 16 2e d6 7b 95 fe 7b 43 b4 3a a2 0a 77 7a d2 a5 6c 3d 2c 36 7f c9 11 f6 18 43 7f 14 4a be c9 71 63 9f b2 ec 25 e8 fb 97 28 62 a7 33 f7 cf 9e 0d fd cc 76 19 fa 1d f1 53 a5 a7 eb 6c a4 b4 
failed signing file
Failed signing!
Disconnect card #15437711.

**Comment by a-dma** [comment]
That would be because `libykpiv` enforces size restrictions based on the key length. Sorry for the poor error handling, but `--sign` function is hidden for a reason.

Try changing your hash algorithm to either SHA1 or, more appropriately for this case, to SHA256 and you should see a better result.

**Comment by lucy-sha512** [comment]
Thank you for replying.

**Comment by mouse07410** [comment]
@a-dma if memory serves me correctly, ECDSA standard says that if the data to be signed is larger than the key size, the first leftmost bits of that data are used. I.e., data is truncated. 

I realize that this approach doesn't allow distinguishing between signatures for "correct-and-long" and "correct-and-long-modified-plus-more-evil-suffix". But I recall that that's what the standard says. Could you check please?

P.S. What other functions are hidden in `yubico-piv-tool`? ;-)

**Comment by a-dma** [comment]
> @a-dma if memory serves me correctly, ECDSA standard says that if the data to be signed is larger than the key size, the first leftmost bits of that data are used. I.e., data is truncated.

Yes that is what NIST say in FIPS 186-4. Currently that behavior is not supported though. Anything calling into `libykpiv` (and therefore `ykcs11`) will have to use a "matching" digest function.
 
> P.S. What other functions are hidden in `yubico-piv-tool`? ;-)

Not a whole lot https://github.com/Yubico/yubico-piv-tool/blob/master/tool/cmdline.ggo#L69-L70
You can get those by invoking `--full-help`.

**Comment by mouse07410** [comment]
Thanks. I don't know what to say, because on one hand, silent truncation is not good from security point of view, on the other hand, the standard supports that "security violation".

Perhaps it's fine to leave as-is... I, for one, do not require sorry for truncation in my apps.
