### ISSUE TITLE
Uninstall on Mac?

### ISSUE THREAD

**Issue by Ramias1** [Yubico/yubico-piv-tool#316]
Installed on my Mac M1 from the main download page at Yubikey.  Didn't work; got everything working with OpenSC - then I found the Arm version of Yubi Key Pin Tools.  Still -- how do I cleanly and completely uninstall the Yubico key piv tools from a Mac?

Thanks

**Comment by aveenismail** [comment]
Hi

Unfortunately, there's no straight forward way to uninstall yubico-piv-tool from a Mac. The only way is to manually delete the following files:

/usr/local/bin/yubico-piv-tool
/usr/local/include/ykpiv
/usr/local/lib/libykcs11.*  
/usr/local/lib/libykpiv.*
/usr/local/licenses/yubico-piv-tool.txt
/usr/local/share/man/man1/yubico-piv-tool.1

Note though that yubico-piv-tool installer includes also libcrypto libraries, so it also installs the following files:

/usr/local/include/openssl
/usr/local/lib/libcrypto.*  
/usr/local/licenses/openssl.txt

So if you're using libcrypto for something other than yubico-piv-tool, you may want to be careful about deleting those files.

Having said that, installing yubico-piv-tool from the Mac .pkg installer typically over-writes existing files if there were any. So when you've installed from the ARM installer, the files from your first installation should have been replaced.

Does it still not work after you installed yubico-piv-tool using the installer for ARM arch? How is it not working? Are you getting error messages?

**Comment by Ramias1** [comment]
Thanks. Have not installed the Arm version yet since it works fine with OpenSC and I may stick with that.  Is there a benefit to using the native Yubikey vs Open SC files?

**Comment by mouse07410** [comment]
I think it is **very bad** for `yubico-piv-tool` to install its "own" OpenSSL library.

**Comment by aveenismail** [comment]
I'm assuming what you're using is the PKCS11 module? If yes, then the benefit of using YKCS11 is that YKCS11 is a lighter application than OpenSC's. It also exposes the attestation certificates, which OpenSC does not

**Comment by mouse07410** [comment]
And YKCS11 offers more capabilities when you generate or import keys.
