### ISSUE TITLE
AES keys support for PIV management is missing in yubico-piv-tool

### ISSUE THREAD

**Issue by fblr** [Yubico/yubico-piv-tool#333]
Hello

Have a yubikey with firmware version 5.4.3 and created AES-192 management key with ykman.
Unfortunately it is impossible to, for example, import keys using yubico-piv-tool with this management key, because, I guess, yubico-piv-tool supports only 3DES. I got misleading "Failed authentication with the application." error during import, although the key was management correct. It works correctly if I keep 3DES for the management key.

Please either add this functionality or change error message to more relevant. Thank you.

% yubico-piv-tool --version
yubico-piv-tool 2.2.1
% /Applications/YubiKey\ Manager.app/Contents/MacOS/ykman list
YubiKey 5C NFC (5.4.3) [OTP+FIDO+CCID] Serial: XXXXXXXX

**Comment by qpernil** [comment]
The above PR implements support for authenticating with an AES management key, by using the -m option to specify AES128, AES192 or AES256 key support. Still to do is complete support in libykcs11.

**Comment by qpernil** [comment]
The code was changed so that the -m option only applies to the new key when setting a new mgmt key. The algorithm for the current key is retrieved using the get-metadata command. If that fails the YubiKey must be using a TDEA key, as metada support predates AES support.

**Comment by qpernil** [comment]
Support is now present in libykcs11, thanks to automatic algorithm detection. When setting SO PIN through pkcs11 the new mgmt key will be set to the same algorithm as the old one.
