### ISSUE TITLE
PKCS#11 support for Touch and PIN policies

### ISSUE THREAD

**Issue by kevinjacobs** [Yubico/yubico-piv-tool#341]
Hi. I'm working on a library that exposes 2FA functionality through PKCS#11 with certain hardware tokens. 

We're in the process of adding YubiKey support and we'd like to be able to set touch and PIN policy through `C_GenerateKeyPair`. This used to be supported through the `CKA_VENDOR_DEFINED` attribute [0] but it was removed in [1]. I don't see any PR or explanation for its removal. 

Would Yubico be receptive to a PR adding this functionality? If so, are there known, blocking issues with the old approach that would need to be addressed in the new PR? It appears that the old implementation lacked support for querying policy through `C_GetAttributeValue`, but that can be added (via `ykpiv_get_metadata`) relatively easily.

FWIW, I've implemented the basic functionality and confirmed that it works on a recent YubiKey 5.

Thanks in advance!

[0] https://github.com/Yubico/yubico-piv-tool/blob/yubico-piv-tool-1.7.0/ykcs11/token_vendors.c#L162
[1] https://github.com/Yubico/yubico-piv-tool/commit/fd2b5852817814ef64e496facbd33d81b0e55efb

**Comment by qpernil** [comment]
We'd welcome a PR, preferably rebased on master of course. As you might notice there are quite a few PRs in flight at the moment, so it might take a little bit of time to get around to it, as well as the possibility that we might request another rebase after those are merged. But now is the time, a new release is not too far off into the future..

**Comment by kevinjacobs** [comment]
Sounds good and sorry for the delay.. The code is ready to go but I'm awaiting a couple of employer approvals before opening the PR. It should be up sometime next week at the latest, hopefully in time for your upcoming release.

**Comment by qpernil** [comment]
How would you feel about adding the CKA_ALWAYS_AUTHENTICATE as an additional attribute for PIN policy ? It only has two possible values according to the standard. But we could support it as an alternative way of specifying YKPIV_PINPOLICY_ONCE or YKPIV_PINPOLICY_ALWAYS. Neither of the attributes would mean YKPIV_PINPOLICY_DEFAULT.

**Comment by kevinjacobs** [comment]
> 

Yeah, I should have thought to wire that in. It's a simple addition. 

Using a `CKA_ALWAYS_AUTHENTICATE` value of `CK_FALSE` to specify `YKPIV_PINPOLICY_ONCE` seems a bit counterintuitive, given that the PIV applet defines per-slot defaults and the PKCS#11 spec only discusses behavior when that attribute is `CK_TRUE`. 

The alternative would be to only allow specifying a value of `CK_TRUE` (as `YKPIV_PINPOLICY_ALWAYS`). That said, PIN_ONCE is a safer configuration and from what I can tell this would only matter on slot 9e. I'll go that route as long as you're comfortable with the behavior.

**Comment by qpernil** [comment]
I have merged the first PR now, thx for the contribution. I am working on keeping the policy values around in the slot info, like we do for the 'local' attribute already, from when the first session is opened on a slot. That logic uses attestation first, since we want the attestation certificate anyway, and also that is is available for older YubiKeys. If that fails it uses metadata, which will also be the case for imported keys. This way getting those attributes will not need to touch the PIV applet.

**Comment by qpernil** [comment]
FYI, working on this now here https://github.com/Yubico/yubico-piv-tool/pull/354

**Comment by qpernil** [comment]
https://github.com/Yubico/yubico-piv-tool/pull/354 has now been merged to master. Let me know if you have any issues with how this works

**Comment by qpernil** [comment]
It's expected but maybe not ideal - As it now only reads the attestation / metadata when you open the first session on a slot. I adjusted the tests accordingly. If you just implement the import like I did the key generation, i.e. setting the pin and touch policy values to the specified ones the existing tests (with my adjustments) should work.

**Comment by qpernil** [comment]
We should probably create an attestation or fetch metadata when generating or importing keys as well, to keep that info up to date. But in the mean time, maybe you could just do as described in my last note here.

**Comment by qpernil** [comment]
OK, I have added code to parse the attestation upon key generation, and to get metadata when importing. So the tests fail again now, I just have to fix that and we should be fine. I still suggest you assign the specified policies on import (like I do in key generation) so that we have the best we can in case metadata is not supported by the device. Checking this in soon.

**Comment by qpernil** [comment]
See https://github.com/Yubico/yubico-piv-tool/pull/356

**Comment by kevinjacobs** [comment]
Thanks! See #357

**Comment by kevinjacobs** [comment]
And thank you for the reviews! We're glad to be able to use this functionality.
