### ISSUE TITLE
Importing ed25519 key material appears to be not supported

### ISSUE THREAD

**Issue by mirko** [Yubico/yubico-piv-tool#349]
To my understanding - since firmware version 5.2 - the YubiKey is able to hold keys / certificates of type ed25519.
Trying to import them via yubico-piv-tool however results in "Unknown algorithm".
Looking at HEAD of master within this repo, it indeed seems to only support RSA1024, RSA2048 and ECCP256, ECCP384.[1]
Do I misunderstand the support for ed25519 key material introduced in FW 5.2 and if not, what's the way of importing such key material if not via yubico-piv-tool?

Thanks!

[1]https://github.com/Yubico/yubico-piv-tool/blob/master/tool/yubico-piv-tool.c#L1727

**Comment by a-dma** [comment]
Hi,

indeed, there is no support for Curve25519 in the PIV application since the related algorithms are not available in that standard.

Other independent applications on a YubiKey like FIDO and OpenPGP have support for that type of keys.

**Comment by mirko** [comment]
Thanks for answering, I'd just like to take the opportunity for clarification:

This means the slots for retired keys can not be used to hold ed25519 keys - is that correct?

**Comment by a-dma** [comment]
Yes, that would be correct.

Technically speaking it is possible to import certificates in those slots (or any other), but not private keys.

**Comment by dylangerdaly** [comment]
Is there a reason this isn't possible? I'm guessing PIV is NIST so any changes to the PIV applet have to be approved by NIST first?

Like, technically Yubico could add support for Curve25519? I assume NIST certify the applet or something?

I really like PIV, just wish I could use Ed25519 keys.

**Comment by mouse07410** [comment]
Out of curiosity, what is it about Ed25519 that you find so attractive?

**Comment by dylangerdaly** [comment]
It's not low-key backdoored.

It's GPG I hate with a passion, PIV is a much nicer interface

-------- Original Message --------

**Comment by mouse07410** [comment]
> It's not low-key backdoored

And you know that - how?

**Comment by dylangerdaly** [comment]
I drink, and I know things 🤣

There are smarter people than me that have opinions on this subject

-------- Original Message --------

**Comment by 497a** [comment]
Whatever one’s personal beliefs on the back door topic may be, support for Ed25519 would be great.

**Comment by mirko** [comment]
I would like to follow up on that and ask whether firmware version 5.7.0+ this would be possible today?

**Comment by aveenismail** [comment]
Yes, the PIV application in firmware version 5.7.0+ does now support ED25519 as well as X25519

**Comment by qpernil** [comment]
And so does yubico-piv-tool as well as Yubico Authenticator
