### ISSUE TITLE
Use as SDK for Go

### ISSUE THREAD

**Issue by dnascimento** [Yubico/yubico-piv-tool#35]
Could someone write documentation on how to use Yubico PIV Tool with GoLang (or C) as SDK? 
It would be great to have an easy and secure API to develop solutions with Yubico. There are several wrappers with PKCS#11 but I would prefer to use a secure API provided by Yubico community

**Comment by dnascimento** [comment]
A good reference is Docker's Notary integration with yubico:
https://github.com/docker/notary/tree/master/trustmanager/yubikey

**Comment by qpernil** [comment]
Both yubico-piv-tool and ykcs11 are based on the piv library thats is part of the same installation. 
I'm closing this issue because of it's age. Please re-open if needed.
