### ISSUE TITLE
Issue adding keys to ssh-agent

### ISSUE THREAD

**Issue by viraptor** [Yubico/yubico-piv-tool#361]
I've tried to add the key from piv to my agent and it keeps failing.

```
yubico-piv-tool 2.0.0
OpenSSH_8.6p1, LibreSSL 2.8.3
```

```
$ ssh-add -v -s "/nix/store/0r4iprrb71b03fb4bpgjn4r0g3lbncc3-yubico-piv-tool-2.0.0/lib/libykcs11.dylib"
Enter passphrase for PKCS#11:
Could not add card "/nix/store/0r4iprrb71b03fb4bpgjn4r0g3lbncc3-yubico-piv-tool-2.0.0/lib/libykcs11.dylib": agent refused operation
```

I don't know which password PKCS11 it's asking for here since it's not the PIN:

```
$ yubico-piv-tool -s 9a -a verify-pin
Enter PIN:
Successfully verified PIN.
```

I'm not sure what's happening here - pkcs library trying to get a different spot? Happy to provide more info or debug this further.

**Comment by mouse07410** [comment]
PKCS#11 password **is** your PIN. The problem is that SSH agent is broken, which is why it's refusing operation. 

I have the same problem on MacOS.

**Comment by viraptor** [comment]
The docs could be improved a bit. Here's the summary of how to fix it: https://somm15.github.io/yubikey/macos/ssh/2018/11/20/welcome-to-jekyll.html
In short - make sure the agent is spawned with `-P (pattern-that-matches-library)`.

The issue becomes obvious when you run `ssh-agent -d`.

**Comment by viraptor** [comment]
Ah, I failed to save the later edit of the message.
Although that part solves adding the key, it doesn't seem like the right key is used by openssh.
Specifically:
1. If I just try to use the original keys, I'm asked for the pin to the attestation key and that doesn't work.
2. If I try to generate a key in an unused slot (piv-tool -s 9c -a generate), no new key is seen by ssh-agent - still only attestation.

**Comment by johndutchover** [comment]
I'm looking at the links for a "fix" and haven't found one.

**Comment by Jakuje** [comment]
Do you see the keys if you list them in ssh-keygen, with something like
```
$ ssh-keygen -D "/nix/store/0r4iprrb71b03fb4bpgjn4r0g3lbncc3-yubico-piv-tool-2.0.0/lib/libykcs11.dylib"
```
The solution is to support PKCS#11 URIs in OpenSSH, but the pkcs11 users are not interesting enough for the OpenSSH developers to accept a patch I posted 4 years back.

**Comment by johndutchover** [comment]
> Do you see the keys if you list them in ssh-keygen, with something like
> 
> ```
> $ ssh-keygen -D "/nix/store/0r4iprrb71b03fb4bpgjn4r0g3lbncc3-yubico-piv-tool-2.0.0/lib/libykcs11.dylib"
> ```
> 
> The solution is to support PKCS#11 URIs in OpenSSH, but the pkcs11 users are not interesting enough for the OpenSSH developers to accept a patch I posted 4 years back.

I'm on macOS 12.2.1 and dealing with inherent challenges there. Found a couple locations with libvkcs11:
- symlink `/usr/local/lib/libykcs11.dylib` to homebrew version `/usr/local/lib/libykcs11.dylib`

Results:
ssh-keygen -D /usr/local/lib/libykcs11.dylib
cannot read public key from pkcs11

ssh-keygen -D /usr/local/Cellar/yubico-piv-tool/2.2.1/lib/libykcs11.dylib
cannot read public key from pkcs11

**Note**: I will review use of gnupg and any conflicts with ssh-agent.

**Comment by Jakuje** [comment]
Adding `-v` to the `ssh-keygen` can give some more information why it failed. I would also suggest to try OpenSC, which should be also available for mac.

**Comment by johndutchover** [comment]
I'm probably going to "table" this for now as time spent working out issues with gpg-agent isn't worth the trouble. Thanks for the help.

**Comment by jordanenglish** [comment]
@viraptor Have you tried updating your `yubico-piv-tool` ?

I'm running `yubico-piv-tool 2.3.0`
