### ISSUE TITLE
FreeBSD 11 build fails

### ISSUE THREAD

**Issue by cypher386** [Yubico/yubico-piv-tool#37]
$ make
Making all in lib
Making all in .
  CC       ykpiv.lo
  CC       version.lo
  CC       error.lo
  CCLD     libykpiv.la
Making all in tests
Making all in tool
/bin/sh /home/jporter/yubico-piv-tool/build-aux/missing gengetopt --input
gengetopt: option '--input' requires an argument
Run gengetopt --help to see the list of options.
*** Error code 1

Stop.
make[1]: stopped in /usr/home/jporter/yubico-piv-tool/tool
*** Error code 1

Stop.
make: stopped in /usr/home/jporter/yubico-piv-tool

Packages installed:
autoconf-2.69
autoconf-wrapper-20131203
automake-1.15_1
automake-wrapper-20131203
gengetopt-2.22.6_2
libtool-2.4.6
pcsc-lite-1.8.14,2

**Comment by klali** [comment]
interesting.. in the generated Makefile for me that call to gengetopt is:
  $(GENGETOPT) --input $^

you should be able to get around this by building an official release from https://developers.yubico.com/yubico-piv-tool/Releases/

**Comment by cypher386** [comment]
The official release works.
