### ISSUE TITLE
Add support for Ubuntu 22.04

### ISSUE THREAD

**Issue by adiroiban** [Yubico/yubico-piv-tool#373]
Hi,

I have recently updated to Ubuntu 22.04 and it looks like the PIV part of yubikey is not working.

The U2F was working out of the box.

But I am using the yubikey with ssh-agent

```
Bus 005 Device 005: ID 1050:0406 Yubico.com Yubikey 4/5 U2F+CCID
```

I have installed the piv-tool from Ubuntu repository, since there is no Ubuntu 22.04 version at `ppa:yubico/stable`

I get this error:

```
$ yubico-piv-tool -a status
Failed to connect to yubikey.
Try removing and reconnecting the device.
```

I have also installed `ykcs11` - PKCS#11 module for the YubiKey PIV applet and I get

```
Could not add card "/usr/lib/x86_64-linux-gnu/libykcs11.so": agent refused operation
```

The pin is correct, as I use the same yubikey  and same commands in Ubuntu 21.04 and it works fine.

I run ssh-agent in debug mode, and the output is

```
debug1: process_message: socket 1 (fd=4) type 20
debug2: process_add_smartcard_key: entering
debug1: process_add_smartcard_key: add /usr/lib/x86_64-linux-gnu/libykcs11.so.2.2.0
debug1: process_add
debug1: provider /usr/lib/x86_64-linux-gnu/libykcs11.so.2.2.0: manufacturerID <Yubico (www.yubico.com)> cryptokiVersion 2.40 libraryDescription <PKCS#11 PIV Library (SP-800-73)> libraryVersion 2.20
C_GetSlotList failed: 48
```

Do you know how I can fix this issue?

Thanks for the yubikey which is such a great product!

**Comment by qpernil** [comment]
I just upgraded my test machine to 22.04, and have no issues. However, there are a couple of potential differences:
- I upgraded instead of doing a fresh install. This machine has been on several earlier versions before now.
- I built yubico-piv-tool from source (rebuilt it now on 22.04 just to be safe).
Would you mind building from source to test if that works, in order to see if it's just the packaging ?
Thanks

**Comment by qpernil** [comment]
Some additional details : My machine also has an (empty) smartcard reader. I used a YubiKey version 5.4.3 to test.
If I log out from my user with the YubiKey still present the machine will try do perform smartcard login.
Since I haven't set that up I have to remove the YubiKey while logging on. After that there is no interference.

**Comment by e100** [comment]
Fresh install of 22.04
Setup Yubico PPA and installed yubico-piv-tool

libykcs11.so is not working, for example:
openvpn --show-pkcs11-ids /usr/lib/libykcs11.so
`2022-05-09 13:38:03 PKCS#11: Cannot add provider '/usr/lib/libykcs11.so' 6-'CKR_FUNCTION_FAILED'
2022-05-09 13:38:03 Exiting due to fatal error`

yubico-piv-tool -V
`yubico-piv-tool: symbol lookup error: yubico-piv-tool: undefined symbol: ykpiv_set_mgmkey3`

**Comment by qpernil** [comment]
Interesting, that looks like the yubihsm library is too old.

**Comment by e100** [comment]
When we first installed yubico-piv-tool it did not exist in PPA yet so installed one from ubuntu.
We installed the one from the PPA but libykpiv2 from Ubuntu repo lingered.
This resolved the problem:
`
sudo apt purge libykpiv2
`
Seems we are working now!

**Comment by qpernil** [comment]
Is the above a solution for the original poster ? The PPAs have been updated as well.

**Comment by adiroiban** [comment]
Still doesn't work.

`libykpiv2` is still provided by Ubuntu.

I don't see it on the Yubico PPA.

https://launchpad.net/~yubico/+archive/ubuntu/stable?field.series_filter=jammy

**Comment by e100** [comment]
@adiroiban 
The Ubuntu Package `yubico-piv-tool` has a dependency for the Ubuntu Package `libykpiv2`
So if you installed the yubico-piv-tool from Ubuntu repo it would have installed libykpiv2
The Ubuntu yubico-piv-tool package does not work, only the PPA package works in 22.04.

The PPA package for 22.04 was made available just a couple days ago.
Even if you had the PPA setup you would have received the broken Ubunu Package, like I did, if you installed it before it was available in the PPA.

If you install the Yubico PPA and then install yubico-piv-tool from the PPA, it does not need libykpiv2 from Ubuntu and if that library remains the PPA yubico-piv-tool will not work properly.
Once I purged the libykpiv2 package the PPA yubico-piv-tool started working.

Also, the Yubico PPA has different path for `libykcs11.so` it is located at `/usr/lib/libykcs11.so`

Hope that helps!

**Comment by adiroiban** [comment]
Thanks for the info.

`/usr/lib/libykcs11.so` is one step forward :)

I am using  yubico-piv-tool_2.3.0~ppa2~jammy1_amd64.deb

```
Package 'libykpiv2' is not installed, so not removed
Package 'ykcs11' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ lsusb  | grep Yubico
Bus 005 Device 008: ID 1050:0406 Yubico.com Yubikey 4/5 U2F+CCID

$ yubico-piv-tool -v 9 -a status
SCardEstablishContext failed, rc=8010001d
Failed to connect to yubikey.
Try removing and reconnecting the device.
```

I tried reconnecting but still doesn't work. I have the mini-USB-C version.
It works on Ubuntu 21.04.
Also, the U2F part works in 22.04 (including for sudo and GDM login)


When I start `ssh-add` in debug mode I get this...but I guess that unless  yubico-piv-tool fails, there is no poing in trying libykcs11

```
debug1: new_socket: type = CONNECTION
debug2: fd 4 setting O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 20
debug2: process_add_smartcard_key: entering
debug1: process_add_smartcard_key: add /usr/lib/libykcs11.so.2.3.0
debug1: process_add
debug1: provider /usr/lib/libykcs11.so.2.3.0: manufacturerID <Yubico (www.yubico.com)> cryptokiVersion 2.40 libraryDescription <PKCS#11 PIV Library (SP-800-73)> libraryVersion 2.30
C_GetSlotList failed: 48
```

**Comment by qpernil** [comment]
This might be a different error - 8010001d is SCARD_E_NO_SERVICE, which typically means pcscd is not running. Maybe check your pcsc-lite installation.

**Comment by qpernil** [comment]
Another thing to check - does Ubuntu try to perform smartcard login if you have the YubiKey attached when you log in (not unlock) ?

**Comment by adiroiban** [comment]
Many thanks for all your help.


It works!

I have pcscd installed... but I have no idea why it wasn't automatically started.

```
pcscd is already the newest version (1.9.5-3).
```

After starting the pcscd all looks good.

For the reference
 
```
sudo systemctl enable pcscd.service
sudo systemctl start pcscd.service
````

------

Regarding the Ubuntu yubikey package.
Any reason why they exist?

Should I open a bug  report to Ubuntu and try to get those packages removed or fixed ?
