### ISSUE TITLE
Failed signing certificate on Ubuntu 22.04

### ISSUE THREAD

**Issue by marlonbaeten** [Yubico/yubico-piv-tool#388]
I am trying to self-sign a certificate using yubico-piv-tool version 2.2.0 on Ubuntu 22.04 (OpenSSL 3.0.2)

The command (sensitive information removed):
```
yubico-piv-tool -v2 -a verify-pin --pin=123456 -a selfsign-certificate -s 9a -S "/CN=example/O=organisation/" -i "keys/example-public.pem"  -o "keys/example-cert.pem" --valid-days=1825
```

The output:
```
Connect reader 'Yubico YubiKey OTP+FIDO+CCID 00 00' matching 'Yubikey'.
... snip ...
Action 'verify-pin' does not need authentication.
Action 'selfsign-certificate' does not need authentication.
Now processing for action 'verify-pin'.
... snip ...
Successfully verified PIN.
Now processing for action 'selfsign-certificate'.
Failed signing certificate.
Disconnect card #12345678
```

Performing the exact same action on Ubuntu 20.04 with yubico-piv-tool version 2.0.0 results in successfully signing the certificate.

I have tried 3 different yubikeys on 2 different Ubuntu 22.04 machines with the same results. I have also tried yubico-piv-tool version 2.3.0 and master which also resulted in the same error.

Any tips on how the debug this issue? Thanks in advance!

**Comment by qpernil** [comment]
Could you run that command again with the -v2 option enabled (debug verbose) ?
Thx.

**Comment by qpernil** [comment]
Sorry I missed the v2, assumed it wasn't active since you had no debug output.
I think the issue is related to yubico-piv-tool 2.2 not being compatible with openssl 3.
I would suggest trying 2.3.0 or building yourself.

**Comment by qpernil** [comment]
The selfsign-certificate action doesn't write the certificate, just like the request-certificate action. The reason being that we didn't expect you to put the selfsigned certificate onto the YubiKey, instead just using it as input for some CA that would issue the real certificate. You can just import it if you wish.
yubico-piv-tool -aimport-certificate -s9a

**Comment by qpernil** [comment]
Both the certificate request and the selfsigned certificate will contain said attestation, plus the attestation certificate from the YubiKey as extensions, so that a CA can use them to verify that the key they receive is from a genuine YubiKey.

**Comment by marlonbaeten** [comment]
Aha, that works! We only use the self-signed certificate to match the username of linux accounts - which is a bit hacky I admit. It might be time to properly sign the certificates. Thank you for the suggestion to use the --attestation option - that sounds useful indeed.

**Comment by qpernil** [comment]
Just a warning - anybody could generate a key and the corresponding selfsigned certificate containing whatever username they choose, so you really must validate the certificate some way. If it is selfsigned your only viable way of doing that would be to know and trust that exact certificate beforehand, or perhaps the sha256 hash of it.

**Comment by qpernil** [comment]
Yes that works as long as you don't trust any other information in the certificate, such as the validity..
