### ISSUE TITLE
No ability to target a specific Yubikey with more than one Yubikey connected.

### ISSUE THREAD

**Issue by dnesting** [Yubico/yubico-piv-tool#409]
Opening a new request per #287 for my use case.  I also have situations where I need to work with multiple YubiKeys simultaneously.  The recommended option in the linked issue is to use `list-readers`, however this is my situation:

```shell
$ yubico-piv-tool -a list-readers
Yubico YubiKey FIDO+CCID 01
Yubico YubiKey FIDO+CCID
```

The `01` appears to be added to give some way of disambiguating, but it doesn't actually work. Both strings above connect to the same Yubikey (maybe it's just doing a prefix match?) and even if it worked, it won't be stable since it depends on what order keys are found in, and whether the second Yubikey uses the same string as the first.

Is it possible to select based on serial number?  This is an obvious unique identifier that's printed on the side of my Yubikeys and would be easy for me to incorporate into my workflow.  I could even have my automation validate the right Yubikey was inserted and eliminate one type of issue caused by human error.

**Comment by qpernil** [comment]
You can specify exact match by prefixing with the at-sign '@'

**Comment by qpernil** [comment]
You are right that it is not stable, and selecting by serial would be a nice added feature.

**Comment by qpernil** [comment]
@dnesting is your use case solved by the above (modulo the stability caveat) for now ?

**Comment by dnesting** [comment]
It doesn't, but I've worked around the issue for now.  One of my use cases involves provisioning, so I can't just leave keys in the device.  If this becomes worth the squeeze I might look into a PR.  Thanks for the response.

**Comment by qpernil** [comment]
Ok, closing this issue now. Thanks for reporting.
