### ISSUE TITLE
C_GetSlotList cannot see tokens if they were inserted after call to C_Initialize

### ISSUE THREAD

**Issue by denisenkom** [Yubico/yubico-piv-tool#41]
E.g.

C_Initialize()
// insert token now
C_GetSlotList(true) // returns empty list

Looks like ykcs11 takes snapshot of attached tokens when Initialize is called and does not update it when GetSlotList is called.

**Comment by a-dma** [comment]
That is correct.
That part has to be slightly refactored to refresh the token list when C_GetSlotList is invoked.

**Comment by a-dma** [comment]
For clarity, I just wanted to point out that this is still according to the specs:

>Furthermore, the set of slots accessible through a Cryptoki library is checked at the time that C_GetSlotList, for list length prediction (NULL pSlotList argument) is called. If an application calls C_GetSlotList with a non-NULL pSlotList, and then the user adds or removes a hardware device, the changed slot list will only be visible and effective if C_GetSlotList is called again with NULL. Even if C_ GetSlotList is successfully called this way, it may or may not be the case that the changed slot list will be successfully recognized depending on the library implementation.  _On some platforms, or earlier PKCS11 compliant libraries, it may be necessary to successfully call C_Initialize or to restart the entire system._
