### ISSUE TITLE
No libykcs11.dylib file after installing package

### ISSUE THREAD

**Issue by YoNevelt** [Yubico/yubico-piv-tool#424]
Hi,

I installed the package yubico-piv-tool on my raspberry pi 4b and as I read on many places, this should install the libykcs11.dylib file as well to the path /usr/local/lib/ ... but it's not there and after the full / path search, it's nowhere. On the above mentioned path there was only Python related file.
I was going to follow a tutorial where this line caused problem due to non-existing file:
> Let's get the SSH pubkey for this. We'll need a PKCS#11 library, either libykcs (provided with yubico-piv-tool) or OpenSC.
ssh-keygen -D /opt/local/lib/libykcs11.dylib

But this path isn't valid for raspi, so I changed to this according to another tutorial:
> ssh-keygen -D /usr/local/lib/libykcs11.dylib

This path doesn't exist either. So how can I get this libykcs11.dylib work, please?

**Comment by mouse07410** [comment]
`libykcs11.dylib` makes sense **only** on Mac. You need to figure where on your system is file `libykcs11.so`.

**Comment by YoNevelt** [comment]
I was following this [https://gist.github.com/jamesog/b156c7a85e7f95046ca8b95f6f857f70](url) and it didn't mention Mac anywhere.
But as usual, I searched for a more likely found "libykcs" word and there was still nothing.

**Comment by mouse07410** [comment]
I suggest you follow my recommendation (locate where `libykcs11.so` was installed on your system) and report results here.

**Comment by YoNevelt** [comment]
There is no `libykcs11.so` file in my entire system at all. This is where my initial problem is. I expected this file was created by installing the above packages but no... this file doesn't exist. I used MC and also the following command (with and without sudo):
```
cd /
find . -name "libykcs11.so"
```

I tried to reinstall the packages as well, no positive result.
```
sudo apt install yubico-piv-tool --reinstall
```

**Comment by mouse07410** [comment]
I rarely use packages compiled by somebody else. So, no idea where `apt` picked the package from, nor what MC is. 

You can clone https://GitHub.com/Yubico/yubico-piv-tool.git and compile from the source. Then it will be installed in `/usr/local`

**Comment by a-dma** [comment]
`ykcs11` is its own package. Running `sudo apt install ykcs11` should get you what you need given that you were able to install `yubico-piv-tool`, i.e., given that your OS knows where to find those packages already or that you manually added Yubico's PPA.

**Comment by mouse07410** [comment]
I can understand installing the library (`ykcs11`) without the CLI (`yubico-piv-tool`). But how can the CLI install and work without the library it presumably depends on?

~~weirdness~~ over-cleverness of package maintainers is among the reasons why I try to build my packages myself. It tends to reduce the number of surprises, such as this one.

**Comment by a-dma** [comment]
the library would be `libykpiv` and that is indeed a dependency of both `yubico-piv-tool` and `ykcs11`. Those two, however, are completely independent from one another.

**Comment by mouse07410** [comment]
Works you care to explain the difference between `libykpiv` and `libykcs11`?

**Comment by a-dma** [comment]
`libykpiv` is the underlying library that takes care of the communication with the device. `libykcs11`, or simply `ykcs11`, is the PKCS#11 module.

**Comment by qpernil** [comment]
Im going to close this issue now, as it seems to be resolved. Please feel free to open a new issue as needed.
