### ISSUE TITLE
Have ykpiv_verify receive a byte array and not a string

### ISSUE THREAD

**Issue by a-dma** [Yubico/yubico-piv-tool#45]
In some cases (e.g. pkcs11) the pin is represented as a sequence of bytes rather than a string and it is not null terminated.

We should add a new function/refactor the signature of ykpiv_verify to be

`ykpiv_rc ykpiv_verify(ykpiv_state *state, const char *pin, size_t pin_len, int *tries);`

and avoid calling `strlen` inside.

**Comment by qpernil** [comment]
ykpiv_verify_select provides the requested functionality.
