### ISSUE TITLE
Why object management requires SO login?

### ISSUE THREAD

**Issue by yota9** [Yubico/yubico-piv-tool#453]
Hello!
It seems that creation, generation, deletion operations requires SO login, although it feels like the opposite should be. 
I'm judging from the softhsm2 project, where such operations requires user to be logged in. At first it felt unnatural, but after I realised that there is a good point in such approach. After all it is the user who would use the the key, not SO. And SO (let's suppose admin of some company) must not have an access to the private data stored on security key. The way I see it SO has to admin the key, e.g. re-initialize it after the user quits his job for the new employee. But the user must be able to generate, import & etc his private keys. I would ask to consider to change the policy, although I believe it's kind of legacy now and nobody would do it :) Anyway would be interesting to see opinions on this.
Thank you!

**Comment by qpernil** [comment]
The way this works is specified in the PIV specification, and we implement it according to that. That leaves no room for changing the behaviour I'm afraid.

**Comment by yota9** [comment]
Thanks @qpernil ! I read briefly the "Interfaces for Personal Identity Verification" document and indeed it says that e.g. asymmetric key generation must be under under PIV card administrator, thanks!
Closing the issue.
P.S. Would be thankful for #454 review :)
