### ISSUE TITLE
BUG: `2.4.0/2.4.1` - macOS `pkg` | `package receipt` is not applied properly to final release

### ISSUE THREAD

**Issue by radsec** [Yubico/yubico-piv-tool#460]
Please re-release the macOS universal packages to contain a `package version` applied to the resulting binaries/application.

See - bug - `2.4.0` - [yubico-piv-tool-2.4.0-mac-universal.pkg](https://developers.yubico.com/yubico-piv-tool/Releases/yubico-piv-tool-2.4.0-mac-universal.pkg)
<img width="904" alt="image" src="https://github.com/Yubico/yubico-piv-tool/assets/39590744/39548786-0dff-46d5-83b5-707843852220">

Expected -`2.4.0` - Reviewed the `github CI/workflows` and the `arm` package compiles correctly - https://github.com/Yubico/yubico-piv-tool/actions/runs/7051164256
<img width="912" alt="image" src="https://github.com/Yubico/yubico-piv-tool/assets/39590744/16b4ad92-e77b-4657-bd3c-6f8ed41d40f4">

Correctly working version - `2.3.1` - [yubico-piv-tool-2.3.1-mac-universal.pkg](https://developers.yubico.com/yubico-piv-tool/Releases/yubico-piv-tool-2.3.1-mac-universal.pkg)
<img width="904" alt="image" src="https://github.com/Yubico/yubico-piv-tool/assets/39590744/716bae7f-f588-4fb0-b6d7-f0f26c049ec0">

**Comment by aveenismail** [comment]
Thank you for the notification. Seems like some processes have changed from one version to another. Our release routines are now updated to make sure the version number appears correctly

**Comment by radsec** [comment]
Are you able to re-release the package on the public page: 

where the links are:https://developers.yubico.com/yubico-piv-tool/Releases/.

I just re-downloaded it and the internal `com.yubico.yubico-piv-tool` version is still `0.0` and showing incorrectly even though running the Github actions in this repo locally produce a binary with the correct package versions/receipts.

**Comment by korylprince** [comment]
Version 2.4.2 has the same issue, unfortunately. If you expand the [latest pkg](https://developers.yubico.com/yubico-piv-tool/Releases/yubico-piv-tool-2.4.2-mac-universal.pkg):

`pkgutil --expand-full yubico-piv-tool-2.4.2-mac-universal.pkg pkgfiles`

You'll see `pkgfiles/Distribution` now contains the correct version, but `pkgs/yubico-piv-tool.pkg/PackageInfo` still contains `version="0"`, causing the receipt to still have version 0:

![image](https://github.com/Yubico/yubico-piv-tool/assets/559762/0d4564ee-6bf3-49f4-a7dd-27b9e5bf42ab)

**Comment by radsec** [comment]
Fixed in `2.5.1`.

Thanks for getting this resolved.
