### ISSUE TITLE
ykcs11 library reports incorrect hardcoded token serial number

### ISSUE THREAD

**Issue by denisenkom** [Yubico/yubico-piv-tool#47]
```
pkcs11-tool --module libykcs11.dylib -T
```

```
  token label        : YubiKey PIV
  token manufacturer : Yubico
  token model        : YubiKey YK4
  token flags        : rng, login required, PIN initialized, token initialized
  hardware version   : 0.0
  firmware version   : 4.206
  serial num         : 1234
```

Here serial number is reported as 1234 which is incorrect.

I've found that another library: libykneomgr is reporting correct serial number.  I tried sending same APDU command as libykneomgr: `"\x00\x01\x10\x00"` but token doesn't report serial number when this command is called from ykcs11.  Is there a documentation on APDU commands supported by Yubikey?

**Comment by a-dma** [comment]
The serial number is pretty much a place holder, probably 0000 would be a better value.
Unfortunately there is no way of extracting the serial number through PIV.

A.

**Comment by denisenkom** [comment]
What do you think about using same algorithm as is used by OpenSC for PIV cards?  OpenSC derives serial number from CHUID, it basically takes FASC-N field if it is valid, otherwise it takes UUID, then it does bin2hex on it, and then it uses last 16 characters as serial number.

If this approach is good I can try implementing it myself.

**Comment by a-dma** [comment]
The YubiKey has its own serial number, and deriving a different number doesn't really make sense I believe.

**Comment by denisenkom** [comment]
So what do you think about implementing it in the same way libykneomgr is doing it?

I actually tried it as I wrote initially but it didn't work:
> I've found that another library: libykneomgr is reporting correct serial number. I tried sending same APDU command as libykneomgr: "\x00\x01\x10\x00" but token doesn't report serial number when this command is called from ykcs11. Is there a documentation on APDU commands supported by Yubikey?

**Comment by a-dma** [comment]
Unfortunately not, as I said before there is no way of accessing the serial number through PIV at this stage. This could be changed in a future firmware version but it requires some extra work.

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 contains a major upgrade to ykcs11. Please try with that version.
I believe the issue has been adressed, closing the issue. Please re-open if the problem persists.
