### ISSUE TITLE
The manual pages refer to pin policy availability only in Yk4, but it should also work in Yk5

### ISSUE THREAD

**Issue by Jakuje** [Yubico/yubico-piv-tool#479]
These are two lines from man page that say the pin policy is available only on Yk4:

https://github.com/Yubico/yubico-piv-tool/blob/f567b3588db84e073db4738fc27c4d662b3a253c/tool/cmdline.ggo#L74-L75

There might be some more outdated documentation that should be adjusted to match the reality.

**Comment by aveenismail** [comment]
Thank you for pointing that out. The help text has now been corrected and the change will be visible in the next release.
