### ISSUE TITLE
Add support to write signed CHUID

### ISSUE THREAD

**Issue by ryanchapman** [Yubico/yubico-piv-tool#48]
Please add the capability to write a signed CHUID, which is required for use with physical access control systems, such as pivCLASS.

**Comment by ryanchapman** [comment]
The more I think about this, the less I think the tool that communicates with the Yubikey needs to sign the CHUID.  Reason is in a lot of cases, the certificate authority (CA) administrator isn't the one who will write the certs and CHUID to the card.  Most likely what would happen is the CA admin generates a user certificate, a signed CHUID object, and hands that to the guy who provisions tokens (we'll call him the token admin).  The token admin then uses yubikey-piv-tool (or some GUI that uses yubikey-piv-tool under the covers) to write the user cert, user private key and signed CHUID to the Yubikey NEO.

So I'm thinking that a new binary should be created to be used by the CA admin which is takes as input:
1. CA cert/private key (is the cert needed?)
2. CHUID (FASC-N, expiration date, etc.)
and produces a binary file containing the signed CHUID.

Then the CA admin needs to generate the user cert/private key.  He puts the CHUID in the cert's subject alt name field (required by FIPS 201) and generates a p12 bundle.

The CHUID file and p12 are given to the token admin.

Token admin uses yubikey-piv-tool to write the p12 and CHUID file a Yubikey NEO.

Thoughts?

**Comment by klali** [comment]
Agreed on most of your points, which is why the tool right now doesn't care about signing because you probably want to sign it in another place anyways.
I had some thinking around allowing load of arbitrary objects: #31

**Comment by klali** [comment]
When looking at making something to generate a chuid theres a script to generate the fasc at https://github.com/Yubico/yubico-piv-tool/blob/master/tools/fasc.pl which might be helpful.

**Comment by mouse07410** [comment]
Probably (a) giving the ability to generate one's own CHUID (like `fasc.pl` does) and (b) enabling creation/write-to arbitrary objects on the card (with care! :) should address this issue.

Another option is to add the capability to the yubico-piv-tool to sign CHUID it generates with a certificate+key given as input parameter(s), but frankly it seems like quite some work. In the scenario that @ryanchapman outlined, the only thing yubico-piv-tool would need to do is writing a signed object to the card. No signing capability is needed in the yubico tool itself.

**Comment by Davidllo** [comment]
I'd prefer a separate PIV configuration tool that isn't specific to Yubico.  Signing BLOBs and installing them shouldn't depend on the manufacturer of PIV card.

Having said that: I haven't found an Open Source PIV toolset that I particularly like yet, so maybe this is as good a place as any to start building one!

**Comment by klali** [comment]
Closing this since the tool now can write arbitrary objects and will not be growing further capabilities to build signed objects.

**Comment by ryanchapman** [comment]
:+1:
