### ISSUE TITLE
RFE: Possibility of setting token label for certificates without a subject name

### ISSUE THREAD

**Issue by opoplawski** [Yubico/yubico-piv-tool#481]
We are using Active Directory to issue authentication certificates for our users.  Unfortunately Windows will only cache a single certificate for a particular subject for offline authentication - making the use of backup YKs problematic for roaming users.  To avoid this we have starting issuing certificates without subject names.  A side effect of this though it that the PKCS11 token id/label for the device becomes `PIV_II` instead of the user's full name as before.

Would there be any way to encode a user identifying label as the token id for subject-less certificates?  Thanks.

**Comment by qpernil** [comment]
May I ask what pkcs11 module you are using ?

**Comment by qpernil** [comment]
I might add that libykcs11 from yubico-piv-tool sets the token label to 'YubiKey PIV #%u' where %u is taken from the serial number of the YubiKey, so it's unrelated to certificates.

**Comment by opoplawski** [comment]
Hmm, maybe this isn't the right place to ask then.  We create the certificates on Windows with the YK minidriver installed.

**Comment by qpernil** [comment]
Closing this issue now. Feel free to open a new one if needed.
