### ISSUE TITLE
aes tests fail on big endian

### ISSUE THREAD

**Issue by sertonix** [Yubico/yubico-piv-tool#522]
The aes tests added in #514 fail on big endian systems.
```
7/9 Test #4: aes ..............................***Failed    0.04 sec
Running suite(s): libykpiv aes
40%: Checks: 5, Failures: 3, Errors: 0
/builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/lib/tests/aes.c:95:F:aes:test_encryption:0: Assertion 'rc == YKPIV_OK' failed
/builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/lib/tests/aes.c:95:F:aes:test_encryption:1: Assertion 'rc == YKPIV_OK' failed
/builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/lib/tests/aes.c:107:F:aes:test_decryption:0: Assertion 'd_len == dec_len' failed
```

@aveenismail You made the MR. Do you have any idea where the issue could be?

Full build logs: https://gitlab.alpinelinux.org/sertonix/aports/-/jobs/1657531

**Comment by aveenismail** [comment]
The log doesn't exactly show what the error is.  In your build directory, there should be a directory called "Testing". Somewhere there, there is a file containing the test log (On my system it's `build/Testing/Temporary/LastTest.log`). What does it say about the output of the aes test?

Also, can you run the following command with a YubiKey plugged in and copy the output here?

`$ yubico-piv-tool -a status --scp11 -v 5`

No need to copy all the output, just the output until and including the version number should be enough

**Comment by sertonix** [comment]
This is the contents of `LastTest.log`
```
Start testing: Dec 19 13:49 UTC
----------------------------------------------------------
4/9 Testing: aes
4/9 Test: aes
Command: "/builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/build/lib/tests/test_aes"
Directory: /builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/build/lib/tests/
"aes" start time: Dec 19 13:49 UTC
Output:
----------------------------------------------------------
Running suite(s): libykpiv aes
40%: Checks: 5, Failures: 3, Errors: 0
/builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/lib/tests/aes.c:95:F:aes:test_encryption:0: Assertion 'rc == YKPIV_OK' failed
/builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/lib/tests/aes.c:95:F:aes:test_encryption:1: Assertion 'rc == YKPIV_OK' failed
/builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/lib/tests/aes.c:107:F:aes:test_decryption:0: Assertion 'd_len == dec_len' failed
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"aes" end time: Dec 19 13:49 UTC
"aes" time elapsed: 00:00:00
----------------------------------------------------------
End testing: Dec 19 13:49 UTC
```

**Comment by aveenismail** [comment]
Hmm, it didn't have more information. I was hoping it would state what error code it's getting instead.

What OS are you running the tests on?

The functionality tested by the aes test is used to encrypt the communication with the YubiKey, which is supported only by newer YubiKeys. The test does not run on an actual YubiKey but any command line with the `--scp11` flag will attempt to open an encrypted connection using the these aes functions. So running for example `-a status --scp11 -v 5` will have more debug output that hopefully can help us pinpoint where the error occurs.

**Comment by Jakuje** [comment]
Same here on Fedora:

https://kojipkgs.fedoraproject.org//work/tasks/6131/127016131/build.log
https://koji.fedoraproject.org/koji/taskinfo?taskID=127015986

I will try to get some more useful logs from there

**Comment by Jakuje** [comment]
Ok, not much more useful:
https://koji.fedoraproject.org/koji/taskinfo?taskID=127016846

```
8/9 Test #4: aes ..............................***Failed    0.01 sec
Running suite(s): libykpiv aes
40%: Checks: 5, Failures: 3, Errors: 0
/builddir/build/BUILD/yubico-piv-tool-2.7.0-build/yubico-piv-tool-2.7.0/lib/tests/aes.c:95:F:aes:test_encryption:0: Assertion 'rc == YKPIV_OK' failed
/builddir/build/BUILD/yubico-piv-tool-2.7.0-build/yubico-piv-tool-2.7.0/lib/tests/aes.c:95:F:aes:test_encryption:1: Assertion 'rc == YKPIV_OK' failed
/builddir/build/BUILD/yubico-piv-tool-2.7.0-build/yubico-piv-tool-2.7.0/lib/tests/aes.c:107:F:aes:test_decryption:0: Assertion 'd_len == dec_len' failed
```
I can try to get the actual errors values if it will help.

**Comment by Jakuje** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=127017246
https://kojipkgs.fedoraproject.org//work/tasks/7276/127017276/build.log

```
/builddir/build/BUILD/yubico-piv-tool-2.7.0-build/yubico-piv-tool-2.7.0/lib/tests/aes.c:95:F:aes:test_encryption:0: Assertion 'rc == YKPIV_OK' failed: rc == -8, YKPIV_OK == 0
/builddir/build/BUILD/yubico-piv-tool-2.7.0-build/yubico-piv-tool-2.7.0/lib/tests/aes.c:95:F:aes:test_encryption:1: Assertion 'rc == YKPIV_OK' failed: rc == -8, YKPIV_OK == 0
/builddir/build/BUILD/yubico-piv-tool-2.7.0-build/yubico-piv-tool-2.7.0/lib/tests/aes.c:107:F:aes:test_decryption:0: Assertion 'd_len == dec_len' failed: d_len == 274877907199, dec_len == 61
```

**Comment by sertonix** [comment]
Patching `_ykpiv_debug` to always log messages :sweat_smile: :
```
DBG scp11_util.c:160 (scp11_encrypt_data): Key error: cipher_encrypt: -4
DBG scp11_util.c:160 (scp11_encrypt_data): Key error: cipher_encrypt: -4
40%: Checks: 5, Failures: 3, Errors: 0
/builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/lib/tests/aes.c:95:F:aes:test_encryption:0: Assertion 'rc == YKPIV_OK' failed
/builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/lib/tests/aes.c:95:F:aes:test_encryption:1: Assertion 'rc == YKPIV_OK' failed
/builds/sertonix/aports/community/yubico-piv-tool/src/yubico-piv-tool-2.7.0/lib/tests/aes.c:107:F:aes:test_decryption:0: Assertion 'd_len == dec_len' failed
```

**Comment by sertonix** [comment]
> Also, can you run the following command with a YubiKey plugged in and copy the output here?

Since all theses things run in a CI and I don't have a big endian machine myself I can't plug in a yubikey and run these commands.

**Comment by aveenismail** [comment]
Can you try building and testing with this branch: https://github.com/Yubico/yubico-piv-tool/tree/bigendian ? I fixed some problematic casting so hopefully it'll work better

**Comment by Jakuje** [comment]
Here is the build with the patch from the above branch

https://koji.fedoraproject.org/koji/taskinfo?taskID=127018803

**Comment by Jakuje** [comment]
It looks like your change in https://github.com/Yubico/yubico-piv-tool/tree/bigendian fixed this problem.

**Comment by aveenismail** [comment]
Great. Thanks for testing. I'll make sure to get a patch source release out as soon as possible

**Comment by aveenismail** [comment]
Source release 2.7.1 containing a fix for this issue is now out. Please let us know if the problem still persists

**Comment by Jakuje** [comment]
Builds ok in Fedora:
https://koji.fedoraproject.org/koji/taskinfo?taskID=127042386
Thank you for prompt fix!
