### ISSUE TITLE
SECURITY: Windows Installer vulnerable to DLL Hijacking attack

### ISSUE THREAD

**Issue by ericlaw1979** [Yubico/yubico-piv-tool#54]
![image](https://cloud.githubusercontent.com/assets/4192774/11955301/68a50bfe-a876-11e5-945c-d101a7e5d758.png)

Please upgrade from NSIS 2.46 to 2.49 or later.
http://textslashplain.com/2015/12/18/dll-hijacking-just-wont-die/

**Comment by klali** [comment]
Thank you for this report!
I suspect this is meant to live in https://github.com/Yubico/yubikey-piv-manager though so I'm going to close this issue. We're working to get new installers out where we're affected by this issue.
