### ISSUE TITLE
Impossible to import CA reply

### ISSUE THREAD

**Issue by mouse07410** [Yubico/yubico-piv-tool#55]
`yubico-piv-tool` and `YubiKey PIV Manager` allow to generate a new key on-board **and** output a Certificate Signing Request (CSR).
![yubi-piv-keygen](https://cloud.githubusercontent.com/assets/5923577/11960772/43d98116-a8a2-11e5-9baf-2d83d3556f54.png)

The problem is - once this CSR has been signed, there seems to be no way to import the CA reply (in .p7r format). How is one supposed to use this feature???

**Comment by klali** [comment]
I'm not sure what format p7r is, at a guess it's some sort of pkcs7 encoded data, the certificate should be extractable with openssl pkcs7

What gives this output? Is it commonly used?

**Comment by mouse07410** [comment]
> I'm not sure what format p7r is, at a guess it's some sort of pkcs7 encoded data,

Yes. Many apps wrap the CA response to CSR into this format. It seems to contain the newly-signed certificate, and the CA's own cert.

> the certificate should be extractable with openssl pkcs7

It turned out that yes it could be extracted with openssl, though with triple-dance.

```
$ openssl pkcs7 -text -inform DER -in yubi4-9e.p7r | openssl pkcs7 -print_certs -out yubi4-9e.pem
```
And then the resulting `yubi4-9e.pem` has to be manually edited to remove the descriptor lines outside the "---BEGIN-CERT---" and "---END-CERT---" block.
which seem to confuse YubiKey PIV Manager.

After that surgery certificates were imported successfully.

> What gives this output? Is it commonly used?

CAs, and apps like KeyStore Explorer. It is fairly common

Is there a reason why I can extract public key from the NEO and Yubikey 4 only after its **certificate** has been successfully loaded? I.e., why generating a new key pair in the slot is not sufficient?.

**Comment by mouse07410** [comment]
Well...?

**Comment by klali** [comment]
So I haven't ever seen this format in the wild. Since it can be converted to a supported format with openssl that's workable for me right now, I'd be happy to merge a pull request implementing this if the implementation is clean enough.

On extracting public key: The way the PIV standard looks the public key is given back on generate, after that you can't get it, so then it's extracted from the corresponding cert if that is loaded.

**Comment by mouse07410** [comment]
> I haven't ever seen this format in the wild.

I haven't seen a lot of it - but I have seen it. For one example, check here: https://github.com/kaikramer/keystore-explorer

> I'd be happy to merge a pull request implementing this if the implementation is clean enough.

I guess it's fair. Let me see what I can do.

> The way the PIV standard looks the public key is given back on generate, after that you
> can't get it, so then it's extracted from the corresponding cert if that is loaded.

Are you saying that the PIV standard explicitly forbids extracting the public key?! It sounds very strange. 

It basically means that unless the public key was captured immediately when the key pair was generated, the card is unusable without integrating it into PKI. (Some people may not need/want a PKI, and use the card as a hardware secure carrier of a key pair...)

Thanks!

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 contains a major upgrade to ykcs11. Please try with that version.

On a YubiKey newer than NEO you can get onboard-generated public keys through the attestation function. On even newer keys (ureleased yes) you can get them for imported keys as well.

There is currently unreleased code in master that uses this to expose the public keys even if no certificates are loaded. (An added benefit of this is that you get the correct public key even if an unmatching certificate has been loaded) However, ykcs11 will create a certificate signed by a throw-away key and store it in the device when you generate keys through it. This was implemented to support NEO keys. Another option which we are considering is to expose the public key as a session object, which would work with any reasonable application, i.e. one that picked up the public key in the same session as it was generated, and for any key,

I believe the issue has been adressed, closing the issue. Please re-open if the problem persists.
