### ISSUE TITLE
CKA_PUBLIC_EXPONENT - 3 Bytes

### ISSUE THREAD

**Issue by dnascimento** [Yubico/yubico-piv-tool#61]
The latest version trims the the prefix and suffix of CKA_MODULUS. However, CKA_PUBLIC_EXPONENT returns 3 bytes. The bytes are correct but why 3 instead of 4 or 8 bytes?
Notice: I'm using https://github.com/miekg/pkcs11 Go Lang Lib

**Comment by a-dma** [comment]
That's how you typically represents numbers in crypto related applications. Big numbers (e.g., 2048-bit numbers) won't fit in a regular variable. To obviate to this, alternative representations are used (MPIs or DER/BER for example). This typically involves having the actual value represented as sequence of bytes that can be, depending on the encoding, as short as possible.
PKCS#11 is no exception. CKA_PUBLIC_EXPONENT is a BigInteger, which is defined as:

```
a string of CK_BYTEs representing an unsigned integer of arbitrary size,
most-significant byte first (e.g., the integer 32768 is represented
as the 2-byte string 0x80 0x00)
```

**Comment by dnascimento** [comment]
Ok, thanks for the clarification @a-dma :)
