### ISSUE TITLE
Can not import retired private key

### ISSUE THREAD

**Issue by nexussafe** [Yubico/yubico-piv-tool#64]
I am trying to import private key to slot 82 (retired) and getting following error:

> tool/yubico-piv-tool -a import-key -s 82 --key=111111111111111111111111111111111111111111111111 -i privateKey.key --verbose=2
trying to connect to reader 'Yubico Yubikey NEO CCID'.
> 00 a4 04 00 05 a0 00 00 03 08 
< 61 11 4f 06 00 00 10 00 01 00 79 07 4f 05 a0 00 00 03 08 90 00 
Authenticating since action 'import-key' needs that.
> 00 87 03 9b 04 7c 02 80 00 
< 7c 0a 80 08 e8 ae 08 79 47 d6 06 44 90 00 
> 00 87 03 9b 16 7c 14 80 08 6a 72 73 c3 77 60 8e 4a 81 08 11 8a d1 69 bc 41 8c 0f 
< 7c 0a 82 08 55 22 7f c2 51 44 5a 55 90 00 
Successful application authentication.
Now processing for action 'import-key'.
Going to send 255 bytes in this go.
> 10 fe 06 82 ff 01 40 ed aa 11 78 30 91 48 26 77 69 b5 a3 3e 0e 7d a9 77 1b 2f 08 65 04 3b dc d2 81 f3 c3 63 fa 17 6b f0 7c 5d f8 da 83 21 ef 46 13 4e cc 46 bc be 84 21 6b 22 78 27 fc d0 93 a6 f9 41 1b f3 2e 26 23 02 40 d2 78 b2 5f 80 3e 1a cb 2b 64 5e 77 08 87 1a 11 0f e0 48 b4 f5 c3 a3 39 1d 02 9f ca dd a9 e2 51 78 7c 12 69 a1 2c b2 d4 df 30 a5 03 e0 57 ad 48 13 45 36 31 e3 30 30 57 38 62 a3 6f 09 1c da 85 03 40 c6 4d a0 33 f3 fa 55 04 5b a0 e5 80 e6 f7 ba 5c 5b 58 60 3f 15 e2 99 7c 60 5d 34 22 f5 59 a8 8f 54 e2 c0 9a 32 e1 35 c0 6b 6d 12 d3 99 b6 45 15 04 b9 5a d2 7d 33 12 6a 10 e9 6b 2d 42 14 60 97 04 40 6e 33 ca 59 dc e1 27 d0 57 a1 0f 21 4e 72 c7 00 46 0a ce a7 09 c3 ed 13 fb 8f a3 31 6a 8d 08 36 56 5a c8 9d 4c 4a 06 3d 15 bb f7 bb 26 dd 61 9a ca 94 43 c3 2d 4c cf 
< 90 00 
Going to send 75 bytes in this go.
> 00 fe 06 82 4b 12 ec 30 21 99 02 f1 7b ad 05 40 9f c5 17 13 07 a4 aa ba 2a 1b f7 6c 6f 68 39 ca 15 73 66 01 c1 2f 45 98 32 ab 5f 17 e3 4b bc ed a5 6e 3e 5c cd 88 cf d9 3c 04 19 05 cd 31 a0 f4 66 02 1c fd d4 46 bf 52 47 19 b6 03 91 2b fc bb 
< 6a 80 
Unable to import private key

**Comment by a-dma** [comment]
Retired keys are not available on YubiKey NEO. They have been introduced with YuibKey 4.
