### ISSUE TITLE
[question] possible to use within a container?

### ISSUE THREAD

**Issue by bibby** [Yubico/yubico-piv-tool#68]
Greetings.

I'm investigating the possible use of my YubiKey4, using `yubico-piv-tool` from _inside_ a docker container. Both host and container image are running Ubuntu 14.04, with the yubikey attached to the host. The device works as expected from the host OS. But within the container, I can't seem to get passed a message: `Failed to connect to reader.`

A glimmer of hope was given by [this post](http://forum.yubico.com/viewtopic.php?f=26&t=2121), in which a user appears successful in running their U2F device.

In my `Dockerfile`, I'm compiling `pcsc-lite, ccid, openct` and `opensc` libraries (to control versions); and creating `udev` rules as was necessary to make use of the device from the host machine.

    ENV PCSC_VERSION 1.8.13
    ENV CCID_CERSION 1.4.18
    ENV OPENCT_VERSION 0.6.20
    ENV OPENSC_VERSION 0.15.0

Has anyone (community at large) had any success accessing their YubiKey4 from within a docker container? If so, I'd love to hear from you!

Edit: markdown link components reversed

**Comment by a-dma** [comment]
Support for the YubiKey 4 has been added with libccid version 1.4.20, see [1].
You can try and manually patch the /etc/libccid_info.plist file, there is a script to do that, see [2].

Also, if you only care about yubico-piv-tool, udev rules shouldn't be necessary.

[1] - http://ludovicrousseau.blogspot.se/2015/08/new-version-of-libccid-1420.html
[2] - https://github.com/Yubico/yubioath-desktop-dpkg/blob/master/resources/linux-patch-ccid

**Comment by bibby** [comment]
Thanks for the response, @a-dma . I've updated my libraries to use libccid 1.4.20 (and also the latest), but my results are the same. For completeness and for curious future visitors, I'm attaching my `Dockerfile` and runner script.

_named {}.txt, so that github would accept the uploads_
[Dockerfile.txt](https://github.com/Yubico/yubico-piv-tool/files/163666/Dockerfile.txt)

[run.sh.txt](https://github.com/Yubico/yubico-piv-tool/files/163667/run.sh.txt)

The mean build time for the image on my machine without caches is about 7 minutes, should anyone try it.

**Comment by a-dma** [comment]
I've tried to build your image. Not sure why but it looks like the plist file doesn't get installed correctly.

As a quick test I tried to manually copy it with `cp /tmp/ccid-1.4.20/src/Info.plist /etc/libccid_Info.plist` and after restarting pcscd everything seems to be working fine.

**Comment by bibby** [comment]
I see. The `yubico-piv-tool` package in the ppa installs libccid 1.4.15 ; perhaps I skip the ppa and try buliding it from source as well.

This happened when I reordered the steps, and the desired Info.plist was in place.

```
Preparing to unpack .../yubico-piv-tool_1.3.0-1~ppa1~trusty1_amd64.deb ...                                                               [16/1946]
Unpacking yubico-piv-tool (1.3.0-1~ppa1~trusty1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up libpcsclite1:amd64 (1.8.10-1ubuntu1) ...
Setting up libykpiv1 (1.3.0-1~ppa1~trusty1) ...
Setting up libccid (1.4.15-1) ...
Setting up yubico-piv-tool (1.3.0-1~ppa1~trusty1) ...

Configuration file '/etc/libccid_Info.plist'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
```

I had a successful test, though!
Searching through various githup repos, I found that if I add a volume for `/var/run/pcscd/pcscd.comm` from the host, I finally get a response to `verify-pin`.

I'll keep noodling for a few hours and likely close this issue today. I truly appreciate your participation in my flailing. All the best!

**Comment by bibby** [comment]
The inclusion of `pcscd.comm` appears to be an easy out; and good enough for me for the time being. I suppose the caveat is that the docker host must be prepared in such a way that `yubico-piv-tool` works for itself, but seems a reasonable expectation.

The Dockerfile need only install `yubico-piv-tool`; the ppa works fine for this.
At run time, voluming-in the pcscd.comm is all that's needed.

Attaching working Dockerfile and run script (assumes tool works on the host).
[Dockerfile.txt](https://github.com/Yubico/yubico-piv-tool/files/165725/Dockerfile.txt)
[run.sh.txt](https://github.com/Yubico/yubico-piv-tool/files/165726/run.sh.txt)

I think this gets me what I'm after, so I'll close this issue. If for some reason you think this hack is a terrible thing to do or there is a safer, more appropriate method to achieve tool function in docker, I'm genuinely interested. 

I was not able to recreate your success moving the plist and restarting pcscd.

**Comment by a-dma** [comment]
To be honest I didn't muck around with this too much. I just run an interactive container and tried a few things. Restarting pcscd was more of a quick way to make sure the changes took effect, probably reloading would suffice.

I'm by no means a Docker expert, but I guess both your solutions are fine, it depends where you want to draw the line between what is running in your container and what isn't. If you pipe through the USB subsystem, then you need to run pcscd yourself. If you pipe the socket through then it's good enough to know how to write into/read from it. I know it's better to run a single process within each container, so probably the second solution is a better.
