### ISSUE TITLE
PIV VERIFY returns '63 Cx' on unlocked token instead of '90 00'

### ISSUE THREAD

**Issue by mouse07410** [Yubico/yubico-piv-tool#77]
According to NIST SP 800-73-3 part 2 page 11 (and SP 800-73-4 part 2 page 13), when PIV VERIFY command is sent to the token,
> If Lc=0x00 (as per 73-3) or absent (as per 73-4) *and* the command data field is empty, the command can be used to retrieve the number of further retries allowed ('63 CX'), or to check whether verification is not needed ('90 00').

This is understood as "if the token is locked return '63 CX', if the token is unlocked return '90 00').

Yubikey NEO (both older ones with serial numbers 36xxxxx and below, and newer ones with serial numbers 38xxxxx and above) always replies to `00 20 00 80 00` with `63 Cx`. Excerpt from the log of the NEO interactions with javax.smartcardio-based low-level test-app:
```
. . . . .
VERIFY  CommandAPDU: 00 20 00 80 00
               ResponseAPDU: 2 bytes, SW=63c5        [correct response - token is locked at this point]
          ------------------------------
VERIFY  CommandAPDU: 00 20 00 80 08 31 32 33 34 35 36 FF FF
               ResponseAPDU: 2 bytes, SW=9000
          ------------------------------
VERIFY CommandAPDU: 00 20 00 80 00
              ResponseAPDU: 2 bytes, SW=63c5         [incorrect: token unlocked, so should be 9000]
. . . . .
```

**Comment by klali** [comment]
Yes, this seems like a bug, it will be fixed in future revisions. Thanks!

I'm closing this since this issue tracker is officially for the yubico-piv-tool not for what is on the actual keys.

**Comment by mouse07410** [comment]
> Yes, this seems like a bug, it will be fixed in future revisions

@klali Thank you!  Could you give me an idea when I could hope to see token (I assume - NEO and 4) with fixed firmware?

> I'm closing this since this issue tracker is officially for the yubico-piv-tool not for what is on the actual keys.

Sure.

There's another thing: according to PIV standard, some objects must be on the token (and access to them is PIN-protected). NEO (and 4) currently don't have them, and respond with `6A 82` (see https://github.com/OpenSC/OpenSC/pull/624#issuecomment-227573711). Any chance to address that?

**Comment by klali** [comment]
No timeline at the moment, will be in for the next update of the firmware.

And yes, that update will adress this second issue as well. Thank you!

**Comment by mouse07410** [comment]
Thanks!!
