### ISSUE TITLE
Object Value length > 1024 bytes

### ISSUE THREAD

**Issue by dnascimento** [Yubico/yubico-piv-tool#79]
Is it ok to update the get_coa object buffer to 2048 instead of 1024? I can store certificates bigger than 1024.
https://github.com/Yubico/yubico-piv-tool/blob/master/ykcs11/objects.c#L449

I tested it and it works.

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 is out and contains a major update to ykcs11. Please try with that version.
The issue you mention has ben adressed in that release, so I'm closing this release due to age.
Please re-open if the problem persists.
