### ISSUE TITLE
ykcs11: C_GetMechanismInfo should return CKR_MECHANISM_INVALID on digest mechanisms until Digest is implemented

### ISSUE THREAD

**Issue by blaufish** [Yubico/yubico-piv-tool#81]
Returning CKR_OK on unsupported mechanisms screws up compatibility checks

**Comment by a-dma** [comment]
I've changed all the non implemented functions to return CKR_FUNCTION_FAILED (see #84).

It's not *too* much work to fix digest, but currently I'm buried in other things.
When I can spend some time on this project I'll cleanup the code a bit.

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 contains a major upgrade to ykcs11. Please try with that version.
I believe the issue has been adressed, closing the issue. Please re-open if the problem persists.
