### ISSUE TITLE
ykcs11: implement CKM_ECDSA CKA_EC_PARAMS support for P-384 etc

### ISSUE THREAD

**Issue by blaufish** [Yubico/yubico-piv-tool#83]
Only CKA_EC_PARAMS support for PRIME256V1 currently

**Comment by qpernil** [comment]
yubico-piv-tool 2.0.0 is out and contains a major update to ykcs11. Please try with that version.
The issue you mention has ben adressed in that release, so I'm closing this release due to age.
Please re-open if the problem persists.
