### ISSUE TITLE
 Enforce a minimum PIN length of 6 characters.

### ISSUE THREAD

**Issue by c3ph3us** [Yubico/yubico-piv-tool#85]
how i was surprised :) when i wanted unblock pin :) 

         Minimum 6 digits of PIN supported

yes i see in docs:

       yubico-piv-tool NEWS — History of user-visible changes. -- outline --
       Version 1.4.0 (released 2016-05-03)

        Enforce a minimum PIN length of 6 characters.

do i need to make my own version or do you implement some option to switch back to 4 digit pin ? or there already is some sort of option to allow use 4 digit pin ?

you should not enforce any length "in my opinion"  as user wants should be able to set zero length pin :)  

i haven't seen in my country any debit or credit card with 6 digit pin !!!  they all use 4

**Comment by a-dma** [comment]
I don't mean this in the wrong way, but "in my opinion" doesn't cut the mustard.

 According to the PIV specifications:
> [...] the PIV Card Application PIN shall be between 6 and 8 bytes in length [...]

For what it's worth, I agree that the user should be able to not use a PIN if they wanted, but when there are several mutually exclusive options we usually do what official specifications say.

**Comment by c3ph3us** [comment]
@a-dma pleas consider how big impact has changing to enforce a 6 digit pin when from 2012 user used to use 4 digit pin 

i'm one of those users which must get used to this new situation and i tell you why it so annoying:

I use yubi as pkcs11 provider to :

        1) authenticate on my machine as an user  
        2) authorize as sudo, 
        3) for ssh login and remote administration 
        4) or many many more... 

Do you know how many operations do i do daily with piv applet ??? probably more than you can imagine. Now consider i used to use 4 digit pin from year  2012 ..  can you tell me how often now I get wrong in entering pin ?? and further how this has an effect on course of events... i need provide a full password or begin from start :) this takes time!  plus i need type 20% more of text ( this is not annoying if u do it once twice daily - but not hundred times) 

so do you take for an consideration side effects or the impact of your decisions ?  if you do such drastically changes? 

so still I stand on the position you should give to an user a choice (for example by implementing a option to lower requirement for pin length) - and not to force him to search for an "hack" (regardless of path - changing code / changing software) - because now i'm using piv manager but i will not any more - for my comfort. And keep in mind  that if no one else is arguing on theme does not mean that there are no more unhappy as I am

**Comment by a-dma** [comment]
As I said before, I agree with you that users should be allowed to choose what kind of PIN the want to use. However, in this case it is not a matter of what you and I prefer, but rather a matter of following specifications.

The only solution I can offer is to change the PIN policy on your YubiKey so that a PIN is only required once or not at all, depending what you prefer, and maybe enable touch. Keep in mind that the tool itself may not be aware of the change and still ask for the PIN.

I know it's far from a perfect solution, but it is what it is.

**Comment by c3ph3us** [comment]
@a-dma 
> so that a PIN is only required once

once per  ...?

**Comment by a-dma** [comment]
Once per session (basically a power cycle).
