### ISSUE TITLE
ykcs11: Allow C_Login() with short PIN

### ISSUE THREAD

**Issue by dwmw2** [Yubico/yubico-piv-tool#95]
I've been using a Yubkey NEO for testing PKCS#11 for a while; it has the PIN `1234`. 

I can understand refusing to _set_ that PIN any more, and enforcing a PIN length. But when the PIN on the device _is_ that short, ykcs11 is refusing to even try it. Can't we relax that check?

**Comment by qpernil** [comment]
It's a bit of a conundrum - If we allow 4 characters, should we also say that minimum PIN length is 4 in C_GetTokenInfo ? Or allow 4 while still saying 6 in the info, according to the PIV spec ?
Isn't it easier to just change the PIN ?

**Comment by qpernil** [comment]
Closing this as it's old and easy to work around.
