### ISSUE TITLE
Feature request: make debugging output controlled by env variable

### ISSUE THREAD

**Issue by mouse07410** [Yubico/yubico-piv-tool#99]
It is a royal pain to have to recompile `yubico-piv-tool` every time I need to turn debugging output on and off. This tool is still buggy enough to want debugging output often, but some operations do work, and for those I don't want to pollute the screen with the ton of debugging messages it produces.

So, can you please add env variable, e.g., `YKCS11_DEBUG`, and print debugging output if it is set to "yes"?

**Comment by a-dma** [comment]
I totally agree with this, it's on my radar and I wanted to do this for some time.
Don't mean to sound like a broken record, but the usual rant about lack of time applies.
I'll try to take a day to work on some of these issues and at least try to solve the low-hanging ones (like this one).

**Comment by qpernil** [comment]
Yubico PIV tool 2.0.0 was recently released, but this feature didn't make it into that release. A new minor release is planned for the near future, and this will definitely be a candidate for that release.

**Comment by qpernil** [comment]
This has now been implemented on the master branch, and will be included in the 2.0.1 release.
With that you can now turn on debug output by setting the YKCS11_DBG environment variable to the verbosity level desired (default 0, no output). If you compile with YKCS11_DBG enabled the verbosity level is compiled in as specified, and the environment variable is ignored. If compiled this way you also get function entry/exit tracing in ykcs11.
